Repository automatisch/automatisch, pull requests merged in 2022-11, with the labels that each got.

#673 feat(slack): add bot capability in send message action
  packages/backend/src/apps/slack/actions/send-a-message-to-channel/index.ts
  packages/backend/src/apps/slack/actions/send-a-message-to-channel/post-message.ts
  packages/backend/src/apps/slack/auth/create-auth-data.ts
  packages/backend/src/apps/slack/auth/index.ts
  packages/backend/src/apps/slack/auth/is-still-verified.ts
  packages/backend/src/apps/slack/auth/verify-credentials.ts
  packages/backend/src/apps/slack/common/add-auth-header.ts
  packages/backend/src/apps/slack/common/get-current-user.ts
  packages/backend/src/helpers/compute-parameters.ts
  packages/docs/pages/apps/slack/connection.md
  packages/types/index.d.ts
Labels: enhancement

#674 Remove reconnection steps
  packages/backend/src/apps/discord/auth/index.ts
  packages/backend/src/apps/flickr/auth/index.ts
  packages/backend/src/apps/github/auth/index.ts
  packages/backend/src/apps/slack/auth/index.ts
  packages/backend/src/apps/smtp/auth/index.ts
  packages/backend/src/apps/twilio/auth/index.ts
  packages/backend/src/apps/twitter/auth/index.ts
  packages/backend/src/graphql/schema.graphql
  packages/backend/src/helpers/add-reconnection-steps.ts
  packages/backend/src/helpers/get-app.ts
  packages/types/index.d.ts
  packages/web/src/components/AppConnectionRow/index.tsx
  packages/web/src/graphql/queries/get-app.ts
  packages/web/src/graphql/queries/get-apps.ts
Labels: enhancement

#676 feat(salesforce): add authentication
  packages/backend/src/apps/salesforce/assets/favicon.svg
  packages/backend/src/apps/salesforce/auth/create-auth-data.ts
  packages/backend/src/apps/salesforce/auth/index.ts
  packages/backend/src/apps/salesforce/auth/is-still-verified.ts
  packages/backend/src/apps/salesforce/auth/verify-credentials.ts
  packages/backend/src/apps/salesforce/common/add-auth-header.ts
  packages/backend/src/apps/salesforce/common/get-current-user.ts
  packages/backend/src/apps/salesforce/index.d.ts
  packages/backend/src/apps/salesforce/index.ts
  packages/web/src/components/InputCreator/index.tsx
Labels: enhancement

#681 feat(salesforce): add updated field in objects trigger
  packages/backend/src/apps/salesforce/data/index.ts
  packages/backend/src/apps/salesforce/data/list-fields/index.ts
  packages/backend/src/apps/salesforce/data/list-objects/index.ts
  packages/backend/src/apps/salesforce/index.ts
  packages/backend/src/apps/salesforce/triggers/index.ts
  packages/backend/src/apps/salesforce/triggers/updated-field-in-objects/index.ts
  packages/backend/src/apps/salesforce/triggers/updated-field-in-objects/updated-field-in-objects.ts
  packages/web/src/components/TestSubstep/index.tsx
  packages/web/src/graphql/queries/get-apps.ts
Labels: enhancement

#689 docs(salesforce): describe auth and triggers
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/.vitepress/theme/custom.css
  packages/docs/pages/apps/salesforce/connection.md
  packages/docs/pages/apps/salesforce/triggers.md
  packages/docs/pages/public/favicons/salesforce.svg
Labels: documentation

#696 feat: eager load apps
  packages/backend/src/helpers/get-app.ts
Labels: enhancement

#698 feat(web): hide empty error tab in execution step
  packages/web/src/components/ExecutionStep/index.tsx
Labels: enhancement

#699 feat(web): add status in execution row
  packages/types/index.d.ts
  packages/web/src/components/ExecutionRow/index.tsx
  packages/web/src/graphql/queries/get-executions.ts
  packages/web/src/locales/en.json
Labels: enhancement

#702 feat: add circular progress in flow step
  packages/web/src/components/FlowStep/index.tsx
Labels: enhancement

#703 Docs/build integrations
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/build-integrations/actions.md
  packages/docs/pages/build-integrations/app.md
  packages/docs/pages/build-integrations/auth.md
  packages/docs/pages/build-integrations/examples.md
  packages/docs/pages/build-integrations/folder-structure.md
  packages/docs/pages/build-integrations/global-variable.md
  packages/docs/pages/build-integrations/triggers.md
Labels: documentation

#704 feat: add .all support in auth arguments
  packages/backend/src/apps/deepl/auth/index.ts
  packages/backend/src/apps/discord/auth/generate-auth-url.ts
  packages/backend/src/apps/discord/auth/index.ts
  packages/backend/src/apps/discord/auth/verify-credentials.ts
  packages/backend/src/apps/flickr/auth/generate-auth-url.ts
  packages/backend/src/apps/flickr/auth/index.ts
  packages/backend/src/apps/flickr/auth/verify-credentials.ts
  packages/backend/src/apps/github/auth/generate-auth-url.ts
  packages/backend/src/apps/github/auth/index.ts
  packages/backend/src/apps/github/auth/verify-credentials.ts
  packages/backend/src/apps/salesforce/auth/generate-auth-url.ts
  packages/backend/src/apps/salesforce/auth/index.ts
  packages/backend/src/apps/slack/auth/generate-auth-url.ts
  packages/backend/src/apps/slack/auth/index.ts
  packages/backend/src/apps/smtp/auth/index.ts
  packages/backend/src/apps/twilio/auth/index.ts
  packages/backend/src/apps/twitter/auth/generate-auth-url.ts
  packages/backend/src/apps/twitter/auth/index.ts
  packages/backend/src/apps/twitter/auth/verify-credentials.ts
  packages/backend/src/errors/generate-auth-url.ts
  packages/backend/src/graphql/mutation-resolvers.ts
  packages/backend/src/graphql/mutations/generate-auth-url.ts
  packages/backend/src/graphql/schema.graphql
  packages/backend/src/helpers/add-authentication-steps.ts
  packages/backend/src/helpers/get-app.ts
  packages/types/index.d.ts
  packages/web/src/graphql/mutations/create-auth-data.ts
  packages/web/src/graphql/mutations/generate-auth-url.ts
  packages/web/src/graphql/mutations/index.ts
  packages/web/src/helpers/computeAuthStepVariables.ts
Labels: enhancement

#712 Release v0.2.0
  docker/images/main/Dockerfile
  docker/images/worker/Dockerfile
  lerna.json
  packages/backend/package.json
  packages/cli/package.json
  packages/docs/package.json
  packages/e2e-tests/package.json
  packages/types/package.json
  packages/web/package.json
Labels: release

#714 chore: add project name in docker compose
  docker/compose/docker-compose.yml
Labels: enhancement

#717 feat: show doc info in auth dialog in editor
  packages/web/src/graphql/queries/get-apps.ts
Labels: enhancement

#729 docs: Add explanation of automatic error handling for http client
  packages/docs/pages/build-integrations/global-variable.md
Labels: documentation

#726 fix: use actual DB name in wait for postgres script
  docker/images/main/wait-for-postgres.sh
  docker/images/worker/wait-for-postgres.sh
Labels: bug

#744 feat(http-error): add response
  packages/backend/src/errors/http.ts
Labels: enhancement

#746 Separate dockerfile for release
  docker-compose.yml
  docker/Dockerfile
  docker/Dockerfile.compose
  docker/compose-entrypoint.sh
  docker/entrypoint.sh
  docker/images/main/wait-for-postgres.sh
  docker/images/worker/wait-for-postgres.sh
Labels: enhancement

#748 feat: accept username, password, tls for redis configuration
  packages/backend/.env-example
  packages/backend/src/config/app.ts
  packages/backend/src/config/redis.ts
  packages/docs/pages/advanced/configuration.md
Labels: enhancement

#759 Add new entry trigger for typeform with webhook support
  packages/backend/.env-example
  packages/backend/src/app.ts
  packages/backend/src/apps/typeform/assets/favicon.svg
  packages/backend/src/apps/typeform/auth/generate-auth-url.ts
  packages/backend/src/apps/typeform/auth/index.ts
  packages/backend/src/apps/typeform/auth/is-still-verified.ts
  packages/backend/src/apps/typeform/auth/refresh-token.ts
  packages/backend/src/apps/typeform/auth/verify-credentials.ts
  packages/backend/src/apps/typeform/auth/verify-webhook.ts
  packages/backend/src/apps/typeform/common/add-auth-header.ts
  packages/backend/src/apps/typeform/common/auth-scope.ts
  packages/backend/src/apps/typeform/dynamic-data/index.ts
  packages/backend/src/apps/typeform/dynamic-data/list-forms/index.ts
  packages/backend/src/apps/typeform/index.d.ts
  packages/backend/src/apps/typeform/index.ts
  packages/backend/src/apps/typeform/triggers/index.ts
  packages/backend/src/apps/typeform/triggers/new-entry/index.ts
  packages/backend/src/config/app.ts
  packages/backend/src/controllers/webhooks/handler.ts
  packages/backend/src/graphql/mutations/update-flow-status.ts
  packages/backend/src/helpers/global-variable.ts
  packages/backend/src/helpers/graphql-instance.ts
  packages/backend/src/routes/index.ts
  packages/backend/src/routes/webhooks.ts
  packages/backend/src/services/flow.ts
  packages/types/index.d.ts
Labels: enhancement
