Repository automatisch/automatisch, pull requests merged in 2022-10, with the labels that each got.

#601 docs(readme): remove github community link
  README.md
Labels: hacktoberfest-accepted

#602 fix: Do not sort user tweets since it's in reverse-chronological order
  packages/backend/src/apps/twitter/common/get-user-tweets.ts
  packages/backend/src/apps/twitter/triggers/my-tweets/index.ts
  packages/backend/src/apps/twitter/triggers/user-tweets/index.ts
Labels: bug

#603 fix: only show apps with actions in action step
  packages/backend/src/graphql/queries/get-apps.ts
  packages/backend/src/graphql/schema.graphql
  packages/web/src/components/ChooseAppAndEventSubstep/index.tsx
  packages/web/src/components/ExecutionStep/index.tsx
  packages/web/src/components/FlowStep/index.tsx
  packages/web/src/graphql/queries/get-apps.ts
Labels: bug

#605 fix(scheduler): return TriggerDataItem
  packages/backend/src/apps/scheduler/triggers/every-day/index.ts
  packages/backend/src/apps/scheduler/triggers/every-hour/index.ts
  packages/backend/src/apps/scheduler/triggers/every-month/index.ts
  packages/backend/src/apps/scheduler/triggers/every-week/index.ts
Labels: bug

#604 feat(FlowEditor): allow adding new connection in step
  packages/web/src/components/AddAppConnection/index.tsx
  packages/web/src/components/ChooseConnectionSubstep/index.tsx
  packages/web/src/components/FlowStep/index.tsx
  packages/web/src/locales/en.json
Labels: enhancement

#608 chore(docs): update copyright date
  packages/docs/pages/.vitepress/config.js
Labels: documentation, hacktoberfest-accepted

#607 feat: add defineTrigger and defineAction
  packages/backend/package.json
  packages/backend/src/apps/scheduler/common/get-date-time-object.ts
  packages/backend/src/apps/scheduler/index.ts
  packages/backend/src/apps/scheduler/triggers/every-day/index.ts
  packages/backend/src/apps/scheduler/triggers/every-hour/index.ts
  packages/backend/src/apps/scheduler/triggers/every-month/index.ts
  packages/backend/src/apps/scheduler/triggers/every-week/index.ts
  packages/backend/src/apps/slack/actions/find-message/find-message.ts
  packages/backend/src/apps/slack/actions/find-message/index.ts
  packages/backend/src/apps/slack/actions/send-a-message-to-channel/index.ts
  packages/backend/src/apps/twitter/triggers/my-tweets/index.ts
  packages/backend/src/apps/twitter/triggers/new-follower-of-me/index.ts
  packages/backend/src/apps/twitter/triggers/search-tweets/index.ts
  packages/backend/src/apps/twitter/triggers/user-tweets/index.ts
  packages/backend/src/helpers/app-info-converter.ts
  packages/backend/src/helpers/define-action.ts
  packages/backend/src/helpers/define-trigger.ts
  packages/backend/src/helpers/get-app.ts
  packages/backend/src/services/action.ts
  packages/types/index.d.ts
  packages/web/src/components/FlowStep/index.tsx
  packages/web/src/components/InputCreator/index.tsx
  packages/web/src/hooks/useDynamicData.ts
Labels: enhancement

#612 docs(readme): remove trailing slash in docs link
  README.md
Labels: documentation, hacktoberfest-accepted

#554 feat: soft delete database entities
  packages/backend/src/db/migrations/20220928162525_soft-delete-base-model.ts
  packages/backend/src/helpers/pagination.ts
  packages/backend/src/models/base.ts
  packages/backend/src/models/flow.ts
  packages/backend/src/models/query-builder.ts
  packages/backend/src/models/user.ts
Labels: enhancement

#616 feat: add defineApp and beforeRequest
  packages/backend/src/apps/github/common/add-auth-header.ts
  packages/backend/src/apps/github/index.ts
  packages/backend/src/helpers/define-app.ts
  packages/backend/src/helpers/global-variable.ts
  packages/backend/src/helpers/http-client/index.ts
  packages/types/index.d.ts
  packages/web/src/components/AddAppConnection/index.tsx
Labels: enhancement

#624 feat(github): add new issues trigger
  packages/backend/src/apps/github/common/get-repo-owner-and-repo.ts
  packages/backend/src/apps/github/common/paginate-all.ts
  packages/backend/src/apps/github/data/list-labels/index.ts
  packages/backend/src/apps/github/data/list-repos/index.ts
  packages/backend/src/apps/github/triggers/new-issues/index.ts
  packages/backend/src/apps/github/triggers/new-issues/new-issues.ts
  packages/backend/src/graphql/queries/get-data.ts
  packages/backend/src/helpers/parse-header-link.ts
  packages/backend/src/services/action.ts
  packages/backend/src/services/trigger.ts
  packages/web/src/components/ControlledAutocomplete/index.tsx
  packages/web/src/components/InputCreator/index.tsx
  packages/web/src/hooks/useDynamicData.ts
Labels: enhancement

#625 feat(github): add new stargazer trigger
  packages/backend/src/apps/github/triggers/new-stargazers/index.ts
  packages/backend/src/apps/github/triggers/new-stargazers/new-stargazers.ts
Labels: enhancement

#629 feat(github): add new watcher trigger
  packages/backend/src/apps/github/triggers/new-watchers/index.ts
  packages/backend/src/apps/github/triggers/new-watchers/new-watchers.ts
Labels: enhancement

#630 feat(github): add create issue action
  packages/backend/src/apps/github/actions/create-issue/index.ts
Labels: enhancement

#631 feat(flickr): add authentication
  packages/backend/src/apps/flickr/auth/create-auth-data.ts
  packages/backend/src/apps/flickr/auth/index.ts
  packages/backend/src/apps/flickr/auth/is-still-verified.ts
  packages/backend/src/apps/flickr/auth/verify-credentials.ts
  packages/backend/src/apps/flickr/authentication.ts
  packages/backend/src/apps/flickr/common/add-auth-header.ts
  packages/backend/src/apps/flickr/common/oauth-client.ts
  packages/backend/src/apps/flickr/data.ts
  packages/backend/src/apps/flickr/data/list-albums.ts
  packages/backend/src/apps/flickr/index.d.ts
  packages/backend/src/apps/flickr/index.ts
  packages/backend/src/apps/flickr/info.json
  packages/backend/src/apps/flickr/triggers.ts
  packages/backend/src/apps/flickr/triggers/new-album.ts
  packages/backend/src/apps/flickr/triggers/new-favorite-photo.ts
  packages/backend/src/apps/flickr/triggers/new-photo-in-album.ts
  packages/backend/src/apps/flickr/triggers/new-photo.ts
  packages/backend/src/models/app.ts
  packages/backend/tsconfig.json
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/connections/flickr.md
Labels: enhancement

#637 feat(flickr): add new photos trigger
  packages/backend/src/apps/flickr/triggers/new-photos/index.ts
  packages/backend/src/apps/flickr/triggers/new-photos/new-photos.ts
  packages/backend/src/apps/github/triggers/new-watchers/new-watchers.ts
Labels: enhancement

#648 fix: cover _ in variable regex
  packages/backend/src/helpers/compute-parameters.ts
Labels: bug

#649 feat(flickr): add new albums trigger
  packages/backend/src/apps/flickr/triggers/new-albums/index.ts
  packages/backend/src/apps/flickr/triggers/new-albums/new-albums.ts
Labels: enhancement

#653 feat(rss): add new items in feed trigger
  packages/backend/package.json
  packages/backend/src/apps/rss/assets/favicon.svg
  packages/backend/src/apps/rss/index.d.ts
  packages/backend/src/apps/rss/index.ts
  packages/backend/src/apps/rss/triggers/new-items-in-feed/index.ts
  packages/backend/src/apps/rss/triggers/new-items-in-feed/new-items-in-feed.ts
  packages/backend/src/graphql/schema.graphql
  packages/docs/pages/connections/rss.md
  packages/web/src/components/AddAppConnection/index.tsx
  yarn.lock
Labels: enhancement

#658 feat(discord): add auth
  packages/backend/src/apps/discord/actions/index.ts
  packages/backend/src/apps/discord/assets/favicon.svg
  packages/backend/src/apps/discord/auth/create-auth-data.ts
  packages/backend/src/apps/discord/auth/index.ts
  packages/backend/src/apps/discord/auth/is-still-verified.ts
  packages/backend/src/apps/discord/auth/verify-credentials.ts
  packages/backend/src/apps/discord/common/add-auth-header.ts
  packages/backend/src/apps/discord/common/get-current-user.ts
  packages/backend/src/apps/discord/common/scopes.ts
  packages/backend/src/apps/discord/index.d.ts
  packages/backend/src/apps/discord/index.ts
  packages/backend/src/apps/discord/triggers/index.ts
  packages/backend/src/helpers/global-variable.ts
Labels: enhancement

#666 feat(discord): add send message to channel action
  packages/backend/src/apps/discord/actions/index.ts
  packages/backend/src/apps/discord/actions/send-message-to-channel/index.ts
  packages/backend/src/apps/discord/auth/create-auth-data.ts
  packages/backend/src/apps/discord/auth/index.ts
  packages/backend/src/apps/discord/auth/verify-credentials.ts
  packages/backend/src/apps/discord/common/add-auth-header.ts
  packages/backend/src/apps/discord/common/scopes.ts
  packages/backend/src/apps/discord/data/index.ts
  packages/backend/src/apps/discord/data/list-channels/index.ts
  packages/backend/src/apps/discord/index.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/connections/discord.md
  packages/web/src/components/AddAppConnection/index.tsx
  packages/web/src/helpers/authenticationSteps.ts
Labels: enhancement
