Repository automatisch/automatisch, pull requests merged in 2022-12, with the labels that each got.

#770 Add telegram bot support with sending message
  packages/backend/src/apps/telegram-bot/actions/index.ts
  packages/backend/src/apps/telegram-bot/actions/send-message/index.ts
  packages/backend/src/apps/telegram-bot/assets/favicon.svg
  packages/backend/src/apps/telegram-bot/auth/index.ts
  packages/backend/src/apps/telegram-bot/auth/is-still-verified.ts
  packages/backend/src/apps/telegram-bot/auth/verify-credentials.ts
  packages/backend/src/apps/telegram-bot/common/add-auth-header.ts
  packages/backend/src/apps/telegram-bot/index.d.ts
  packages/backend/src/apps/telegram-bot/index.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/telegram-bot/actions.md
  packages/docs/pages/apps/telegram-bot/connection.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/telegram-bot.svg
  packages/web/src/components/AppRow/index.tsx
Labels: enhancement

#776 feat(FlowSubstep): show autocomplete option value
  packages/web/src/components/ControlledAutocomplete/index.tsx
  packages/web/src/components/FlowSubstep/index.tsx
  packages/web/src/components/InputCreator/index.tsx
Labels: enhancement

#775 fix(ControlledAutocomplete): use option value as option key
  packages/web/src/components/ControlledAutocomplete/index.tsx
  packages/web/src/components/Editor/index.tsx
  packages/web/src/components/FlowSubstep/index.tsx
  packages/web/src/components/InputCreator/index.tsx
Labels: bug

#779 docs(available-apps): fix telegram link
  packages/docs/pages/guide/available-apps.md
Labels: documentation

#778 feat(worker): log when workers are ready
  packages/backend/src/config/redis.ts
  packages/backend/src/helpers/check-worker-readiness.ts
  packages/backend/src/worker.ts
Labels: enhancement

#780 Add webhook integration
  packages/backend/src/apps/webhook/assets/favicon.svg
  packages/backend/src/apps/webhook/index.d.ts
  packages/backend/src/apps/webhook/index.ts
  packages/backend/src/apps/webhook/triggers/catch-raw-webhook/index.ts
  packages/backend/src/apps/webhook/triggers/index.ts
  packages/backend/src/controllers/webhooks/handler.ts
  packages/backend/src/graphql/mutations/update-flow-status.ts
  packages/backend/src/graphql/schema.graphql
  packages/backend/src/helpers/global-variable.ts
  packages/backend/src/models/step.ts
  packages/backend/src/routes/webhooks.ts
  packages/types/index.d.ts
  packages/web/src/components/AddAppConnection/index.tsx
  packages/web/src/components/TestSubstep/index.tsx
  packages/web/src/components/WebhookUrlInfo/index.tsx
  packages/web/src/components/WebhookUrlInfo/style.ts
  packages/web/src/config/urls.ts
  packages/web/src/graphql/queries/get-flow.ts
  packages/web/src/helpers/translation-values.tsx
  packages/web/src/locales/en.json
Labels: enhancement

#783 feat(ntfy): describe user & psswd in auth dialog
  packages/backend/src/apps/ntfy/auth/index.ts
Labels: enhancement

#786 Release v0.3.0
  docker/Dockerfile
  docker/Dockerfile.compose
  lerna.json
  packages/backend/package.json
  packages/cli/package.json
  packages/docs/package.json
  packages/e2e-tests/package.json
  packages/types/package.json
  packages/web/package.json
Labels: release

#787 fix(webhook): correct internal ID for GET requests
  packages/backend/src/controllers/webhooks/handler.ts
  packages/web/src/components/TestSubstep/index.tsx
  packages/web/src/components/WebhookUrlInfo/index.tsx
Labels: bug

#789 feat: show "instant" chip for webhook triggers
  packages/backend/src/graphql/schema.graphql
  packages/web/src/components/ChooseAppAndEventSubstep/index.tsx
  packages/web/src/graphql/queries/get-app.ts
  packages/web/src/graphql/queries/get-apps.ts
  packages/web/src/locales/en.json
Labels: enhancement

#794 fix: make type optional for webhook check
  packages/web/src/components/ChooseAppAndEventSubstep/index.tsx
Labels: bug

#793 feat: take search bar out of scroll in add app connection
  packages/web/src/components/AddNewAppConnection/index.tsx
Labels: enhancement

#806 Add flowers software
  packages/backend/src/apps/flowers-software/assets/favicon.svg
  packages/backend/src/apps/flowers-software/auth/index.ts
  packages/backend/src/apps/flowers-software/auth/is-still-verified.ts
  packages/backend/src/apps/flowers-software/auth/verify-credentials.ts
  packages/backend/src/apps/flowers-software/common/add-auth-header.ts
  packages/backend/src/apps/flowers-software/common/get-webhooks.ts
  packages/backend/src/apps/flowers-software/common/webhook-filters.ts
  packages/backend/src/apps/flowers-software/index.d.ts
  packages/backend/src/apps/flowers-software/index.ts
  packages/backend/src/apps/flowers-software/triggers/index.ts
  packages/backend/src/apps/flowers-software/triggers/new-activity/index.ts
  packages/backend/src/db/migrations/20221214184855_add_remote_webhook_id_in_flow.ts
  packages/backend/src/helpers/global-variable.ts
  packages/backend/src/models/flow.ts
  packages/types/index.d.ts
  packages/web/src/components/AddAppConnection/index.tsx
Labels: enhancement

#818 feat(webhooks): handle form-data and text/plain reqs
  packages/backend/package.json
  packages/backend/src/app.ts
  packages/backend/src/routes/webhooks.ts
  yarn.lock
Labels: enhancement
