Repository automatisch/automatisch, pull requests merged in 2023-08, with the labels that each got.

#1183 feat(notion): add create page action
  packages/backend/src/apps/notion/actions/create-page/index.ts
  packages/backend/src/apps/notion/actions/index.ts
  packages/backend/src/apps/notion/dynamic-data/index.ts
  packages/backend/src/apps/notion/dynamic-data/list-parent-pages/index.ts
  packages/docs/pages/apps/notion/actions.md
Labels: enhancement

#1184 feat(notion): add find database item action
  packages/backend/src/apps/notion/actions/create-database-item/index.ts
  packages/backend/src/apps/notion/actions/find-database-item/index.ts
  packages/backend/src/apps/notion/actions/index.ts
  packages/docs/pages/apps/notion/actions.md
Labels: enhancement

#1189 Release v0.8.0
  docker/Dockerfile
  docker/Dockerfile.compose
  lerna.json
  packages/backend/package.json
  packages/cli/package.json
  packages/docs/package.json
  packages/e2e-tests/package.json
  packages/types/package.json
  packages/web/package.json
Labels: release

#1192 fix: add fallback for api url
  packages/web/src/config/app.ts
Labels: bug

#1193 fix: clone base db queries
  packages/backend/src/graphql/queries/get-app.ts
  packages/backend/src/graphql/queries/get-connected-apps.ts
  packages/backend/src/graphql/queries/get-dynamic-data.ts
  packages/backend/src/graphql/queries/get-dynamic-fields.ts
  packages/backend/src/graphql/queries/get-execution-steps.ts
  packages/backend/src/graphql/queries/get-execution.ts
  packages/backend/src/graphql/queries/get-executions.ts
  packages/backend/src/graphql/queries/get-flow.ts
  packages/backend/src/graphql/queries/get-flows.ts
  packages/backend/src/graphql/queries/get-step-with-test-executions.ts
  packages/backend/src/graphql/queries/test-connection.ts
Labels: bug

#1160 feat(wordpress): add auth and new post trigger
  packages/backend/src/apps/wordpress/assets/favicon.svg
  packages/backend/src/apps/wordpress/auth/generate-auth-url.ts
  packages/backend/src/apps/wordpress/auth/index.ts
  packages/backend/src/apps/wordpress/auth/is-still-verified.ts
  packages/backend/src/apps/wordpress/auth/verify-credentials.ts
  packages/backend/src/apps/wordpress/common/add-auth-header.ts
  packages/backend/src/apps/wordpress/common/get-instance-url.ts
  packages/backend/src/apps/wordpress/common/set-base-url.ts
  packages/backend/src/apps/wordpress/dynamic-data/index.ts
  packages/backend/src/apps/wordpress/dynamic-data/list-statuses/index.ts
  packages/backend/src/apps/wordpress/index.d.ts
  packages/backend/src/apps/wordpress/index.ts
  packages/backend/src/apps/wordpress/triggers/index.ts
  packages/backend/src/apps/wordpress/triggers/new-post/index.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/wordpress/connection.md
  packages/docs/pages/apps/wordpress/triggers.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/wordpress.svg
Labels: enhancement

#1205 feat: introduce dynamic configuration
  packages/backend/src/db/migrations/20230810124730_create_config.ts
  packages/backend/src/db/migrations/20230810134714_seed_update_config_permissions_to_admin.ts
  packages/backend/src/graphql/mutation-resolvers.ts
  packages/backend/src/graphql/mutations/update-config.ts
  packages/backend/src/graphql/queries/get-config.ts
  packages/backend/src/graphql/query-resolvers.ts
  packages/backend/src/graphql/schema.graphql
  packages/backend/src/helpers/authentication.ts
  packages/backend/src/models/config.ts
  packages/web/src/components/AppBar/index.tsx
  packages/web/src/components/CustomLogo/index.ee.tsx
  packages/web/src/components/Logo/index.tsx
  packages/web/src/components/Logo/style.ts
  packages/web/src/components/PublicLayout/index.tsx
  packages/web/src/components/ThemeProvider/index.tsx
  packages/web/src/graphql/mutations/update-config.ts
  packages/web/src/graphql/queries/get-config.ts
  packages/web/src/hooks/useConfig.ts
Labels: enhancement

#1209 fix(get-apps): fetch additionalFields for triggers
  packages/web/src/graphql/queries/get-apps.ts
Labels: bug

#1211 chore: move config behind checks
  packages/backend/src/graphql/mutation-resolvers.ts
  packages/backend/src/graphql/mutations/update-config.ee.ts
  packages/backend/src/graphql/queries/get-config.ee.ts
  packages/backend/src/graphql/query-resolvers.ts
  packages/backend/src/models/user.ts
  packages/web/src/graphql/mutations/update-config.ee.ts
  packages/web/src/graphql/queries/get-config.ee.ts
  packages/web/src/hooks/useConfig.ts
Labels: enhancement

#1213 feat: introduce app configs with shared auth clients
  packages/backend/src/apps/gitlab/auth/verify-credentials.ts
  packages/backend/src/db/migrations/20230812132005_create_app_configs.ts
  packages/backend/src/db/migrations/20230813172729_create_app_auth_clients.ts
  packages/backend/src/db/migrations/20230815161102_add_app_auth_client_id_in_connections.ts
  packages/backend/src/db/migrations/20230816121044_seed_update_app_permissions_to_admin.ts
  packages/backend/src/graphql/mutation-resolvers.ts
  packages/backend/src/graphql/mutations/create-app-auth-client.ee.ts
  packages/backend/src/graphql/mutations/create-app-config.ee.ts
  packages/backend/src/graphql/mutations/create-connection.ts
  packages/backend/src/graphql/mutations/delete-app-auth-client.ee.ts
  packages/backend/src/graphql/mutations/update-app-auth-client.ee.ts
  packages/backend/src/graphql/mutations/update-app-config.ee.ts
  packages/backend/src/graphql/mutations/update-connection.ts
  packages/backend/src/graphql/queries/get-app-auth-client.ee.ts
  packages/backend/src/graphql/queries/get-app-auth-clients.ee.ts
  packages/backend/src/graphql/queries/get-app-config.ee.ts
  packages/backend/src/graphql/queries/get-app.ts
  packages/backend/src/graphql/query-resolvers.ts
  packages/backend/src/graphql/schema.graphql
  packages/backend/src/helpers/add-authentication-steps.ts
  packages/backend/src/helpers/add-reconnection-steps.ts
  packages/backend/src/models/app-auth-client.ts
  packages/backend/src/models/app-config.ts
  packages/backend/src/models/connection.ts
  packages/backend/src/models/user.ts
  packages/types/index.d.ts
  packages/web/src/components/AddAppConnection/index.tsx
  packages/web/src/components/AppAuthClientsDialog/index.ee.tsx
  packages/web/src/components/AppConnectionContextMenu/index.tsx
  packages/web/src/components/AppConnectionRow/index.tsx
  packages/web/src/components/ChooseConnectionSubstep/index.tsx
  packages/web/src/components/SplitButton/index.tsx
  packages/web/src/config/urls.ts
  packages/web/src/graphql/queries/get-app-auth-client.ee.ts
  packages/web/src/graphql/queries/get-app-auth-clients.ee.ts
  packages/web/src/graphql/queries/get-app-config.ee.ts
  packages/web/src/graphql/queries/get-app-connections.ts
  packages/web/src/graphql/queries/get-app.ts
  packages/web/src/graphql/queries/get-apps.ts
  packages/web/src/helpers/authenticationSteps.ts
  packages/web/src/hooks/useApp.ts
  packages/web/src/hooks/useAppAuthClient.ee.ts
  packages/web/src/hooks/useAppAuthClients.ee.ts
  packages/web/src/hooks/useAppConfig.ee.ts
  packages/web/src/hooks/useAuthenticateApp.ee.ts
  packages/web/src/locales/en.json
  packages/web/src/pages/Application/index.tsx
Labels: enhancement

#1220 chore: make e2e tests manually triggerable
  .github/workflows/playwright.yml
Labels: enhancement

#1221 chore: configure login env. vars. in e2e test workflow
  .github/workflows/playwright.yml
Labels: bug

#1219 feat(user-list): add pagination
  packages/backend/src/graphql/queries/get-users.ts
  packages/backend/src/graphql/schema.graphql
  packages/backend/src/helpers/pagination.ts
  packages/web/src/components/UserList/TablePaginationActions/index.tsx
  packages/web/src/components/UserList/index.tsx
  packages/web/src/components/UserList/style.ts
  packages/web/src/graphql/queries/get-users.ts
  packages/web/src/hooks/useUsers.ts
Labels: enhancement

#1222 feat: create clear button for ControlledCustomAutocomplete
  packages/web/src/components/ControlledCustomAutocomplete/CustomOptions.tsx
  packages/web/src/components/ControlledCustomAutocomplete/index.tsx
  packages/web/src/components/ControlledCustomAutocomplete/style.ts
  packages/web/src/components/Slate/Element.tsx
  packages/web/src/components/Slate/utils.ts
Labels: enhancement

#1229 feat: add getSamlAuthProviderRoleMappings query
  packages/backend/src/graphql/queries/get-saml-auth-provider-role-mappings.ee.ts
  packages/backend/src/graphql/query-resolvers.ts
  packages/backend/src/graphql/schema.graphql
Labels: enhancement

#1233 feat: enhance step variable coverage
  packages/backend/src/graphql/mutations/execute-flow.ts
  packages/backend/src/graphql/mutations/update-flow-status.ts
  packages/backend/src/graphql/mutations/update-step.ts
  packages/backend/src/helpers/compute-parameters.ts
Labels: enhancement

#1246 Release v0.9.0
  docker/Dockerfile
  docker/Dockerfile.compose
  lerna.json
  packages/backend/package.json
  packages/cli/package.json
  packages/docs/package.json
  packages/e2e-tests/package.json
  packages/types/package.json
  packages/web/package.json
Labels: release

#1248 Release v0.9.1
  docker/Dockerfile
  docker/Dockerfile.compose
  lerna.json
  packages/backend/package.json
  packages/cli/package.json
  packages/docs/package.json
  packages/e2e-tests/package.json
  packages/types/package.json
  packages/web/package.json
Labels: release

#1250 Release v0.9.2
  docker/Dockerfile
  docker/Dockerfile.compose
  lerna.json
  packages/backend/package.json
  packages/cli/package.json
  packages/docs/package.json
  packages/e2e-tests/package.json
  packages/types/package.json
  packages/web/package.json
Labels: release

#1253 refactor: fetch notifications over graphql query
  .devcontainer/boot.sh
  .vscode/settings.json
  packages/backend/src/graphql/queries/get-notifications.ts
  packages/backend/src/graphql/query-resolvers.ts
  packages/backend/src/graphql/schema.graphql
  packages/backend/src/helpers/authentication.ts
  packages/types/index.d.ts
  packages/web/.env-example
  packages/web/src/config/app.ts
  packages/web/src/graphql/queries/get-notifications.ts
  packages/web/src/hooks/useNotifications.ts
  packages/web/src/hooks/useVersion.ts
  packages/web/src/pages/Notifications/index.tsx
Labels: enhancement
