Repository automatisch/automatisch, pull requests merged in 2023-03, with the labels that each got.

#964 feat: introduce full name column to user model
  packages/backend/bin/database/utils.ts
  packages/backend/src/db/migrations/20230301211751_add_full_name_to_users.ts
  packages/backend/src/graphql/schema.graphql
  packages/backend/src/models/user.ts
  packages/web/src/graphql/queries/get-current-user.ts
Labels: enhancement

#965 Add deleteUser mutation
  packages/backend/src/graphql/mutation-resolvers.ts
  packages/backend/src/graphql/mutations/delete-user.ee.ts
  packages/backend/src/graphql/schema.graphql
  packages/backend/src/helpers/create-bull-board-handler.ts
  packages/backend/src/queues/delete-user.ee.ts
  packages/backend/src/worker.ts
  packages/backend/src/workers/delete-user.ee.ts
Labels: enhancement

#966 feat: show delete user functionality
  packages/backend/src/graphql/mutations/delete-user.ee.ts
  packages/backend/src/graphql/schema.graphql
  packages/web/src/components/DeleteAccountDialog/index.ee.tsx
  packages/web/src/graphql/mutations/delete-user.ee.ts
  packages/web/src/locales/en.json
  packages/web/src/pages/ProfileSettings/index.tsx
Labels: enhancement

#970 Add signup
  packages/backend/src/graphql/mutations/create-user.ee.ts
  packages/backend/src/graphql/schema.graphql
  packages/web/src/components/LoginForm/index.tsx
  packages/web/src/components/SignUpForm/index.ee.tsx
  packages/web/src/config/urls.ts
  packages/web/src/graphql/mutations/create-user.ee.ts
  packages/web/src/locales/en.json
  packages/web/src/pages/ProfileSettings/index.tsx
  packages/web/src/pages/SignUp/index.ee.tsx
  packages/web/src/routes.tsx
Labels: enhancement

#968 feat: add forgot password featureset
  packages/backend/src/graphql/mutations/forgot-password.ee.ts
  packages/backend/src/graphql/mutations/reset-password.ee.ts
  packages/backend/src/helpers/authentication.ts
  packages/backend/src/views/emails/reset-password-instructions.ee.hbs
  packages/backend/src/workers/email.ts
  packages/web/src/components/DeleteAccountDialog/index.ee.tsx
  packages/web/src/components/ForgotPasswordForm/index.ee.tsx
  packages/web/src/components/LoginForm/index.tsx
  packages/web/src/components/ResetPasswordForm/index.ee.tsx
  packages/web/src/components/SignUpForm/index.ee.tsx
  packages/web/src/config/urls.ts
  packages/web/src/graphql/mutations/forgot-password.ee.ts
  packages/web/src/graphql/mutations/reset-password.ee.ts
  packages/web/src/locales/en.json
  packages/web/src/pages/ForgotPassword/index.ee.tsx
  packages/web/src/pages/ResetPassword/index.ee.tsx
  packages/web/src/routes.tsx
Labels: enhancement

#978 feat: show payment portal information
  packages/web/src/components/PaymentInformation/index.ee.tsx
  packages/web/src/contexts/AutomatischInfo.tsx
  packages/web/src/graphql/queries/get-payment-portal-url.ee.ts
  packages/web/src/helpers/translation-values.tsx
  packages/web/src/hooks/usePaymentPortalUrl.ee.ts
  packages/web/src/locales/en.json
  packages/web/src/pages/BillingAndUsageSettings/index.ee.tsx
Labels: enhancement

#977 feat: add empty billing and usage page
  packages/backend/src/graphql/schema.graphql
  packages/web/src/components/PaymentInformation/index.ee.tsx
  packages/web/src/components/SettingsLayout/index.tsx
  packages/web/src/config/urls.ts
  packages/web/src/contexts/AutomatischInfo.tsx
  packages/web/src/graphql/queries/get-automatisch-info.ts
  packages/web/src/graphql/queries/get-payment-portal-url.ee.ts
  packages/web/src/helpers/translation-values.tsx
  packages/web/src/hooks/useAutomatischInfo.ts
  packages/web/src/hooks/useCloud.ts
  packages/web/src/hooks/usePaymentPortalUrl.ee.ts
  packages/web/src/index.tsx
  packages/web/src/locales/en.json
  packages/web/src/pages/BillingAndUsageSettings/index.ee.tsx
  packages/web/src/pages/ProfileSettings/index.tsx
  packages/web/src/settingsRoutes.tsx
Labels: enhancement

#979 feat: show usage data
  packages/web/src/components/UsageDataInformation/index.ee.tsx
  packages/web/src/graphql/queries/get-usage-data.ee.ts
  packages/web/src/hooks/useUsageData.ee.ts
  packages/web/src/pages/BillingAndUsageSettings/index.ee.tsx
Labels: enhancement

#985 feat: show current plan name in usage information
  packages/backend/src/graphql/queries/get-usage-data.ee.ts
  packages/backend/src/graphql/schema.graphql
  packages/web/src/components/UsageDataInformation/index.ee.tsx
  packages/web/src/graphql/queries/get-usage-data.ee.ts
  packages/web/src/hooks/useUsageData.ee.ts
Labels: enhancement

#984 feat: add chatwoot
  packages/types/index.d.ts
  packages/web/src/components/LiveChat/Chatwoot.ee.tsx
  packages/web/src/components/LiveChat/index.ee.tsx
  packages/web/src/config/app.ts
  packages/web/src/graphql/link.ts
  packages/web/src/index.tsx
Labels: enhancement

#986 feat: increase consumed task count upon tasks
  packages/backend/src/models/execution-step.ts
  packages/backend/src/models/execution.ts
  packages/backend/src/models/flow.ts
  packages/backend/src/models/usage-data.ee.ts
Labels: enhancement

#990 feat: disable non-cloud features
  packages/web/src/components/LoginForm/index.tsx
  packages/web/src/hooks/useCloud.ts
  packages/web/src/index.tsx
  packages/web/src/pages/ForgotPassword/index.ee.tsx
  packages/web/src/pages/ResetPassword/index.ee.tsx
  packages/web/src/pages/SignUp/index.ee.tsx
Labels: enhancement

#988 feat: show usage alert as of threshold
  packages/web/src/components/AppBar/index.tsx
  packages/web/src/components/ConditionalIconButton/index.tsx
  packages/web/src/components/Drawer/index.tsx
  packages/web/src/components/Layout/index.tsx
  packages/web/src/components/LiveChat/Chatwoot.ee.tsx
  packages/web/src/components/SettingsLayout/index.tsx
  packages/web/src/components/UsageAlert/index.ee.tsx
  packages/web/src/config/app.ts
  packages/web/src/hooks/useUsageAlert.ee.ts
  packages/web/src/locales/en.json
  packages/web/src/pages/Application/index.tsx
  packages/web/src/styles/theme.ts
Labels: enhancement

#989 feat: skip processing tasks over task quota
  packages/backend/src/controllers/webhooks/handler.ts
  packages/backend/src/models/flow.ts
  packages/backend/src/models/usage-data.ee.ts
  packages/backend/src/routes/webhooks.ts
  packages/backend/src/services/action.ts
  packages/backend/src/services/flow.ts
Labels: enhancement

#991 feat: don't interrupt execution due to quota
  packages/backend/src/models/flow.ts
  packages/backend/src/services/action.ts
  packages/backend/src/services/flow.ts
  packages/backend/src/workers/flow.ts
Labels: enhancement

#994 feat: introduce Sentry
  packages/backend/package.json
  packages/backend/src/app.ts
  packages/backend/src/config/app.ts
  packages/backend/src/controllers/stripe/webhooks.ee.ts
  packages/backend/src/errors/base.ts
  packages/backend/src/errors/quote-exceeded.ts
  packages/backend/src/helpers/error-handler.ts
  packages/backend/src/helpers/graphql-instance.ts
  packages/backend/src/helpers/sentry.ee.ts
  packages/backend/src/models/flow.ts
  packages/backend/src/routes/webhooks.ts
  packages/backend/src/worker.ts
  packages/backend/src/workers/action.ts
  packages/backend/src/workers/delete-user.ee.ts
  packages/backend/src/workers/email.ts
  packages/backend/src/workers/flow.ts
  packages/backend/src/workers/trigger.ts
  packages/types/index.d.ts
  yarn.lock
Labels: enhancement

#995 feat: add validation checks in mutations
  packages/backend/src/graphql/mutations/create-flow.ts
  packages/backend/src/graphql/mutations/create-step.ts
  packages/backend/src/graphql/mutations/execute-flow.ts
  packages/backend/src/graphql/mutations/update-step.ts
  packages/backend/src/helpers/get-app.ts
  packages/backend/src/models/app.ts
Labels: enhancement

#998 fix: show progress as of sign-up in SignUpForm
  packages/web/src/components/SignUpForm/index.ee.tsx
Labels: bug

#993 feat: add searchable json viewer component
  packages/web/src/components/ExecutionStep/index.tsx
  packages/web/src/components/SearchableJSONViewer/index.tsx
  packages/web/src/locales/en.json
Labels: enhancement

#1006 feat: add checkout process
  packages/backend/src/config/app.ts
  packages/backend/src/graphql/schema.graphql
  packages/web/src/components/UpgradeFreeTrial/index.ee.tsx
  packages/web/src/contexts/Paddle.ee.tsx
  packages/web/src/graphql/queries/get-paddle-info.ee.ts
  packages/web/src/hooks/usePaddle.ee.ts
  packages/web/src/hooks/usePaddleInfo.ee.ts
  packages/web/src/index.tsx
Labels: enhancement

#1013 feat(google-drive): add new files trigger
  packages/backend/src/apps/google-drive/assets/favicon.svg
  packages/backend/src/apps/google-drive/auth/generate-auth-url.ts
  packages/backend/src/apps/google-drive/auth/index.ts
  packages/backend/src/apps/google-drive/auth/is-still-verified.ts
  packages/backend/src/apps/google-drive/auth/refresh-token.ts
  packages/backend/src/apps/google-drive/auth/verify-credentials.ts
  packages/backend/src/apps/google-drive/common/add-auth-header.ts
  packages/backend/src/apps/google-drive/common/auth-scope.ts
  packages/backend/src/apps/google-drive/common/get-current-user.ts
  packages/backend/src/apps/google-drive/index.d.ts
  packages/backend/src/apps/google-drive/index.ts
  packages/backend/src/apps/google-drive/triggers/index.ts
  packages/backend/src/apps/google-drive/triggers/new-files/index.ts
  packages/backend/src/apps/google-drive/triggers/new-files/new-files.ts
Labels: enhancement

#1025 feat: use actual data in billing and usage
  .devcontainer/boot.sh
  .devcontainer/docker-compose.yml
  packages/backend/src/graphql/queries/get-billing-and-usage.ee.ts
  packages/types/index.d.ts
  packages/web/src/components/AppBar/index.tsx
  packages/web/src/components/LoginForm/index.tsx
  packages/web/src/components/UsageDataInformation/index.ee.tsx
  packages/web/src/graphql/queries/get-billing-and-usage.ee.ts
  packages/web/src/hooks/useBillingAndUsageData.ee.ts
  packages/web/src/locales/en.json
  packages/web/src/pages/BillingAndUsageSettings/index.ee.tsx
Labels: enhancement

#1026 feat: add invoices on billing and usage page
  packages/types/index.d.ts
  packages/web/src/components/Invoices/index.ee.tsx
  packages/web/src/graphql/queries/get-invoices.ee.ts
  packages/web/src/hooks/useBillingAndUsageData.ee.ts
  packages/web/src/hooks/useInvoices.ee.ts
  packages/web/src/locales/en.json
  packages/web/src/pages/BillingAndUsageSettings/index.ee.tsx
Labels: enhancement

#1028 feat(google-drive): add new files in folder trigger
  packages/backend/src/apps/google-drive/dynamic-data/index.ts
  packages/backend/src/apps/google-drive/dynamic-data/list-folders/index.ts
  packages/backend/src/apps/google-drive/index.ts
  packages/backend/src/apps/google-drive/triggers/index.ts
  packages/backend/src/apps/google-drive/triggers/new-files-in-folder/index.ts
  packages/backend/src/apps/google-drive/triggers/new-files-in-folder/new-files-in-folder.ts
Labels: enhancement

#1032 feat(google-drive): add new folders trigger
  packages/backend/src/apps/google-drive/triggers/index.ts
  packages/backend/src/apps/google-drive/triggers/new-folders/index.ts
  packages/backend/src/apps/google-drive/triggers/new-folders/new-folders.ts
Labels: enhancement

#1015 docs: add google forms connection and triggers
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/google-forms/connection.md
  packages/docs/pages/apps/google-forms/triggers.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/google-forms.svg
Labels: documentation

#1016 docs: add google drive connection and triggers
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/google-drive/connection.md
  packages/docs/pages/apps/google-drive/triggers.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/google-drive.svg
Labels: documentation

#1034 docs(google-drive): add trigger for new folders
  packages/docs/pages/apps/google-drive/triggers.md
Labels: documentation
