Repository automatisch/automatisch, pull requests merged in 2023-10, with the labels that each got.

#1317 feat(pipedrive): add create activity action
  packages/backend/src/apps/pipedrive/actions/create-activity/index.ts
  packages/backend/src/apps/pipedrive/actions/index.ts
  packages/backend/src/apps/pipedrive/dynamic-data/index.ts
  packages/backend/src/apps/pipedrive/dynamic-data/list-activity-types/index.ts
  packages/docs/pages/apps/pipedrive/actions.md
Labels: enhancement

#1321 feat(pipedrive): add create lead action
  packages/backend/src/apps/pipedrive/actions/create-lead/index.ts
  packages/backend/src/apps/pipedrive/actions/index.ts
  packages/backend/src/apps/pipedrive/dynamic-data/index.ts
  packages/backend/src/apps/pipedrive/dynamic-data/list-lead-labels/index.ts
  packages/docs/pages/apps/pipedrive/actions.md
  packages/web/src/components/DynamicField/index.tsx
  packages/web/src/components/InputCreator/index.tsx
Labels: enhancement, hacktoberfest-accepted

#1326 refactor: add useEnqueueSnackbar with data-test attr
  packages/web/package.json
  packages/web/src/components/ApolloProvider/index.tsx
  packages/web/src/components/AppConnectionRow/index.tsx
  packages/web/src/components/DeleteRoleButton/index.ee.tsx
  packages/web/src/components/DeleteUserButton/index.ee.tsx
  packages/web/src/components/FlowContextMenu/index.tsx
  packages/web/src/components/ResetPasswordForm/index.ee.tsx
  packages/web/src/hooks/useEnqueueSnackbar.ts
  packages/web/src/pages/Authentication/RoleMappings.tsx
  packages/web/src/pages/Authentication/SamlConfiguration.tsx
  packages/web/src/pages/CreateRole/index.ee.tsx
  packages/web/src/pages/CreateUser/index.tsx
  packages/web/src/pages/EditRole/index.ee.tsx
  packages/web/src/pages/EditUser/index.tsx
  packages/web/src/pages/ProfileSettings/index.tsx
  packages/web/src/pages/UserInterface/index.tsx
  yarn.lock
Labels: enhancement, hacktoberfest-accepted

#1309 chore: add mock license server
  .github/workflows/playwright.yml
  packages/e2e-tests/license-server-with-mock.js
  packages/e2e-tests/package.json
  packages/e2e-tests/playwright.config.js
  yarn.lock
Labels: enhancement

#1323 feat(invoice-ninja): add invoice ninja integration
  packages/backend/src/apps/invoice-ninja/assets/favicon.svg
  packages/backend/src/apps/invoice-ninja/auth/index.ts
  packages/backend/src/apps/invoice-ninja/auth/is-still-verified.ts
  packages/backend/src/apps/invoice-ninja/auth/verify-credentials.ts
  packages/backend/src/apps/invoice-ninja/common/add-auth-header.ts
  packages/backend/src/apps/invoice-ninja/index.d.ts
  packages/backend/src/apps/invoice-ninja/index.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/invoice-ninja/connection.md
  packages/docs/pages/public/favicons/invoice-ninja.svg
Labels: hacktoberfest-accepted, integration request

#1325 feat(invoice-ninja): add new clients trigger
  packages/backend/src/apps/invoice-ninja/index.ts
  packages/backend/src/apps/invoice-ninja/triggers/index.ts
  packages/backend/src/apps/invoice-ninja/triggers/new-clients/index.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/invoice-ninja/triggers.md
  packages/docs/pages/guide/available-apps.md
Labels: enhancement, hacktoberfest-accepted

#1327 feat(invoice-ninja): add new credits trigger
  packages/backend/src/apps/invoice-ninja/triggers/index.ts
  packages/backend/src/apps/invoice-ninja/triggers/new-credits/index.ts
  packages/docs/pages/apps/invoice-ninja/triggers.md
Labels: enhancement, hacktoberfest-accepted

#1328 feat(invoice-ninja): add new invoices trigger
  packages/backend/src/apps/invoice-ninja/triggers/index.ts
  packages/backend/src/apps/invoice-ninja/triggers/new-invoices/index.ts
  packages/docs/pages/apps/invoice-ninja/triggers.md
Labels: enhancement, hacktoberfest-accepted

#1329 feat(invoice-ninja): add new payments trigger
  packages/backend/src/apps/invoice-ninja/triggers/index.ts
  packages/backend/src/apps/invoice-ninja/triggers/new-payments/index.ts
  packages/docs/pages/apps/invoice-ninja/triggers.md
Labels: enhancement, hacktoberfest-accepted

#1330 feat(invoice-ninja): add new projects trigger
  packages/backend/src/apps/invoice-ninja/triggers/index.ts
  packages/backend/src/apps/invoice-ninja/triggers/new-projects/index.ts
  packages/docs/pages/apps/invoice-ninja/triggers.md
Labels: enhancement, hacktoberfest-accepted

#1331 feat(invoice-ninja): add new quotes trigger
  packages/backend/src/apps/invoice-ninja/triggers/index.ts
  packages/backend/src/apps/invoice-ninja/triggers/new-quotes/index.ts
  packages/docs/pages/apps/invoice-ninja/triggers.md
Labels: enhancement, hacktoberfest-accepted

#1334 feat(invoice-ninja): add create client action
  packages/backend/src/apps/invoice-ninja/actions/create-client/fields.ts
  packages/backend/src/apps/invoice-ninja/actions/create-client/index.ts
  packages/backend/src/apps/invoice-ninja/actions/index.ts
  packages/backend/src/apps/invoice-ninja/common/filter-provided-fields.ts
  packages/backend/src/apps/invoice-ninja/common/set-base-url.ts
  packages/backend/src/apps/invoice-ninja/index.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/invoice-ninja/actions.md
Labels: enhancement, hacktoberfest-accepted

#1338 feat(invoice-ninja): add create invoice action
  packages/backend/src/apps/invoice-ninja/actions/create-invoice/fields.ts
  packages/backend/src/apps/invoice-ninja/actions/create-invoice/index.ts
  packages/backend/src/apps/invoice-ninja/actions/index.ts
  packages/backend/src/apps/invoice-ninja/dynamic-data/index.ts
  packages/backend/src/apps/invoice-ninja/dynamic-data/list-clients/index.ts
  packages/backend/src/apps/invoice-ninja/index.ts
  packages/docs/pages/apps/invoice-ninja/actions.md
Labels: enhancement

#1357 fix(pipedrive/create-activity): correct its key
  packages/backend/src/apps/pipedrive/actions/create-activity/index.ts
Labels: bug, hacktoberfest-accepted

#1340 feat(invoice-ninja): add create product action
  packages/backend/src/apps/invoice-ninja/actions/create-product/fields.ts
  packages/backend/src/apps/invoice-ninja/actions/create-product/index.ts
  packages/backend/src/apps/invoice-ninja/actions/index.ts
  packages/docs/pages/apps/invoice-ninja/actions.md
Labels: enhancement

#1359 fix(pipedrive): check if there is no data in dynamic-data
  packages/backend/src/apps/pipedrive/dynamic-data/list-activity-types/index.ts
  packages/backend/src/apps/pipedrive/dynamic-data/list-currencies/index.ts
  packages/backend/src/apps/pipedrive/dynamic-data/list-deals/index.ts
  packages/backend/src/apps/pipedrive/dynamic-data/list-lead-labels/index.ts
  packages/backend/src/apps/pipedrive/dynamic-data/list-leads/index.ts
  packages/backend/src/apps/pipedrive/dynamic-data/list-organizations/index.ts
  packages/backend/src/apps/pipedrive/dynamic-data/list-persons/index.ts
  packages/backend/src/apps/pipedrive/dynamic-data/list-users/index.ts
Labels: bug

#1351 feat(youtube): add youtube integration
  packages/backend/src/apps/youtube/assets/favicon.svg
  packages/backend/src/apps/youtube/auth/generate-auth-url.ts
  packages/backend/src/apps/youtube/auth/index.ts
  packages/backend/src/apps/youtube/auth/is-still-verified.ts
  packages/backend/src/apps/youtube/auth/refresh-token.ts
  packages/backend/src/apps/youtube/auth/verify-credentials.ts
  packages/backend/src/apps/youtube/common/add-auth-header.ts
  packages/backend/src/apps/youtube/common/auth-scope.ts
  packages/backend/src/apps/youtube/common/get-current-user.ts
  packages/backend/src/apps/youtube/index.d.ts
  packages/backend/src/apps/youtube/index.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/youtube/connection.md
  packages/docs/pages/public/favicons/youtube.svg
Labels: integration request

#1353 feat(youtube): add new video in channel trigger
  packages/backend/src/apps/youtube/index.ts
  packages/backend/src/apps/youtube/triggers/index.ts
  packages/backend/src/apps/youtube/triggers/new-video-in-channel/index.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/youtube/triggers.md
  packages/docs/pages/guide/available-apps.md
Labels: enhancement

#1364 feat(pushover): add pushover integration
  packages/backend/src/apps/pushover/assets/favicon.svg
  packages/backend/src/apps/pushover/auth/index.ts
  packages/backend/src/apps/pushover/auth/is-still-verified.ts
  packages/backend/src/apps/pushover/auth/verify-credentials.ts
  packages/backend/src/apps/pushover/index.d.ts
  packages/backend/src/apps/pushover/index.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/pushover/connection.md
  packages/docs/pages/public/favicons/pushover.svg
Labels: integration request

#1378 feat: close snackbars upon click
  packages/web/src/hooks/useEnqueueSnackbar.ts
Labels: enhancement

#1373 feat(pushover): add send a pushover notification action
  packages/backend/src/apps/pushover/actions/index.ts
  packages/backend/src/apps/pushover/actions/send-a-pushover-notification/index.ts
  packages/backend/src/apps/pushover/dynamic-data/index.ts
  packages/backend/src/apps/pushover/dynamic-data/list-devices/index.ts
  packages/backend/src/apps/pushover/dynamic-data/list-sounds/index.ts
  packages/backend/src/apps/pushover/index.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/pushover/actions.md
  packages/docs/pages/guide/available-apps.md
Labels: enhancement

#1380 feat(trello): add trello integration
  packages/backend/src/apps/trello/assets/favicon.svg
  packages/backend/src/apps/trello/auth/generate-auth-url.ts
  packages/backend/src/apps/trello/auth/index.ts
  packages/backend/src/apps/trello/auth/is-still-verified.ts
  packages/backend/src/apps/trello/auth/verify-credentials.ts
  packages/backend/src/apps/trello/common/add-auth-header.ts
  packages/backend/src/apps/trello/common/auth-scope.ts
  packages/backend/src/apps/trello/common/get-current-user.ts
  packages/backend/src/apps/trello/index.d.ts
  packages/backend/src/apps/trello/index.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/trello/connection.md
  packages/docs/pages/public/favicons/trello.svg
  packages/web/src/components/AddAppConnection/index.tsx
  packages/web/src/helpers/authenticationSteps.ts
Labels: integration request

#1382 fix: Guard lowercase email for delete user operation
  packages/backend/src/models/user.ts
Labels: bug

#1385 feat(zendesk): add zendesk integration
  packages/backend/src/apps/zendesk/assets/favicon.svg
  packages/backend/src/apps/zendesk/auth/generate-auth-url.ts
  packages/backend/src/apps/zendesk/auth/index.ts
  packages/backend/src/apps/zendesk/auth/is-still-verified.ts
  packages/backend/src/apps/zendesk/auth/verify-credentials.ts
  packages/backend/src/apps/zendesk/common/add-auth-headers.ts
  packages/backend/src/apps/zendesk/common/auth-scope.ts
  packages/backend/src/apps/zendesk/common/get-current-user.ts
  packages/backend/src/apps/zendesk/index.d.ts
  packages/backend/src/apps/zendesk/index.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/zendesk/connection.md
  packages/docs/pages/public/favicons/zendesk.svg
Labels: integration request

#1388 fix(mutations/duplicate-flow): correct webhook path
  packages/backend/src/graphql/mutations/duplicate-flow.ts
Labels: bug

#1381 feat(queries/get-executions): add filter support
  packages/backend/src/db/migrations/20231025101146_add_flow_id_index_in_executions.ts
  packages/backend/src/db/migrations/20231025101923_add_updated_at_index_in_executions.ts
  packages/backend/src/graphql/queries/get-executions.test.ts
  packages/backend/src/graphql/queries/get-executions.ts
  packages/backend/src/graphql/schema.graphql
  packages/backend/test/factories/execution.ts
  packages/backend/test/factories/flow.ts
  packages/backend/test/factories/permission.ts
  packages/backend/test/factories/step.ts
  packages/types/index.d.ts
  packages/web/src/components/ExecutionHeader/index.tsx
  packages/web/src/components/ExecutionRow/index.tsx
  packages/web/src/components/FlowRow/index.tsx
  packages/web/src/locales/en.json
Labels: enhancement

#1393 feat: unregister webhook upon deleting flow
  packages/backend/src/graphql/mutations/delete-flow.ts
Labels: enhancement

#1391 feat(trello): add create card action
  packages/backend/src/apps/trello/actions/create-card/index.ts
  packages/backend/src/apps/trello/actions/index.ts
  packages/backend/src/apps/trello/common/add-auth-header.ts
  packages/backend/src/apps/trello/dynamic-data/index.ts
  packages/backend/src/apps/trello/dynamic-data/list-board-labels/index.ts
  packages/backend/src/apps/trello/dynamic-data/list-board-lists/index.ts
  packages/backend/src/apps/trello/dynamic-data/list-boards/index.ts
  packages/backend/src/apps/trello/dynamic-data/listMembers/index.ts
  packages/backend/src/apps/trello/index.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/trello/actions.md
  packages/docs/pages/guide/available-apps.md
Labels: enhancement

#1397 fix(mutations/delete-flow): cover incomplete trigger
  packages/backend/src/graphql/mutations/delete-flow.ts
Labels: bug
