Repository automatisch/automatisch, pull requests merged in 2023-04, with the labels that each got.

#1036 feat(profile): add capability to update user's full name
  packages/backend/src/graphql/mutations/update-user.ts
  packages/backend/src/graphql/schema.graphql
  packages/web/src/graphql/mutations/update-user.ts
  packages/web/src/graphql/queries/get-current-user.ts
  packages/web/src/locales/en.json
  packages/web/src/pages/ProfileSettings/index.tsx
Labels: enhancement

#1038 feat(google-sheets): add google sheets integration
  packages/backend/src/apps/google-sheets/assets/favicon.svg
  packages/backend/src/apps/google-sheets/auth/generate-auth-url.ts
  packages/backend/src/apps/google-sheets/auth/index.ts
  packages/backend/src/apps/google-sheets/auth/is-still-verified.ts
  packages/backend/src/apps/google-sheets/auth/refresh-token.ts
  packages/backend/src/apps/google-sheets/auth/verify-credentials.ts
  packages/backend/src/apps/google-sheets/common/add-auth-header.ts
  packages/backend/src/apps/google-sheets/common/auth-scope.ts
  packages/backend/src/apps/google-sheets/common/get-current-user.ts
  packages/backend/src/apps/google-sheets/dynamic-data/index.ts
  packages/backend/src/apps/google-sheets/dynamic-data/list-drives/index.ts
  packages/backend/src/apps/google-sheets/index.d.ts
  packages/backend/src/apps/google-sheets/index.ts
  packages/backend/src/apps/google-sheets/triggers/index.ts
  packages/backend/src/apps/google-sheets/triggers/new-spreadsheets/index.ts
  packages/backend/src/apps/google-sheets/triggers/new-spreadsheets/new-spreadsheets.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/google-sheets/connection.md
  packages/docs/pages/apps/google-sheets/triggers.md
  packages/docs/pages/public/favicons/google-sheets.svg
  packages/web/src/components/ControlledAutocomplete/index.tsx
Labels: enhancement

#1039 feat(google-drive): list shared drives for new files trigger
  packages/backend/src/apps/google-drive/dynamic-data/index.ts
  packages/backend/src/apps/google-drive/dynamic-data/list-drives/index.ts
  packages/backend/src/apps/google-drive/triggers/new-files/index.ts
  packages/backend/src/apps/google-drive/triggers/new-files/new-files.ts
Labels: enhancement

#1043 feat(google-drive): list shared drives for updated files trigger
  packages/backend/src/apps/google-drive/triggers/new-files/index.ts
  packages/backend/src/apps/google-drive/triggers/new-files/new-files.ts
  packages/backend/src/apps/google-drive/triggers/updated-files/index.ts
  packages/backend/src/apps/google-drive/triggers/updated-files/updated-files.ts
Labels: enhancement

#1042 feat(google-drive): list shared drives for new folders trigger
  packages/backend/src/apps/google-drive/triggers/new-folders/index.ts
  packages/backend/src/apps/google-drive/triggers/new-folders/new-folders.ts
Labels: enhancement

#1041 feat(google-drive): list shared drives for new files in folder trigger
  packages/backend/src/apps/google-drive/triggers/new-files-in-folder/index.ts
  packages/backend/src/apps/google-drive/triggers/new-files-in-folder/new-files-in-folder.ts
Labels: enhancement

#1037 feat(dropbox): add create folder and rename file actions
  packages/backend/src/apps/dropbox/actions/create-folder/index.ts
  packages/backend/src/apps/dropbox/actions/index.ts
  packages/backend/src/apps/dropbox/actions/rename-file/index.ts
  packages/backend/src/apps/dropbox/assets/favicon.svg
  packages/backend/src/apps/dropbox/auth/generate-auth-url.ts
  packages/backend/src/apps/dropbox/auth/index.ts
  packages/backend/src/apps/dropbox/auth/is-still-verified.ts
  packages/backend/src/apps/dropbox/auth/refresh-token.ts
  packages/backend/src/apps/dropbox/auth/verify-credentials.ts
  packages/backend/src/apps/dropbox/common/add-auth-header.ts
  packages/backend/src/apps/dropbox/common/get-current-account.ts
  packages/backend/src/apps/dropbox/common/scopes.ts
  packages/backend/src/apps/dropbox/index.d.ts
  packages/backend/src/apps/dropbox/index.ts
  packages/backend/src/apps/spotify/auth/refresh-token.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/dropbox/actions.md
  packages/docs/pages/apps/dropbox/connection.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/dropbox.svg
Labels: enhancement

#1044 feat(strava): add action to create totals and stats report
  packages/backend/src/apps/strava/actions/create-totals-and-stats-report/index.ts
  packages/backend/src/apps/strava/actions/index.ts
  packages/backend/src/apps/strava/assets/favicon.svg
  packages/backend/src/apps/strava/auth/generate-auth-url.ts
  packages/backend/src/apps/strava/auth/index.ts
  packages/backend/src/apps/strava/auth/is-still-verified.ts
  packages/backend/src/apps/strava/auth/refresh-token.ts
  packages/backend/src/apps/strava/auth/verify-credentials.ts
  packages/backend/src/apps/strava/common/add-auth-header.ts
  packages/backend/src/apps/strava/common/get-current-user.ts
  packages/backend/src/apps/strava/index.d.ts
  packages/backend/src/apps/strava/index.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/strava/actions.md
  packages/docs/pages/apps/strava/connection.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/strava.svg
Labels: enhancement

#1040 feat: add subscription update and cancel logics
  packages/backend/src/controllers/paddle/webhooks.ee.ts
  packages/backend/src/db/migrations/20230402183738_add_subscription_id_in_usage_data.ts
  packages/backend/src/graphql/queries/get-billing-and-usage.ee.ts
  packages/backend/src/graphql/queries/get-invoices.ee.ts
  packages/backend/src/graphql/queries/get-trial-status.ee.ts
  packages/backend/src/graphql/queries/get-usage-data.ee.ts
  packages/backend/src/graphql/query-resolvers.ts
  packages/backend/src/graphql/schema.graphql
  packages/backend/src/helpers/billing/paddle.ee.ts
  packages/backend/src/helpers/billing/plans.ee.ts
  packages/backend/src/helpers/billing/webhooks.ee.ts
  packages/backend/src/models/execution-step.ts
  packages/backend/src/models/flow.ts
  packages/backend/src/models/subscription.ee.ts
  packages/backend/src/models/usage-data.ee.ts
  packages/backend/src/models/user.ts
  packages/backend/src/routes/paddle.ee.ts
  packages/web/src/components/UsageDataInformation/index.ee.tsx
Labels: enhancement

#1049 feat: add TrialOverAlert on billing page
  packages/web/src/components/TrialOverAlert/index.ee.tsx
  packages/web/src/components/UsageDataInformation/index.ee.tsx
  packages/web/src/helpers/translation-values.tsx
  packages/web/src/hooks/useTrialStatus.ee.ts
  packages/web/src/locales/en.json
Labels: enhancement

#1048 feat: add trial status badge in appbar
  packages/backend/src/graphql/queries/get-trial-status.ee.ts
  packages/backend/src/models/user.ts
  packages/web/src/components/AppBar/index.tsx
  packages/web/src/components/TrialOverAlert/index.ee.tsx
  packages/web/src/components/TrialStatusBadge/index.ee.tsx
  packages/web/src/components/TrialStatusBadge/style.ee.tsx
  packages/web/src/components/UsageDataInformation/index.ee.tsx
  packages/web/src/graphql/queries/get-trial-status.ee.ts
  packages/web/src/helpers/translation-values.tsx
  packages/web/src/hooks/useBillingAndUsageData.ee.ts
  packages/web/src/hooks/useTrialStatus.ee.ts
  packages/web/src/locales/en.json
Labels: enhancement

#1051 feat: show completed checkout alert
  packages/backend/src/helpers/billing/webhooks.ee.ts
  packages/web/src/components/CheckoutCompletedAlert/index.ee.tsx
  packages/web/src/components/UsageDataInformation/index.ee.tsx
  packages/web/src/contexts/Paddle.ee.tsx
  packages/web/src/hooks/useBillingAndUsageData.ee.ts
  packages/web/src/hooks/useTrialStatus.ee.ts
  packages/web/src/locales/en.json
Labels: enhancement

#1050 feat(flow): add virtual paused/published/draft status
  packages/backend/src/config/app.ts
  packages/backend/src/controllers/webhooks/handler.ts
  packages/backend/src/graphql/schema.graphql
  packages/backend/src/models/flow.ts
  packages/backend/src/models/usage-data.ee.ts
  packages/backend/src/models/user.ts
  packages/backend/src/workers/flow.ts
  packages/types/index.d.ts
  packages/web/src/components/FlowRow/index.tsx
  packages/web/src/graphql/queries/get-flow.ts
  packages/web/src/graphql/queries/get-flows.ts
  packages/web/src/locales/en.json
Labels: enhancement

#1056 fix(user): correct withinLimits instance method
  packages/backend/src/models/user.ts
Labels: bug

#1060 Release v0.6.0
  docker/Dockerfile
  docker/Dockerfile.compose
  lerna.json
  packages/backend/package.json
  packages/cli/package.json
  packages/docs/package.json
  packages/e2e-tests/package.json
  packages/types/package.json
  packages/web/package.json
Labels: release
