Repository automatisch/automatisch, pull requests merged in 2023-11, with the labels that each got.

#1410 feat(notion/create-page): support variables in parentPageId field
  packages/backend/src/apps/notion/actions/create-page/index.ts
Labels: enhancement

#1401 feat(ghost): add ghost integration
  packages/backend/src/apps/ghost/assets/favicon.svg
  packages/backend/src/apps/ghost/auth/index.ts
  packages/backend/src/apps/ghost/auth/is-still-verified.ts
  packages/backend/src/apps/ghost/auth/verify-credentials.ts
  packages/backend/src/apps/ghost/common/add-auth-header.ts
  packages/backend/src/apps/ghost/common/set-base-url.ts
  packages/backend/src/apps/ghost/index.d.ts
  packages/backend/src/apps/ghost/index.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/ghost/connection.md
  packages/docs/pages/public/favicons/ghost.svg
Labels: integration request

#1403 feat(ghost): add new post published trigger
  packages/backend/src/apps/ghost/index.ts
  packages/backend/src/apps/ghost/triggers/index.ts
  packages/backend/src/apps/ghost/triggers/new-post-published/index.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/ghost/triggers.md
  packages/docs/pages/guide/available-apps.md
Labels: enhancement

#1405 feat(carbone): add carbone integration
  packages/backend/src/apps/carbone/assets/favicon.svg
  packages/backend/src/apps/carbone/auth/index.ts
  packages/backend/src/apps/carbone/auth/is-still-verified.ts
  packages/backend/src/apps/carbone/auth/verify-credentials.ts
  packages/backend/src/apps/carbone/common/add-auth-header.ts
  packages/backend/src/apps/carbone/index.d.ts
  packages/backend/src/apps/carbone/index.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/carbone/connection.md
  packages/docs/pages/public/favicons/carbone.svg
  packages/e2e-tests/tests/apps/list-apps.spec.js
Labels: integration request

#1418 feat(xero): add xero integration
  packages/backend/src/apps/xero/assets/favicon.svg
  packages/backend/src/apps/xero/auth/generate-auth-url.ts
  packages/backend/src/apps/xero/auth/index.ts
  packages/backend/src/apps/xero/auth/is-still-verified.ts
  packages/backend/src/apps/xero/auth/refresh-token.ts
  packages/backend/src/apps/xero/auth/verify-credentials.ts
  packages/backend/src/apps/xero/common/add-auth-header.ts
  packages/backend/src/apps/xero/common/auth-scope.ts
  packages/backend/src/apps/xero/common/get-current-user.ts
  packages/backend/src/apps/xero/index.d.ts
  packages/backend/src/apps/xero/index.ts
  packages/docs/pages/apps/xero/connection.md
  packages/docs/pages/public/favicons/xero.svg
Labels: integration request

#1412 fix: let permitted users create step in not-owned flows
  packages/backend/src/graphql/mutations/create-step.ts
Labels: bug

#1417 fix: let permitted users delete others' flows
  packages/backend/src/graphql/mutations/delete-flow.ts
Labels: bug

#1419 feat(xero): add new bank transactions trigger
  packages/backend/src/apps/xero/common/auth-scope.ts
  packages/backend/src/apps/xero/dynamic-data/index.ts
  packages/backend/src/apps/xero/dynamic-data/list-organizations/index.ts
  packages/backend/src/apps/xero/index.ts
  packages/backend/src/apps/xero/triggers/index.ts
  packages/backend/src/apps/xero/triggers/new-bank-transactions/index.ts
  packages/docs/pages/apps/xero/triggers.md
Labels: enhancement

#1422 Release v0.10.0
  docker/Dockerfile
  docker/Dockerfile.compose
  lerna.json
  packages/backend/package.json
  packages/cli/package.json
  packages/docs/package.json
  packages/e2e-tests/package.json
  packages/types/package.json
  packages/web/package.json
Labels: release

#1425 docs(salesforce): list execute query in actions
  packages/docs/pages/apps/salesforce/actions.md
Labels: documentation

#1426 feat(reddit): add reddit integration
  packages/backend/src/apps/reddit/assets/favicon.svg
  packages/backend/src/apps/reddit/auth/generate-auth-url.ts
  packages/backend/src/apps/reddit/auth/index.ts
  packages/backend/src/apps/reddit/auth/is-still-verified.ts
  packages/backend/src/apps/reddit/auth/refresh-token.ts
  packages/backend/src/apps/reddit/auth/verify-credentials.ts
  packages/backend/src/apps/reddit/common/add-auth-header.ts
  packages/backend/src/apps/reddit/common/auth-scope.ts
  packages/backend/src/apps/reddit/common/get-current-user.ts
  packages/backend/src/apps/reddit/index.d.ts
  packages/backend/src/apps/reddit/index.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/reddit/connection.md
  packages/docs/pages/public/favicons/reddit.svg
Labels: enhancement

#1427 feat(reddit): add new posts matching search trigger
  packages/backend/src/apps/reddit/index.ts
  packages/backend/src/apps/reddit/triggers/index.ts
  packages/backend/src/apps/reddit/triggers/new-posts-matching-search/index.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/reddit/triggers.md
  packages/docs/pages/guide/available-apps.md
Labels: enhancement

#1428 feat(reddit): add create link post action
  packages/backend/src/apps/reddit/actions/create-link-post/index.ts
  packages/backend/src/apps/reddit/actions/index.ts
  packages/backend/src/apps/reddit/index.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/reddit/actions.md
Labels: enhancement

#1444 fix(zendesk): get after_cursor from meta field
  packages/backend/src/apps/zendesk/dynamic-data/list-groups/index.ts
  packages/backend/src/apps/zendesk/dynamic-data/list-users/index.ts
Labels: bug

#1441 feat(zendesk): add new tickets trigger
  packages/backend/src/apps/zendesk/dynamic-data/index.ts
  packages/backend/src/apps/zendesk/dynamic-data/list-views/index.ts
  packages/backend/src/apps/zendesk/index.ts
  packages/backend/src/apps/zendesk/triggers/index.ts
  packages/backend/src/apps/zendesk/triggers/new-tickets/index.ts
  packages/docs/pages/apps/zendesk/triggers.md
Labels: enhancement

#1455 feat(discord/create-scheduled-event): remove new prefix
  packages/backend/src/apps/discord/actions/create-scheduled-event/index.ts
  packages/backend/src/apps/discord/actions/index.ts
  packages/docs/pages/apps/discord/actions.md
Labels: enhancement

#1443 feat(zendesk): add update ticket action
  packages/backend/src/apps/zendesk/actions/index.ts
  packages/backend/src/apps/zendesk/actions/update-ticket/fields.ts
  packages/backend/src/apps/zendesk/actions/update-ticket/index.ts
  packages/backend/src/apps/zendesk/dynamic-data/index.ts
  packages/backend/src/apps/zendesk/dynamic-data/list-first-page-of-tickets/index.ts
  packages/docs/pages/apps/zendesk/actions.md
Labels: enhancement

#1447 feat(zendesk): add find ticket action
  packages/backend/src/apps/zendesk/actions/find-ticket/index.ts
  packages/backend/src/apps/zendesk/actions/index.ts
  packages/docs/pages/apps/zendesk/actions.md
Labels: enhancement

#1454 feat(zendesk): add delete user action
  packages/backend/src/apps/zendesk/actions/delete-user/index.ts
  packages/backend/src/apps/zendesk/actions/index.ts
  packages/docs/pages/apps/zendesk/actions.md
Labels: enhancement

#1456 feat(notion): add updated database items trigger
  packages/backend/src/apps/notion/triggers/index.ts
  packages/backend/src/apps/notion/triggers/updated-database-items/index.ts
  packages/backend/src/apps/notion/triggers/updated-database-items/updated-database-items.ts
  packages/docs/pages/apps/notion/triggers.md
Labels: enhancement

#1449 feat(zendesk): add new users trigger
  packages/backend/src/apps/zendesk/triggers/index.ts
  packages/backend/src/apps/zendesk/triggers/new-users/index.ts
  packages/docs/pages/apps/zendesk/triggers.md
Labels: enhancement
