Repository automatisch/automatisch, pull requests merged in 2023-05, with the labels that each got.

#1074 feat: sort executions by updated at
  packages/backend/src/graphql/queries/get-executions.ts
  packages/web/src/components/ExecutionRow/index.tsx
  packages/web/src/locales/en.json
Labels: enhancement

#1078 fix(filters/continue): cover multiple conditions
  packages/backend/src/apps/filter/actions/continue/index.ts
Labels: bug

#1086 feat(ControlledAutocomplete): filter by value too
  packages/web/src/components/ControlledAutocomplete/index.tsx
Labels: enhancement

#1088 fix(queries/get-execution): serve soft deleteds
  packages/backend/src/graphql/queries/get-execution.ts
Labels: bug

#1087 feat(ExecutionStep): show execution date
  packages/web/src/components/ExecutionHeader/index.tsx
  packages/web/src/components/ExecutionStep/index.tsx
  packages/web/src/locales/en.json
Labels: enhancement

#1085 feat: add duplicate flow functionality
  packages/backend/src/graphql/mutation-resolvers.ts
  packages/backend/src/graphql/mutations/duplicate-flow.ts
  packages/backend/src/graphql/schema.graphql
  packages/web/src/components/FlowContextMenu/index.tsx
  packages/web/src/graphql/mutations/duplicate-flow.ts
  packages/web/src/locales/en.json
Labels: enhancement

#1093 feat(openai): add chat prompt
  packages/backend/src/apps/openai/actions/index.ts
  packages/backend/src/apps/openai/actions/send-chat-prompt/index.ts
Labels: enhancement

#1095 feat(google-sheets): add new worksheets trigger
  packages/backend/src/apps/google-sheets/dynamic-data/index.ts
  packages/backend/src/apps/google-sheets/dynamic-data/list-spreadsheets/index.ts
  packages/backend/src/apps/google-sheets/triggers/index.ts
  packages/backend/src/apps/google-sheets/triggers/new-worksheets/index.ts
  packages/backend/src/apps/google-sheets/triggers/new-worksheets/new-worksheets.ts
  packages/docs/pages/apps/google-sheets/triggers.md
Labels: enhancement

#1099 fix(shared-drive): show shared drive items
  packages/backend/src/apps/google-drive/dynamic-data/list-folders/index.ts
  packages/backend/src/apps/google-drive/triggers/new-files-in-folder/index.ts
  packages/backend/src/apps/google-drive/triggers/new-files-in-folder/new-files-in-folder.ts
  packages/backend/src/apps/google-drive/triggers/new-files/new-files.ts
  packages/backend/src/apps/google-drive/triggers/new-folders/index.ts
  packages/backend/src/apps/google-drive/triggers/new-folders/new-folders.ts
  packages/backend/src/apps/google-drive/triggers/updated-files/index.ts
  packages/backend/src/apps/google-drive/triggers/updated-files/updated-files.ts
  packages/backend/src/apps/google-sheets/dynamic-data/list-spreadsheets/index.ts
  packages/backend/src/apps/google-sheets/triggers/new-spreadsheets/new-spreadsheets.ts
Labels: bug

#1100 Release v0.7.0
  docker/Dockerfile
  docker/Dockerfile.compose
  lerna.json
  packages/backend/package.json
  packages/cli/package.json
  packages/docs/package.json
  packages/e2e-tests/package.json
  packages/types/package.json
  packages/web/package.json
Labels: release

#1102 fix(shared-drive): add missing field to payload
  packages/backend/src/apps/google-drive/dynamic-data/list-folders/index.ts
  packages/backend/src/apps/google-drive/triggers/new-files-in-folder/new-files-in-folder.ts
  packages/backend/src/apps/google-drive/triggers/new-files/new-files.ts
  packages/backend/src/apps/google-drive/triggers/new-folders/new-folders.ts
  packages/backend/src/apps/google-drive/triggers/updated-files/updated-files.ts
  packages/backend/src/apps/google-sheets/dynamic-data/list-spreadsheets/index.ts
  packages/backend/src/apps/google-sheets/triggers/new-spreadsheets/new-spreadsheets.ts
Labels: bug

#1103 Release v0.7.1
  docker/Dockerfile
  docker/Dockerfile.compose
  lerna.json
  packages/backend/package.json
  packages/cli/package.json
  packages/docs/package.json
  packages/e2e-tests/package.json
  packages/types/package.json
  packages/web/package.json
Labels: release

#1106 feat(webhook/handler): use UUID for internal ids
  packages/backend/src/controllers/webhooks/handler.ts
Labels: enhancement

#1109 fix: early exit upon failed actions
  packages/backend/src/workers/action.ts
Labels: bug
