Repository automatisch/automatisch, pull requests merged in 2023-02, with the labels that each got.

#867 fix: readme git clone command
  README.md
Labels: documentation

#872 feat(http-request): introduce custom request action
  packages/backend/src/apps/http-request/actions/custom-request/index.ts
  packages/backend/src/apps/http-request/actions/index.ts
  packages/backend/src/apps/http-request/assets/favicon.svg
  packages/backend/src/apps/http-request/index.d.ts
  packages/backend/src/apps/http-request/index.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/http-request/actions.md
  packages/docs/pages/apps/http-request/connection.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/http-request.svg
Labels: enhancement

#880 feat(slack/list-channels): add private and exclude archived channels
  packages/backend/src/apps/slack/dynamic-data/list-channels/index.ts
Labels: enhancement

#888 feat(slack/list-channels): add im channels and increase limit
  packages/backend/src/apps/slack/auth/generate-auth-url.ts
  packages/backend/src/apps/slack/dynamic-data/list-channels/index.ts
Labels: enhancement

#887 fix(worker): compute parameters for delaying job
  packages/backend/src/helpers/delay-as-milliseconds.ts
  packages/backend/src/services/action.ts
  packages/backend/src/workers/action.ts
Labels: bug

#953 feat(filter): add filter app
  packages/backend/src/apps/filter/actions/continue/index.ts
  packages/backend/src/apps/filter/actions/index.ts
  packages/backend/src/apps/filter/assets/favicon.svg
  packages/backend/src/apps/filter/index.d.ts
  packages/backend/src/apps/filter/index.ts
  packages/backend/src/errors/already-processed.ts
  packages/backend/src/helpers/compute-parameters.ts
  packages/backend/src/helpers/global-variable.ts
  packages/backend/src/services/action.ts
  packages/backend/src/services/flow.ts
  packages/backend/src/workers/action.ts
  packages/types/index.d.ts
  packages/web/package.json
  packages/web/src/components/ControlledAutocomplete/index.tsx
  packages/web/src/components/FlowSubstep/FilterConditions/index.tsx
  packages/web/src/components/FlowSubstep/index.tsx
  packages/web/src/components/InputCreator/index.tsx
  packages/web/src/components/PowerInput/index.tsx
  packages/web/src/locales/en.json
  packages/web/src/styles/theme.ts
  packages/web/yarn.lock
  yarn.lock
Labels: enhancement

#959 fix: do not suppress native GQL errors
  packages/backend/src/helpers/graphql-instance.ts
Labels: bug

#961 fix(ntfy): use given server URL instead of default
  packages/backend/src/apps/ntfy/common/add-auth-header.ts
Labels: bug

#962 fix: correct errors for unreachable servers
  packages/backend/src/helpers/http-client/index.ts
Labels: bug
