Repository automatisch/automatisch, pull requests merged in 2023-06, with the labels that each got.

#1120 chore: update action and trigger names
  packages/backend/src/apps/deepl/actions/translate-text/index.ts
  packages/backend/src/apps/delay/actions/delay-for/index.ts
  packages/backend/src/apps/delay/actions/delay-until/index.ts
  packages/backend/src/apps/google-drive/dynamic-data/list-folders/index.ts
  packages/backend/src/apps/google-drive/triggers/new-files-in-folder/index.ts
  packages/backend/src/apps/google-drive/triggers/new-files/index.ts
  packages/backend/src/apps/google-drive/triggers/new-folders/index.ts
  packages/backend/src/apps/google-drive/triggers/updated-files/index.ts
  packages/backend/src/apps/google-forms/triggers/new-form-responses/index.ts
  packages/backend/src/apps/google-sheets/triggers/new-spreadsheets/index.ts
  packages/backend/src/apps/google-sheets/triggers/new-worksheets/index.ts
  packages/backend/src/apps/http-request/actions/custom-request/index.ts
  packages/backend/src/apps/stripe/triggers/balance-transaction/index.ts
  packages/backend/src/apps/stripe/triggers/payouts/index.ts
  packages/backend/src/apps/todoist/actions/create-task/index.ts
  packages/backend/src/apps/todoist/triggers/get-tasks/index.ts
  packages/backend/src/apps/twitter/actions/create-tweet/index.ts
  packages/docs/pages/apps/deepl/actions.md
  packages/docs/pages/apps/delay/actions.md
  packages/docs/pages/apps/google-drive/triggers.md
  packages/docs/pages/apps/google-forms/triggers.md
  packages/docs/pages/apps/google-sheets/triggers.md
  packages/docs/pages/apps/http-request/actions.md
  packages/docs/pages/apps/strava/actions.md
  packages/docs/pages/apps/stripe/triggers.md
  packages/docs/pages/apps/todoist/actions.md
  packages/docs/pages/apps/todoist/triggers.md
  packages/docs/pages/apps/twitter/actions.md
Labels: documentation

#1121 fix: stop checking auth urls
  packages/backend/src/graphql/mutations/generate-auth-url.ts
Labels: bug

#1122 feat(gitlab): add instance URL in screen name
  packages/backend/src/apps/gitlab/auth/verify-credentials.ts
Labels: enhancement

#1118 feat(google-sheets): add new spreadsheet rows trigger
  packages/backend/src/apps/google-sheets/triggers/index.ts
  packages/backend/src/apps/google-sheets/triggers/new-spreadsheet-rows/index.ts
  packages/backend/src/apps/google-sheets/triggers/new-spreadsheet-rows/new-spreadsheet-rows.ts
  packages/docs/pages/apps/google-sheets/triggers.md
Labels: enhancement

#1127 fix(webhook/handler): log whole computed payload
  packages/backend/src/controllers/webhooks/handler.ts
Labels: bug

#1125 feat: prevent from being used in iframe
  packages/backend/src/helpers/web-ui-handler.ts
Labels: enhancement

#1135 docs(postgres): add connection and actions
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/postgresql/actions.md
  packages/docs/pages/apps/postgresql/connection.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/postgres.svg
Labels: documentation

#1139 fix: update flow.active when remote calls succeed
  packages/backend/src/graphql/mutations/update-flow-status.ts
Labels: bug

#1130 docs(gitlab): add connection and triggers
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/gitlab/connection.md
  packages/docs/pages/apps/gitlab/triggers.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/gitlab.svg
Labels: documentation

#1124 feat: introduce CustomAutocomplete with variables
  packages/backend/src/apps/deepl/actions/translate-text/index.ts
  packages/backend/src/apps/delay/actions/delay-for/index.ts
  packages/backend/src/apps/discord/actions/send-message-to-channel/index.ts
  packages/backend/src/apps/github/actions/create-issue/index.ts
  packages/backend/src/apps/google-sheets/actions/create-spreadsheet-row/index.ts
  packages/backend/src/apps/http-request/actions/custom-request/index.ts
  packages/backend/src/apps/openai/actions/send-chat-prompt/index.ts
  packages/backend/src/apps/openai/actions/send-prompt/index.ts
  packages/backend/src/apps/postgresql/actions/delete/index.ts
  packages/backend/src/apps/postgresql/actions/insert/index.ts
  packages/backend/src/apps/postgresql/actions/sql-query/index.ts
  packages/backend/src/apps/postgresql/actions/update/index.ts
  packages/backend/src/apps/salesforce/actions/find-record/index.ts
  packages/backend/src/apps/slack/actions/find-message/index.ts
  packages/backend/src/apps/slack/actions/send-a-direct-message/index.ts
  packages/backend/src/apps/slack/actions/send-a-message-to-channel/index.ts
  packages/backend/src/apps/telegram-bot/actions/send-message/index.ts
  packages/backend/src/apps/todoist/actions/create-task/index.ts
  packages/backend/src/apps/twilio/actions/send-sms/index.ts
  packages/backend/src/graphql/queries/get-dynamic-data.ts
  packages/backend/src/models/flow.ts
  packages/web/package.json
  packages/web/src/components/ControlledCustomAutocomplete/Controller.tsx
  packages/web/src/components/ControlledCustomAutocomplete/CustomOptions.tsx
  packages/web/src/components/ControlledCustomAutocomplete/Options.tsx
  packages/web/src/components/ControlledCustomAutocomplete/index.tsx
  packages/web/src/components/ControlledCustomAutocomplete/style.ts
  packages/web/src/components/FlowStep/index.tsx
  packages/web/src/components/FlowSubstep/index.tsx
  packages/web/src/components/InputCreator/index.tsx
  packages/web/src/components/PowerInput/Popper.tsx
  packages/web/src/components/PowerInput/Suggestions.tsx
  packages/web/src/components/PowerInput/data.ts
  packages/web/src/components/PowerInput/index.tsx
  packages/web/src/components/PowerInput/style.ts
  packages/web/src/components/PowerInput/utils.ts
  packages/web/src/components/SearchableJSONViewer/index.tsx
  packages/web/src/components/Slate/Element.tsx
  packages/web/src/components/Slate/Variable.tsx
  packages/web/src/components/Slate/index.tsx
  packages/web/src/components/Slate/types.ts
  packages/web/src/components/Slate/utils.ts
  packages/web/src/graphql/mutations/create-step.ts
  packages/web/src/helpers/filterObject.ts
  packages/web/src/helpers/isEmpty.ts
  packages/web/src/locales/en.json
  yarn.lock
Labels: enhancement

#1141 fix: skip prior execution steps if no prior execution
  packages/backend/src/graphql/queries/get-dynamic-data.ts
Labels: bug

#1140 feat(notion): add auth and new DB items trigger
  packages/backend/src/apps/notion/assets/favicon.svg
  packages/backend/src/apps/notion/auth/generate-auth-url.ts
  packages/backend/src/apps/notion/auth/index.ts
  packages/backend/src/apps/notion/auth/is-still-verified.ts
  packages/backend/src/apps/notion/auth/verify-credentials.ts
  packages/backend/src/apps/notion/common/add-auth-header.ts
  packages/backend/src/apps/notion/common/add-notion-version-header.ts
  packages/backend/src/apps/notion/common/get-current-user.ts
  packages/backend/src/apps/notion/dynamic-data/index.ts
  packages/backend/src/apps/notion/dynamic-data/list-databases/index.ts
  packages/backend/src/apps/notion/index.d.ts
  packages/backend/src/apps/notion/index.ts
  packages/backend/src/apps/notion/triggers/index.ts
  packages/backend/src/apps/notion/triggers/new-database-items/index.ts
  packages/backend/src/apps/notion/triggers/new-database-items/new-database-items.ts
  packages/backend/src/graphql/queries/get-dynamic-data.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/notion/connection.md
  packages/docs/pages/apps/notion/triggers.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/notion.svg
Labels: integration request

#1142 fix(twilio/receive-sms): use phone number via phone number sid
  packages/backend/src/apps/twilio/common/get-incoming-phone-number.ts
  packages/backend/src/apps/twilio/triggers/receive-sms/fetch-messages.ts
Labels: bug

#1146 feat(google-sheets): add create spreadsheet action
  packages/backend/src/apps/google-sheets/actions/create-spreadsheet/index.ts
  packages/backend/src/apps/google-sheets/actions/index.ts
  packages/docs/pages/apps/google-sheets/actions.md
Labels: enhancement

#1157 fix(discord): show announcement channels in selection
  packages/backend/src/apps/discord/dynamic-data/list-channels/index.ts
Labels: enhancement

#1162 fix(postgresql): close connections when done
  packages/backend/src/apps/postgresql/actions/delete/index.ts
  packages/backend/src/apps/postgresql/actions/insert/index.ts
  packages/backend/src/apps/postgresql/actions/sql-query/index.ts
  packages/backend/src/apps/postgresql/actions/update/index.ts
  packages/backend/src/apps/postgresql/auth/verify-credentials.ts
Labels: bug, enhancement

#1143 feat(odoo): add auth and create lead action
  packages/backend/package.json
  packages/backend/src/apps/odoo/actions/create-lead/index.ts
  packages/backend/src/apps/odoo/actions/index.ts
  packages/backend/src/apps/odoo/assets/favicon.svg
  packages/backend/src/apps/odoo/auth/index.ts
  packages/backend/src/apps/odoo/auth/is-still-verified.ts
  packages/backend/src/apps/odoo/auth/verify-credentials.ts
  packages/backend/src/apps/odoo/common/xmlrpc-client.ts
  packages/backend/src/apps/odoo/index.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/odoo/actions.md
  packages/docs/pages/apps/odoo/connection.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/odoo.svg
  yarn.lock
Labels: integration request

#1165 fix(odoo): add missing empty type file
  packages/backend/src/apps/odoo/index.d.ts
Labels: bug

#1163 feat(mattermost): add auth and send message to channel action
  packages/backend/src/apps/mattermost/actions/index.ts
  packages/backend/src/apps/mattermost/actions/send-a-message-to-channel/index.ts
  packages/backend/src/apps/mattermost/actions/send-a-message-to-channel/post-message.ts
  packages/backend/src/apps/mattermost/assets/favicon.svg
  packages/backend/src/apps/mattermost/auth/generate-auth-url.ts
  packages/backend/src/apps/mattermost/auth/index.ts
  packages/backend/src/apps/mattermost/auth/is-still-verified.ts
  packages/backend/src/apps/mattermost/auth/verify-credentials.ts
  packages/backend/src/apps/mattermost/common/add-auth-header.ts
  packages/backend/src/apps/mattermost/common/add-x-requested-with-header.ts
  packages/backend/src/apps/mattermost/common/get-base-url.ts
  packages/backend/src/apps/mattermost/common/get-current-user.ts
  packages/backend/src/apps/mattermost/common/set-base-url.ts
  packages/backend/src/apps/mattermost/dynamic-data/index.ts
  packages/backend/src/apps/mattermost/dynamic-data/list-channels/index.ts
  packages/backend/src/apps/mattermost/index.d.ts
  packages/backend/src/apps/mattermost/index.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/mattermost/actions.md
  packages/docs/pages/apps/mattermost/connection.md
  packages/docs/pages/guide/available-apps.md
Labels: integration request
