Repository automatisch/automatisch, pull requests merged in 2023-09, with the labels that each got.

#1258 Release v0.9.3
  docker/Dockerfile
  docker/Dockerfile.compose
  lerna.json
  packages/backend/package.json
  packages/cli/package.json
  packages/docs/package.json
  packages/e2e-tests/package.json
  packages/types/package.json
  packages/web/package.json
Labels: release

#1267 feat(user-interface): add title field
  packages/web/src/components/MetadataProvider/index.tsx
  packages/web/src/index.tsx
  packages/web/src/locales/en.json
  packages/web/src/pages/UserInterface/index.tsx
Labels: enhancement

#1286 chore: embed env. vars. for playwright actions
  .github/workflows/ci.yml
  .github/workflows/playwright.yml
Labels: enhancement

#1290 feat(google-calendar): add new calendar trigger
  packages/backend/src/apps/google-calendar/assets/favicon.svg
  packages/backend/src/apps/google-calendar/auth/generate-auth-url.ts
  packages/backend/src/apps/google-calendar/auth/index.ts
  packages/backend/src/apps/google-calendar/auth/is-still-verified.ts
  packages/backend/src/apps/google-calendar/auth/refresh-token.ts
  packages/backend/src/apps/google-calendar/auth/verify-credentials.ts
  packages/backend/src/apps/google-calendar/common/add-auth-header.ts
  packages/backend/src/apps/google-calendar/common/auth-scope.ts
  packages/backend/src/apps/google-calendar/common/get-current-user.ts
  packages/backend/src/apps/google-calendar/index.d.ts
  packages/backend/src/apps/google-calendar/index.ts
  packages/backend/src/apps/google-calendar/triggers/index.ts
  packages/backend/src/apps/google-calendar/triggers/new-calendar/index.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/google-calendar/connection.md
  packages/docs/pages/apps/google-calendar/triggers.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/google-calendar.svg
Labels: integration request

#1294 feat(pipedrive): add new deals trigger
  packages/backend/src/apps/pipedrive/assets/favicon.svg
  packages/backend/src/apps/pipedrive/auth/generate-auth-url.ts
  packages/backend/src/apps/pipedrive/auth/index.ts
  packages/backend/src/apps/pipedrive/auth/is-still-verified.ts
  packages/backend/src/apps/pipedrive/auth/refresh-token.ts
  packages/backend/src/apps/pipedrive/auth/verify-credentials.ts
  packages/backend/src/apps/pipedrive/common/add-auth-header.ts
  packages/backend/src/apps/pipedrive/common/get-current-user.ts
  packages/backend/src/apps/pipedrive/index.d.ts
  packages/backend/src/apps/pipedrive/index.ts
  packages/backend/src/apps/pipedrive/triggers/index.ts
  packages/backend/src/apps/pipedrive/triggers/new-deals/index.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/pipedrive/connection.md
  packages/docs/pages/apps/pipedrive/triggers.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/pipedrive.svg
Labels: integration request

#1305 fix: use default role for fallback user creation
  packages/backend/src/graphql/mutations/create-user.ee.ts
Labels: bug

#1297 feat(pipedrive): add new notes trigger
  packages/backend/src/apps/pipedrive/auth/refresh-token.ts
  packages/backend/src/apps/pipedrive/common/add-auth-header.ts
  packages/backend/src/apps/pipedrive/triggers/index.ts
  packages/backend/src/apps/pipedrive/triggers/new-notes/index.ts
  packages/docs/pages/apps/pipedrive/triggers.md
Labels: enhancement

#1298 feat(pipedrive): add new activities trigger
  packages/backend/src/apps/pipedrive/triggers/index.ts
  packages/backend/src/apps/pipedrive/triggers/new-activities/index.ts
  packages/docs/pages/apps/pipedrive/triggers.md
Labels: enhancement

#1299 feat(pipedrive): add new leads trigger
  packages/backend/src/apps/pipedrive/triggers/index.ts
  packages/backend/src/apps/pipedrive/triggers/new-leads/index.ts
  packages/docs/pages/apps/pipedrive/triggers.md
Labels: enhancement

#1300 feat(miro): add create board action
  packages/backend/src/apps/miro/actions/create-board/index.ts
  packages/backend/src/apps/miro/actions/index.ts
  packages/backend/src/apps/miro/assets/favicon.svg
  packages/backend/src/apps/miro/auth/generate-auth-url.ts
  packages/backend/src/apps/miro/auth/index.ts
  packages/backend/src/apps/miro/auth/is-still-verified.ts
  packages/backend/src/apps/miro/auth/refresh-token.ts
  packages/backend/src/apps/miro/auth/verify-credentials.ts
  packages/backend/src/apps/miro/common/add-auth-header.ts
  packages/backend/src/apps/miro/common/get-current-user.ts
  packages/backend/src/apps/miro/index.d.ts
  packages/backend/src/apps/miro/index.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/miro/actions.md
  packages/docs/pages/apps/miro/connection.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/miro.svg
Labels: integration request

#1301 feat(miro): add copy board action
  packages/backend/src/apps/miro/actions/copy-board/index.ts
  packages/backend/src/apps/miro/actions/index.ts
  packages/backend/src/apps/miro/dynamic-data/index.ts
  packages/backend/src/apps/miro/dynamic-data/list-boards/index.ts
  packages/backend/src/apps/miro/index.ts
  packages/docs/pages/apps/miro/actions.md
Labels: enhancement

#1302 feat(miro): add create card widget action
  packages/backend/src/apps/miro/actions/create-card-widget/index.ts
  packages/backend/src/apps/miro/actions/index.ts
  packages/backend/src/apps/miro/dynamic-data/index.ts
  packages/backend/src/apps/miro/dynamic-data/list-frames/index.ts
  packages/docs/pages/apps/miro/actions.md
Labels: enhancement

#1307 feat(pipedrive): add create deal action
  packages/backend/src/apps/pipedrive/actions/create-deal/index.ts
  packages/backend/src/apps/pipedrive/actions/index.ts
  packages/backend/src/apps/pipedrive/dynamic-data/index.ts
  packages/backend/src/apps/pipedrive/dynamic-data/list-currencies/index.ts
  packages/backend/src/apps/pipedrive/dynamic-data/list-organizations/index.ts
  packages/backend/src/apps/pipedrive/dynamic-data/list-persons/index.ts
  packages/backend/src/apps/pipedrive/dynamic-data/list-users/index.ts
  packages/backend/src/apps/pipedrive/index.ts
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/pipedrive/actions.md
Labels: enhancement
