Repository automatisch/automatisch, pull requests merged in 2024-11, with the labels that each got.

#2153 refactor(flow): distribute createActionStep logic to different methods in model
  packages/backend/src/controllers/api/v1/flows/create-step.js
  packages/backend/src/models/flow.js
  packages/backend/src/models/flow.test.js
Labels: enhancement

#2156 refactor(flow): split delete method and write test
  packages/backend/src/models/flow.js
  packages/backend/src/models/flow.test.js
Labels: enhancement

#2158 test(flow): write test cases for isPaused method
  packages/backend/src/models/flow.test.js
Labels: enhancement

#2159 test(step): cover tableName, jsonSchema, virtualAttributes, relationMappings in model
  packages/backend/src/models/__snapshots__/step.test.js.snap
  packages/backend/src/models/step.test.js
Labels: enhancement

#2161 test(step): write tests for isTrigger, isAction, getWebhookUrl
  packages/backend/src/models/step.js
  packages/backend/src/models/step.test.js
Labels: enhancement

#2163 test(step): write tests for getTriggerCommand and getActionCommand
  packages/backend/src/models/step.test.js
Labels: enhancement

#2164 test(step): write tests for getSetupFields and delete
  packages/backend/src/models/step.js
  packages/backend/src/models/step.test.js
Labels: enhancement

#2166 test(step): write test for updateFor method in model
  packages/backend/src/models/step.js
  packages/backend/src/models/step.test.js
  packages/backend/test/factories/role.js
Labels: enhancement

#2168 test(user): write tests for tableName, jsonSchema, relationMappings
  packages/backend/src/models/__snapshots__/user.test.js.snap
  packages/backend/src/models/user.test.js
Labels: enhancement

#2176 test(user): write test for acceptInvitationUrl
  packages/backend/src/models/user.test.js
Labels: enhancement

#2174 test(user): write tests for authorizedConnections
  packages/backend/src/models/user.test.js
Labels: enhancement

#2177 test(user): write tests for authenticate
  packages/backend/src/models/user.test.js
Labels: enhancement

#2170 test(user): write tests for authorizedFlows
  packages/backend/src/models/user.js
  packages/backend/src/models/user.test.js
Labels: enhancement

#2178 test(user): write tests for login
  packages/backend/src/models/user.js
  packages/backend/src/models/user.test.js
Labels: enhancement

#2180 test(user): write test for generateInvitationToken
  packages/backend/src/models/user.test.js
Labels: enhancement

#2181 test(user): write test for resetPassword
  packages/backend/src/models/user.test.js
Labels: enhancement

#2182 test(user): write test for acceptInvitation
  packages/backend/src/models/user.test.js
Labels: enhancement

#2183 test(user): write tests for updatePassword
  packages/backend/src/models/user.test.js
Labels: enhancement

#2210 Update version to 0.14.0
  packages/backend/src/config/app.js
  packages/backend/src/controllers/api/v1/automatisch/version.test.js
Labels: release

#2212 Remove lerna and yarn workspaces
  .github/workflows/backend.yml
  .github/workflows/ci.yml
  .github/workflows/playwright.yml
  .gitignore
  docker/Dockerfile
  lerna.json
  package.json
  packages/backend/package.json
  packages/backend/yarn.lock
  packages/docs/.gitignore
  packages/docs/package.json
  packages/docs/pages/contributing/development-setup.md
  packages/docs/pages/contributing/repository-structure.md
  packages/docs/yarn.lock
  packages/e2e-tests/package.json
  packages/e2e-tests/yarn.lock
  packages/web/package.json
  packages/web/src/components/ControlledCustomAutocomplete/index.jsx
  packages/web/src/components/PowerInput/index.jsx
  packages/web/src/components/SplitButton/index.jsx
  packages/web/yarn.lock
  yarn.lock
Labels: documentation-change

#2184 test(user): write test for softRemove
  packages/backend/src/models/user.test.js
Labels: enhancement

#2185 test(user): write test for sendResetPasswordEmail
  packages/backend/src/models/user.test.js
Labels: enhancement

#2187 test(user): write test cases for isResetPasswordTokenValid
  packages/backend/src/models/user.test.js
Labels: enhancement

#2188 test(user): write test for sendInvitationEmail
  packages/backend/src/models/user.test.js
Labels: enhancement

#2197 test(user): write tests for isInvitationTokenValid
  packages/backend/src/models/user.test.js
Labels: enhancement

#2198 test(user): write tests for generateHash
  packages/backend/src/models/user.test.js
Labels: enhancement

#2203 test(user): write tests for inTrial
  packages/backend/src/models/user.test.js
Labels: enhancement

#2204 test(user): write tests for hasActiveSubscription
  packages/backend/src/models/user.test.js
Labels: enhancement

#2205 test(user): write tests for withinLimits
  packages/backend/src/models/user.test.js
Labels: enhancement

#2214 test(user): write tests for getInvoices
  packages/backend/src/models/user.test.js
Labels: enhancement

#2215 test(user): write test for createAdmin
  packages/backend/src/models/user.test.js
Labels: enhancement

#2216 test(user): write tests for registerUser
  packages/backend/src/models/user.test.js
Labels: enhancement

#2217 test(user): write tests for ability and can
  packages/backend/src/helpers/user-ability.test.js
  packages/backend/src/models/user.js
  packages/backend/src/models/user.test.js
Labels: enhancement

#2219 test(user): write tests for $beforeInsert and $beforeUpdate
  packages/backend/src/models/user.js
  packages/backend/src/models/user.test.js
Labels: enhancement

#2220 test(user): write tests for $afterInsert and $afterFind
  packages/backend/src/models/user.js
  packages/backend/src/models/user.test.js
Labels: enhancement

#2224 chore: add test coverage
  .github/workflows/backend.yml
  packages/backend/package.json
  packages/backend/vitest.config.js
  packages/backend/yarn.lock
Labels: enhancement
