Repository automatisch/automatisch, pull requests merged in 2024-05, with the labels that each got.

#1845 feat(formatter): add encode uri action
  packages/backend/src/apps/formatter/actions/text/index.js
  packages/backend/src/apps/formatter/actions/text/transformers/encode-uri.js
  packages/backend/src/apps/formatter/dynamic-fields/list-transform-options/index.js
  packages/backend/src/apps/formatter/dynamic-fields/list-transform-options/text/encode-uri.js
Labels: enhancement

#1476 feat(disqus): add new comments trigger
  packages/backend/src/apps/disqus/dynamic-data/index.js
  packages/backend/src/apps/disqus/dynamic-data/list-forums/index.js
  packages/backend/src/apps/disqus/index.js
  packages/backend/src/apps/disqus/triggers/index.js
  packages/backend/src/apps/disqus/triggers/new-comments/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/disqus/triggers.md
  packages/docs/pages/guide/available-apps.md
Labels: enhancement

#1492 feat(google-tasks): add new completed tasks trigger
  packages/backend/src/apps/google-tasks/triggers/index.js
  packages/backend/src/apps/google-tasks/triggers/new-completed-tasks/index.js
  packages/docs/pages/apps/google-tasks/triggers.md
Labels: enhancement

#1490 feat(google-tasks): add new tasks trigger
  packages/backend/src/apps/google-tasks/triggers/index.js
  packages/backend/src/apps/google-tasks/triggers/new-completed-tasks/index.js
  packages/backend/src/apps/google-tasks/triggers/new-tasks/index.js
  packages/docs/pages/apps/google-tasks/triggers.md
Labels: enhancement

#1489 feat(google-tasks): add new task lists trigger
  packages/backend/src/apps/google-tasks/triggers/index.js
  packages/backend/src/apps/google-tasks/triggers/new-completed-tasks/index.js
  packages/backend/src/apps/google-tasks/triggers/new-task-lists/index.js
  packages/backend/src/apps/google-tasks/triggers/new-tasks/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/google-tasks/triggers.md
Labels: enhancement

#1488 feat(google-tasks): add create task list action
  packages/backend/src/apps/google-tasks/actions/create-task-list/index.js
  packages/backend/src/apps/google-tasks/actions/index.js
  packages/backend/src/apps/google-tasks/triggers/index.js
  packages/backend/src/apps/google-tasks/triggers/new-completed-tasks/index.js
  packages/backend/src/apps/google-tasks/triggers/new-task-lists/index.js
  packages/backend/src/apps/google-tasks/triggers/new-tasks/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/google-tasks/actions.md
  packages/docs/pages/apps/google-tasks/triggers.md
Labels: enhancement

#1487 feat(google-tasks): add create task action
  packages/backend/src/apps/google-tasks/actions/create-task-list/index.js
  packages/backend/src/apps/google-tasks/actions/create-task/index.js
  packages/backend/src/apps/google-tasks/actions/index.js
  packages/backend/src/apps/google-tasks/triggers/index.js
  packages/backend/src/apps/google-tasks/triggers/new-completed-tasks/index.js
  packages/backend/src/apps/google-tasks/triggers/new-task-lists/index.js
  packages/backend/src/apps/google-tasks/triggers/new-tasks/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/google-tasks/actions.md
  packages/docs/pages/apps/google-tasks/triggers.md
Labels: enhancement

#1486 feat(google-tasks): add update task action
  packages/backend/src/apps/google-tasks/actions/create-task-list/index.js
  packages/backend/src/apps/google-tasks/actions/create-task/index.js
  packages/backend/src/apps/google-tasks/actions/index.js
  packages/backend/src/apps/google-tasks/actions/update-task/index.js
  packages/backend/src/apps/google-tasks/dynamic-data/index.js
  packages/backend/src/apps/google-tasks/dynamic-data/list-tasks/index.js
  packages/backend/src/apps/google-tasks/triggers/index.js
  packages/backend/src/apps/google-tasks/triggers/new-completed-tasks/index.js
  packages/backend/src/apps/google-tasks/triggers/new-task-lists/index.js
  packages/backend/src/apps/google-tasks/triggers/new-tasks/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/google-tasks/actions.md
  packages/docs/pages/apps/google-tasks/triggers.md
Labels: enhancement

#1485 feat(google-tasks): add find task action
  packages/backend/src/apps/google-tasks/actions/create-task-list/index.js
  packages/backend/src/apps/google-tasks/actions/create-task/index.js
  packages/backend/src/apps/google-tasks/actions/find-task/index.js
  packages/backend/src/apps/google-tasks/actions/index.js
  packages/backend/src/apps/google-tasks/actions/update-task/index.js
  packages/backend/src/apps/google-tasks/dynamic-data/index.js
  packages/backend/src/apps/google-tasks/dynamic-data/list-task-lists/index.js
  packages/backend/src/apps/google-tasks/dynamic-data/list-tasks/index.js
  packages/backend/src/apps/google-tasks/index.js
  packages/backend/src/apps/google-tasks/triggers/index.js
  packages/backend/src/apps/google-tasks/triggers/new-completed-tasks/index.js
  packages/backend/src/apps/google-tasks/triggers/new-task-lists/index.js
  packages/backend/src/apps/google-tasks/triggers/new-tasks/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/google-tasks/actions.md
  packages/docs/pages/apps/google-tasks/triggers.md
  packages/docs/pages/guide/available-apps.md
Labels: enhancement

#1484 feat(google-tasks): add google tasks integration
  packages/backend/src/apps/google-tasks/actions/create-task-list/index.js
  packages/backend/src/apps/google-tasks/actions/create-task/index.js
  packages/backend/src/apps/google-tasks/actions/find-task/index.js
  packages/backend/src/apps/google-tasks/actions/index.js
  packages/backend/src/apps/google-tasks/actions/update-task/index.js
  packages/backend/src/apps/google-tasks/assets/favicon.svg
  packages/backend/src/apps/google-tasks/auth/generate-auth-url.js
  packages/backend/src/apps/google-tasks/auth/index.js
  packages/backend/src/apps/google-tasks/auth/is-still-verified.js
  packages/backend/src/apps/google-tasks/auth/refresh-token.js
  packages/backend/src/apps/google-tasks/auth/verify-credentials.js
  packages/backend/src/apps/google-tasks/common/add-auth-header.js
  packages/backend/src/apps/google-tasks/common/auth-scope.js
  packages/backend/src/apps/google-tasks/common/get-current-user.js
  packages/backend/src/apps/google-tasks/dynamic-data/index.js
  packages/backend/src/apps/google-tasks/dynamic-data/list-task-lists/index.js
  packages/backend/src/apps/google-tasks/dynamic-data/list-tasks/index.js
  packages/backend/src/apps/google-tasks/index.js
  packages/backend/src/apps/google-tasks/triggers/index.js
  packages/backend/src/apps/google-tasks/triggers/new-completed-tasks/index.js
  packages/backend/src/apps/google-tasks/triggers/new-task-lists/index.js
  packages/backend/src/apps/google-tasks/triggers/new-tasks/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/google-tasks/actions.md
  packages/docs/pages/apps/google-tasks/connection.md
  packages/docs/pages/apps/google-tasks/triggers.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/google-tasks.svg
Labels: enhancement, documentation-change

#1519 feat(vtiger-crm): add new cases trigger
  packages/backend/src/apps/vtiger-crm/index.js
  packages/backend/src/apps/vtiger-crm/triggers/index.js
  packages/backend/src/apps/vtiger-crm/triggers/new-cases/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/vtiger-crm/triggers.md
  packages/docs/pages/guide/available-apps.md
Labels: enhancement

#1520 feat(vtiger-crm): add new contacts trigger
  packages/backend/src/apps/vtiger-crm/triggers/index.js
  packages/backend/src/apps/vtiger-crm/triggers/new-contacts/index.js
  packages/docs/pages/apps/vtiger-crm/triggers.md
Labels: enhancement

#1521 feat(vtiger-crm): add new invoices trigger
  packages/backend/src/apps/vtiger-crm/triggers/index.js
  packages/backend/src/apps/vtiger-crm/triggers/new-invoices/index.js
  packages/docs/pages/apps/vtiger-crm/triggers.md
Labels: enhancement

#1522 feat(vtiger-crm): add new leads trigger
  packages/backend/src/apps/vtiger-crm/triggers/index.js
  packages/backend/src/apps/vtiger-crm/triggers/new-leads/index.js
  packages/docs/pages/apps/vtiger-crm/triggers.md
Labels: enhancement

#1523 feat(vtiger-crm): add new opportunities trigger
  packages/backend/src/apps/vtiger-crm/triggers/index.js
  packages/backend/src/apps/vtiger-crm/triggers/new-opportunities/index.js
  packages/docs/pages/apps/vtiger-crm/triggers.md
Labels: enhancement

#1524 feat(vtiger-crm): add new todos trigger
  packages/backend/src/apps/vtiger-crm/triggers/index.js
  packages/backend/src/apps/vtiger-crm/triggers/new-todos/index.js
  packages/docs/pages/apps/vtiger-crm/triggers.md
Labels: enhancement

#1530 feat(vtiger-crm): add create contact action
  packages/backend/src/apps/vtiger-crm/actions/create-case/fields.js
  packages/backend/src/apps/vtiger-crm/actions/create-case/index.js
  packages/backend/src/apps/vtiger-crm/actions/create-contact/fields.js
  packages/backend/src/apps/vtiger-crm/actions/create-contact/index.js
  packages/backend/src/apps/vtiger-crm/actions/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-assets/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-case-options/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-contact-options/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-groups/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-products/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-service-contracts/index.js
  packages/docs/pages/apps/vtiger-crm/actions.md
Labels: enhancement

#1527 feat(vtiger-crm): add create todo action
  packages/backend/src/apps/vtiger-crm/actions/create-case/fields.js
  packages/backend/src/apps/vtiger-crm/actions/create-case/index.js
  packages/backend/src/apps/vtiger-crm/actions/create-contact/fields.js
  packages/backend/src/apps/vtiger-crm/actions/create-contact/index.js
  packages/backend/src/apps/vtiger-crm/actions/create-lead/fields.js
  packages/backend/src/apps/vtiger-crm/actions/create-lead/index.js
  packages/backend/src/apps/vtiger-crm/actions/create-opportunity/fields.js
  packages/backend/src/apps/vtiger-crm/actions/create-opportunity/index.js
  packages/backend/src/apps/vtiger-crm/actions/create-todo/fields.js
  packages/backend/src/apps/vtiger-crm/actions/create-todo/index.js
  packages/backend/src/apps/vtiger-crm/actions/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-assets/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-campaign-sources/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-case-options/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-contact-options/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-contacts/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-groups/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-lead-options/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-milestones/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-opportunity-options/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-organizations/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-products/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-projects/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-record-currencies/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-service-contracts/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-services/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-sla-names/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-tasks/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-todo-options/index.js
  packages/backend/src/apps/vtiger-crm/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/vtiger-crm/actions.md
Labels: enhancement

#1549 feat(ynab): add new transactions trigger
  packages/backend/src/apps/you-need-a-budget/triggers/category-overspent/index.js
  packages/backend/src/apps/you-need-a-budget/triggers/goal-completed/index.js
  packages/backend/src/apps/you-need-a-budget/triggers/index.js
  packages/backend/src/apps/you-need-a-budget/triggers/low-account-balance/index.js
  packages/backend/src/apps/you-need-a-budget/triggers/new-transactions/index.js
  packages/docs/pages/apps/you-need-a-budget/connection.md
  packages/docs/pages/apps/you-need-a-budget/triggers.md
Labels: enhancement

#1547 feat(ynab): add category overspent trigger
  packages/backend/src/apps/you-need-a-budget/triggers/category-overspent/index.js
  packages/backend/src/apps/you-need-a-budget/triggers/goal-completed/index.js
  packages/backend/src/apps/you-need-a-budget/triggers/index.js
  packages/backend/src/apps/you-need-a-budget/triggers/low-account-balance/index.js
  packages/backend/src/apps/you-need-a-budget/triggers/new-transactions/index.js
  packages/docs/pages/apps/you-need-a-budget/connection.md
  packages/docs/pages/apps/you-need-a-budget/triggers.md
Labels: enhancement

#1546 feat(ynab): add low account balance trigger
  packages/backend/src/apps/you-need-a-budget/index.js
  packages/backend/src/apps/you-need-a-budget/triggers/category-overspent/index.js
  packages/backend/src/apps/you-need-a-budget/triggers/goal-completed/index.js
  packages/backend/src/apps/you-need-a-budget/triggers/index.js
  packages/backend/src/apps/you-need-a-budget/triggers/low-account-balance/index.js
  packages/backend/src/apps/you-need-a-budget/triggers/new-transactions/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/you-need-a-budget/connection.md
  packages/docs/pages/apps/you-need-a-budget/triggers.md
  packages/docs/pages/guide/available-apps.md
Labels: enhancement

#1504 feat(vtiger-crm): add vtiger crm integration
  packages/backend/src/apps/vtiger-crm/actions/create-case/fields.js
  packages/backend/src/apps/vtiger-crm/actions/create-case/index.js
  packages/backend/src/apps/vtiger-crm/actions/create-contact/fields.js
  packages/backend/src/apps/vtiger-crm/actions/create-contact/index.js
  packages/backend/src/apps/vtiger-crm/actions/create-lead/fields.js
  packages/backend/src/apps/vtiger-crm/actions/create-lead/index.js
  packages/backend/src/apps/vtiger-crm/actions/create-opportunity/fields.js
  packages/backend/src/apps/vtiger-crm/actions/create-opportunity/index.js
  packages/backend/src/apps/vtiger-crm/actions/create-todo/fields.js
  packages/backend/src/apps/vtiger-crm/actions/create-todo/index.js
  packages/backend/src/apps/vtiger-crm/actions/index.js
  packages/backend/src/apps/vtiger-crm/assets/favicon.svg
  packages/backend/src/apps/vtiger-crm/auth/index.js
  packages/backend/src/apps/vtiger-crm/auth/is-still-verified.js
  packages/backend/src/apps/vtiger-crm/auth/verify-credentials.js
  packages/backend/src/apps/vtiger-crm/common/add-auth-header.js
  packages/backend/src/apps/vtiger-crm/common/set-base-url.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-assets/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-campaign-sources/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-case-options/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-contact-options/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-contacts/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-groups/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-lead-options/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-milestones/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-opportunity-options/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-organizations/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-products/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-projects/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-record-currencies/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-service-contracts/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-services/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-sla-names/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-tasks/index.js
  packages/backend/src/apps/vtiger-crm/dynamic-data/list-todo-options/index.js
  packages/backend/src/apps/vtiger-crm/index.js
  packages/backend/src/apps/vtiger-crm/triggers/index.js
  packages/backend/src/apps/vtiger-crm/triggers/new-cases/index.js
  packages/backend/src/apps/vtiger-crm/triggers/new-contacts/index.js
  packages/backend/src/apps/vtiger-crm/triggers/new-invoices/index.js
  packages/backend/src/apps/vtiger-crm/triggers/new-leads/index.js
  packages/backend/src/apps/vtiger-crm/triggers/new-opportunities/index.js
  packages/backend/src/apps/vtiger-crm/triggers/new-todos/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/vtiger-crm/actions.md
  packages/docs/pages/apps/vtiger-crm/connection.md
  packages/docs/pages/apps/vtiger-crm/triggers.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/vtiger-crm.svg
Labels: integration request, documentation-change

#1544 feat(ynab): add you need a budget app integration
  packages/backend/src/apps/you-need-a-budget/assets/favicon.svg
  packages/backend/src/apps/you-need-a-budget/auth/generate-auth-url.js
  packages/backend/src/apps/you-need-a-budget/auth/index.js
  packages/backend/src/apps/you-need-a-budget/auth/is-still-verified.js
  packages/backend/src/apps/you-need-a-budget/auth/refresh-token.js
  packages/backend/src/apps/you-need-a-budget/auth/verify-credentials.js
  packages/backend/src/apps/you-need-a-budget/common/add-auth-header.js
  packages/backend/src/apps/you-need-a-budget/common/get-current-user.js
  packages/backend/src/apps/you-need-a-budget/index.js
  packages/backend/src/apps/you-need-a-budget/triggers/category-overspent/index.js
  packages/backend/src/apps/you-need-a-budget/triggers/goal-completed/index.js
  packages/backend/src/apps/you-need-a-budget/triggers/index.js
  packages/backend/src/apps/you-need-a-budget/triggers/low-account-balance/index.js
  packages/backend/src/apps/you-need-a-budget/triggers/new-transactions/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/you-need-a-budget/connection.md
  packages/docs/pages/apps/you-need-a-budget/triggers.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/you-need-a-budget.svg
Labels: integration request, documentation-change

#1865 refactor(google-tasks/find-task): filter all tasks when finding a task
  packages/backend/src/apps/google-tasks/actions/find-task/index.js
  packages/docs/pages/apps/google-tasks/actions.md
Labels: enhancement, documentation-change

#1482 feat(disqus): add new flagged comments trigger
  packages/backend/src/apps/disqus/index.js
  packages/backend/src/apps/disqus/triggers/index.js
  packages/backend/src/apps/disqus/triggers/new-flagged-comments/index.js
  packages/docs/pages/apps/disqus/triggers.md
Labels: enhancement, documentation-change

#1873 fix(useDynamicData): send correct payload to API
  packages/web/src/hooks/useDynamicData.js
Labels: bug

#1882 feat: add no_proxy support in http(s) agents
  packages/backend/src/helpers/axios-with-proxy.js
Labels: enhancement

#1875 feat: support bi-directional backchannel SAML SLO
  .devcontainer/docker-compose.yml
  packages/backend/package.json
  packages/backend/src/db/migrations/20240430132947_add_saml_session_id_in_access_tokens.js
  packages/backend/src/helpers/create-auth-token-by-user-id.js
  packages/backend/src/helpers/passport.js
  packages/backend/src/models/access-token.js
  packages/backend/src/models/saml-auth-provider.ee.js
  yarn.lock
Labels: enhancement

#1554 feat(airtable): add create record action
  packages/backend/src/apps/airtable/actions/create-record/index.js
  packages/backend/src/apps/airtable/actions/index.js
  packages/backend/src/apps/airtable/dynamic-data/index.js
  packages/backend/src/apps/airtable/dynamic-data/list-bases/index.js
  packages/backend/src/apps/airtable/dynamic-data/list-tables/index.js
  packages/backend/src/apps/airtable/dynamic-fields/index.js
  packages/backend/src/apps/airtable/dynamic-fields/list-fields/index.js
  packages/backend/src/apps/airtable/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/airtable/actions.md
  packages/docs/pages/guide/available-apps.md
Labels: enhancement

#1555 feat(airtable): add find record action
  packages/backend/src/apps/airtable/actions/find-record/index.js
  packages/backend/src/apps/airtable/actions/index.js
  packages/backend/src/apps/airtable/dynamic-data/index.js
  packages/backend/src/apps/airtable/dynamic-data/list-table-fields/index.js
  packages/backend/src/apps/airtable/dynamic-data/list-table-views/index.js
  packages/docs/pages/apps/airtable/actions.md
Labels: enhancement

#1551 feat(airtable): add airtable integration
  packages/backend/src/apps/airtable/actions/create-record/index.js
  packages/backend/src/apps/airtable/actions/find-record/index.js
  packages/backend/src/apps/airtable/actions/index.js
  packages/backend/src/apps/airtable/assets/favicon.svg
  packages/backend/src/apps/airtable/auth/generate-auth-url.js
  packages/backend/src/apps/airtable/auth/index.js
  packages/backend/src/apps/airtable/auth/is-still-verified.js
  packages/backend/src/apps/airtable/auth/refresh-token.js
  packages/backend/src/apps/airtable/auth/verify-credentials.js
  packages/backend/src/apps/airtable/common/add-auth-header.js
  packages/backend/src/apps/airtable/common/auth-scope.js
  packages/backend/src/apps/airtable/common/get-current-user.js
  packages/backend/src/apps/airtable/dynamic-data/index.js
  packages/backend/src/apps/airtable/dynamic-data/list-bases/index.js
  packages/backend/src/apps/airtable/dynamic-data/list-table-fields/index.js
  packages/backend/src/apps/airtable/dynamic-data/list-table-views/index.js
  packages/backend/src/apps/airtable/dynamic-data/list-tables/index.js
  packages/backend/src/apps/airtable/dynamic-fields/index.js
  packages/backend/src/apps/airtable/dynamic-fields/list-fields/index.js
  packages/backend/src/apps/airtable/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/airtable/actions.md
  packages/docs/pages/apps/airtable/connection.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/airtable.svg
Labels: enhancement, documentation-change

#1556 feat(appwrite): add appwrite integration
  packages/backend/src/apps/appwrite/assets/favicon.svg
  packages/backend/src/apps/appwrite/auth/index.js
  packages/backend/src/apps/appwrite/auth/is-still-verified.js
  packages/backend/src/apps/appwrite/auth/verify-credentials.js
  packages/backend/src/apps/appwrite/common/add-auth-header.js
  packages/backend/src/apps/appwrite/common/set-base-url.js
  packages/backend/src/apps/appwrite/dynamic-data/index.js
  packages/backend/src/apps/appwrite/dynamic-data/list-collections/index.js
  packages/backend/src/apps/appwrite/dynamic-data/list-databases/index.js
  packages/backend/src/apps/appwrite/index.js
  packages/backend/src/apps/appwrite/triggers/index.js
  packages/backend/src/apps/appwrite/triggers/new-documents/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/appwrite/connection.md
  packages/docs/pages/apps/appwrite/triggers.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/appwrite.svg
Labels: integration request, documentation-change

#1890 feat(formatter/format-date-time): add unix to datetime support
  packages/backend/src/apps/formatter/actions/date-time/transformers/format-date-time.js
Labels: enhancement

#1900 release(v0.12.0): Update version to 0.12.0
  packages/backend/src/config/app.js
  packages/backend/src/controllers/api/v1/automatisch/version.test.js
Labels: release

#1907 fix(AdminApplicationSettings): handle undefined appConfig object
  packages/web/src/components/AdminApplicationSettings/index.jsx
Labels: bug
