Repository automatisch/automatisch, pull requests merged in 2024-07, with the labels that each got.

#1944 fix(user): make resetPasswordToken relevant fields nullable
  packages/backend/src/models/user.js
Labels: bug

#1945 fix: delete access token before hard deleting user
  packages/backend/src/workers/delete-user.ee.js
Labels: bug

#1955 docs: Adjust repository to the new packages structure
  packages/docs/pages/contributing/repository-structure.md
Labels: documentation-change

#1961 fix(datastore): stop undefined datastore entry throwing
  packages/backend/src/helpers/global-variable.js
Labels: bug

#1963 feat(formatter): add parse stringified json action
  packages/backend/src/apps/formatter/actions/text/index.js
  packages/backend/src/apps/formatter/actions/text/transformers/parse-stringified-json.js
  packages/backend/src/apps/formatter/dynamic-fields/list-transform-options/index.js
  packages/backend/src/apps/formatter/dynamic-fields/list-transform-options/text/parse-stringified-json.js
Labels: integration request

#1953 feat(Layout): support security icon in additional drawer link
  packages/backend/src/config/app.js
  packages/backend/src/controllers/api/v1/automatisch/config.ee.js
  packages/backend/src/controllers/api/v1/automatisch/config.ee.test.js
  packages/e2e-tests/package.json
  packages/web/src/components/Layout/index.jsx
  yarn.lock
Labels: enhancement

#1939 feat(salesforce): add find partially matching record action
  packages/backend/src/apps/salesforce/actions/find-partially-matching-record/index.js
  packages/backend/src/apps/salesforce/actions/index.js
  packages/docs/pages/apps/salesforce/actions.md
Labels: documentation-change

#1983 fix: safeguard redirect to /installation
  packages/web/src/routes.jsx
Labels: bug

#1975 feat(formatter/date-time): add get current timestamp action
  packages/backend/src/apps/formatter/actions/date-time/index.js
  packages/backend/src/apps/formatter/actions/date-time/transformers/get-current-timestamp.js
Labels: enhancement

#1977 feat(formatter/text): add create uuid action
  packages/backend/src/apps/formatter/actions/text/index.js
  packages/backend/src/apps/formatter/actions/text/transformers/create-uuid.js
Labels: enhancement

#1965 feat: add cryptography app with createHmac and createSignature actions
  packages/backend/src/apps/cryptography/actions/create-hmac/index.js
  packages/backend/src/apps/cryptography/actions/create-rsa-sha256-signature/index.js
  packages/backend/src/apps/cryptography/actions/index.js
  packages/backend/src/apps/cryptography/assets/favicon.svg
  packages/backend/src/apps/cryptography/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/cryptography/actions.md
  packages/docs/pages/apps/cryptography/connection.md
  packages/docs/pages/public/favicons/cryptography.svg
Labels: integration request, documentation-change

#1985 feat: use dynamic DOCS URL
  packages/backend/src/controllers/api/v1/automatisch/info.js
  packages/backend/src/controllers/api/v1/automatisch/info.test.js
  packages/backend/test/mocks/rest/api/v1/automatisch/info.js
  packages/web/src/components/WebhookUrlInfo/index.jsx
  packages/web/src/config/urls.js
  packages/web/src/hooks/useDocsUrl.js
Labels: enhancement

#1987 fix(webhook): add missing filter coverage
  packages/backend/src/helpers/webhook-handler-sync.js
Labels: bug

#1989 docs(appwrite): fix typos
  packages/docs/pages/apps/appwrite/connection.md
  packages/docs/pages/apps/appwrite/triggers.md
Labels: documentation-change

#1988 feat(formatter/text): add regex support in replace transfomer
  packages/backend/src/apps/formatter/actions/text/transformers/replace.js
  packages/backend/src/apps/formatter/dynamic-fields/index.js
  packages/backend/src/apps/formatter/dynamic-fields/list-replace-regex-options/index.js
  packages/backend/src/apps/formatter/dynamic-fields/list-transform-options/text/replace.js
Labels: enhancement

#1992 fix(axios): update order of interceptors
  packages/backend/src/helpers/axios-with-proxy.js
  packages/backend/src/helpers/axios-with-proxy.test.js
  packages/backend/src/helpers/http-client/index.js
Labels: bug

#1995 feat(http-client): support async beforeRequest interceptors
  packages/backend/src/helpers/axios-with-proxy.js
  packages/backend/src/helpers/axios-with-proxy.test.js
  packages/backend/src/helpers/http-client/index.js
Labels: enhancement

#1996 feat: support arrays in flows
  packages/backend/src/helpers/compute-parameters.js
  packages/web/src/components/PowerInput/data.js
Labels: enhancement
