Repository automatisch/automatisch, pull requests merged in 2024-08, with the labels that each got.

#2003 Update version to 0.13.0
  packages/backend/src/config/app.js
  packages/backend/src/controllers/api/v1/automatisch/version.test.js
Labels: release

#2002 feat: expose installationCompleted in GET /v1/automatisch/info
  packages/backend/src/controllers/api/v1/automatisch/info.js
  packages/backend/src/controllers/api/v1/automatisch/info.test.js
  packages/backend/test/mocks/rest/api/v1/automatisch/info.js
  packages/web/src/components/InstallationForm/index.jsx
  packages/web/src/routes.jsx
Labels: enhancement

#2006 fix(compute-parameters): use unparsed numbers
  packages/backend/src/helpers/compute-parameters.js
Labels: bug

#2007 Update version to 0.13.1
  packages/backend/src/config/app.js
  packages/backend/src/controllers/api/v1/automatisch/version.test.js
Labels: release

#1998 feat(code/run-javascript): run JS code and introduce monaco editor
  docker/Dockerfile
  packages/backend/package.json
  packages/backend/src/apps/code/actions/index.js
  packages/backend/src/apps/code/actions/run-javascript/index.js
  packages/backend/src/apps/code/assets/favicon.svg
  packages/backend/src/apps/code/index.js
  packages/web/package.json
  packages/web/src/components/CodeEditor/index.jsx
  packages/web/src/components/CodeEditor/style.js
  packages/web/src/components/InputCreator/index.jsx
  yarn.lock
Labels: enhancement

#2013 fix(github/create-issue): mark repo field as required
  packages/backend/src/apps/github/actions/create-issue/index.js
Labels: enhancement

#2012 feat(http-request/custom-request): expose response headers and status
  packages/backend/src/apps/http-request/actions/custom-request/index.js
Labels: enhancement

#2010 fix: mark steps incomplete when their parameters change
  packages/backend/src/graphql/mutations/update-step.js
Labels: bug

#2009 test(compute-parameters): write tests for different type of values
  packages/backend/src/helpers/compute-parameters.test.js
Labels: enhancement

#1561 feat(mailerlite): add mailerlite integration
  packages/backend/src/apps/mailerlite/assets/favicon.svg
  packages/backend/src/apps/mailerlite/auth/index.js
  packages/backend/src/apps/mailerlite/auth/is-still-verified.js
  packages/backend/src/apps/mailerlite/auth/verify-credentials.js
  packages/backend/src/apps/mailerlite/common/add-auth-header.js
  packages/backend/src/apps/mailerlite/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/mailerlite/connection.md
  packages/docs/pages/public/favicons/mailerlite.svg
Labels: integration request

#1563 feat(mailerlite): add subscriber created trigger
  packages/backend/src/apps/mailerlite/triggers/index.js
  packages/backend/src/apps/mailerlite/triggers/subscriber-created/index.js
  packages/docs/pages/apps/mailerlite/triggers.md
Labels: enhancement

#1564 feat(mailerlite): add subscriber unsubscribed trigger
  packages/backend/src/apps/mailerlite/triggers/index.js
  packages/backend/src/apps/mailerlite/triggers/subscriber-unsubscribed/index.js
  packages/docs/pages/apps/mailerlite/triggers.md
Labels: enhancement

#1565 feat(mailerlite): add campaign sent trigger
  packages/backend/src/apps/mailerlite/triggers/campaign-sent/index.js
  packages/backend/src/apps/mailerlite/triggers/index.js
  packages/docs/pages/apps/mailerlite/triggers.md
Labels: enhancement

#1461 feat(google-sheets): add find worksheet action
  packages/backend/src/apps/google-sheets/actions/find-worksheet/index.js
  packages/backend/src/apps/google-sheets/actions/index.js
  packages/backend/src/apps/google-sheets/dynamic-fields/index.js
  packages/backend/src/apps/google-sheets/dynamic-fields/list-create-worksheet-fields/index.js
  packages/docs/pages/apps/google-sheets/actions.md
Labels: enhancement, documentation-change

#1577 feat(jotform): add jotform integration
  packages/backend/src/apps/jotform/assets/favicon.svg
  packages/backend/src/apps/jotform/auth/index.js
  packages/backend/src/apps/jotform/auth/is-still-verified.js
  packages/backend/src/apps/jotform/auth/verify-credentials.js
  packages/backend/src/apps/jotform/common/add-auth-header.js
  packages/backend/src/apps/jotform/common/get-current-user.js
  packages/backend/src/apps/jotform/common/set-base-url.js
  packages/backend/src/apps/jotform/dynamic-data/index.js
  packages/backend/src/apps/jotform/dynamic-data/list-forms/index.js
  packages/backend/src/apps/jotform/index.js
  packages/backend/src/apps/jotform/triggers/index.js
  packages/backend/src/apps/jotform/triggers/new-submissions/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/jotform/connection.md
  packages/docs/pages/apps/jotform/triggers.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/jotform.svg
Labels: integration request, documentation-change

#1612 feat(clickup): add create list action
  packages/backend/src/apps/clickup/actions/create-list/index.js
  packages/backend/src/apps/clickup/actions/index.js
  packages/docs/pages/apps/clickup/actions.md
Labels: enhancement

#1611 feat(clickup): add create folder action
  packages/backend/src/apps/clickup/actions/create-folder/index.js
  packages/backend/src/apps/clickup/actions/create-list/index.js
  packages/backend/src/apps/clickup/actions/index.js
  packages/backend/src/apps/clickup/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/clickup/actions.md
Labels: enhancement

#1610 feat(clickup): add task changes trigger
  packages/backend/src/apps/clickup/actions/create-folder/index.js
  packages/backend/src/apps/clickup/actions/create-list/index.js
  packages/backend/src/apps/clickup/actions/index.js
  packages/backend/src/apps/clickup/index.js
  packages/backend/src/apps/clickup/triggers/index.js
  packages/backend/src/apps/clickup/triggers/task-changes/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/clickup/actions.md
  packages/docs/pages/apps/clickup/triggers.md
Labels: enhancement

#1599 feat(clickup): add new tasks trigger
  packages/backend/src/apps/clickup/actions/create-folder/index.js
  packages/backend/src/apps/clickup/actions/create-list/index.js
  packages/backend/src/apps/clickup/actions/index.js
  packages/backend/src/apps/clickup/dynamic-data/index.js
  packages/backend/src/apps/clickup/dynamic-data/list-lists/index.js
  packages/backend/src/apps/clickup/dynamic-data/list-tasks/index.js
  packages/backend/src/apps/clickup/index.js
  packages/backend/src/apps/clickup/triggers/index.js
  packages/backend/src/apps/clickup/triggers/new-tasks/index.js
  packages/backend/src/apps/clickup/triggers/task-changes/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/clickup/actions.md
  packages/docs/pages/apps/clickup/triggers.md
Labels: enhancement

#1598 feat(clickup): add new lists trigger
  packages/backend/src/apps/clickup/actions/create-folder/index.js
  packages/backend/src/apps/clickup/actions/create-list/index.js
  packages/backend/src/apps/clickup/actions/index.js
  packages/backend/src/apps/clickup/dynamic-data/index.js
  packages/backend/src/apps/clickup/dynamic-data/list-folders/index.js
  packages/backend/src/apps/clickup/dynamic-data/list-lists/index.js
  packages/backend/src/apps/clickup/dynamic-data/list-tasks/index.js
  packages/backend/src/apps/clickup/index.js
  packages/backend/src/apps/clickup/triggers/index.js
  packages/backend/src/apps/clickup/triggers/new-lists/index.js
  packages/backend/src/apps/clickup/triggers/new-tasks/index.js
  packages/backend/src/apps/clickup/triggers/task-changes/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/clickup/actions.md
  packages/docs/pages/apps/clickup/triggers.md
Labels: enhancement

#1594 feat(clickup): add clickup integration
  packages/backend/src/apps/clickup/actions/create-folder/index.js
  packages/backend/src/apps/clickup/actions/create-list/index.js
  packages/backend/src/apps/clickup/actions/index.js
  packages/backend/src/apps/clickup/assets/favicon.svg
  packages/backend/src/apps/clickup/auth/generate-auth-url.js
  packages/backend/src/apps/clickup/auth/index.js
  packages/backend/src/apps/clickup/auth/is-still-verified.js
  packages/backend/src/apps/clickup/auth/verify-credentials.js
  packages/backend/src/apps/clickup/common/add-auth-header.js
  packages/backend/src/apps/clickup/common/get-current-user.js
  packages/backend/src/apps/clickup/dynamic-data/index.js
  packages/backend/src/apps/clickup/dynamic-data/list-folders/index.js
  packages/backend/src/apps/clickup/dynamic-data/list-lists/index.js
  packages/backend/src/apps/clickup/dynamic-data/list-spaces/index.js
  packages/backend/src/apps/clickup/dynamic-data/list-tasks/index.js
  packages/backend/src/apps/clickup/dynamic-data/list-workspaces/index.js
  packages/backend/src/apps/clickup/index.js
  packages/backend/src/apps/clickup/triggers/index.js
  packages/backend/src/apps/clickup/triggers/new-folders/index.js
  packages/backend/src/apps/clickup/triggers/new-lists/index.js
  packages/backend/src/apps/clickup/triggers/new-tasks/index.js
  packages/backend/src/apps/clickup/triggers/updated-task/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/clickup/actions.md
  packages/docs/pages/apps/clickup/connection.md
  packages/docs/pages/apps/clickup/triggers.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/clickup.svg
Labels: integration request, documentation-change

#1617 feat(clickup): add find task by id action
  packages/backend/src/apps/clickup/actions/find-task-by-id/index.js
  packages/backend/src/apps/clickup/actions/index.js
  packages/backend/src/apps/clickup/dynamic-fields/index.js
  packages/backend/src/apps/clickup/dynamic-fields/use-custom-id/index.js
  packages/backend/src/apps/clickup/index.js
  packages/docs/pages/apps/clickup/actions.md
Labels: enhancement

#1615 feat(clickup): add create task action
  packages/backend/src/apps/clickup/actions/create-task/index.js
  packages/backend/src/apps/clickup/actions/find-task-by-id/index.js
  packages/backend/src/apps/clickup/actions/index.js
  packages/backend/src/apps/clickup/dynamic-data/index.js
  packages/backend/src/apps/clickup/dynamic-data/list-assignees/index.js
  packages/backend/src/apps/clickup/dynamic-data/list-statuses/index.js
  packages/backend/src/apps/clickup/dynamic-data/list-tags/index.js
  packages/backend/src/apps/clickup/dynamic-fields/index.js
  packages/backend/src/apps/clickup/dynamic-fields/use-custom-id/index.js
  packages/backend/src/apps/clickup/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/clickup/actions.md
Labels: enhancement, documentation-change

#2022 feat(PowerInput): support whole objects as variables
  packages/web/src/components/PowerInput/data.js
Labels: enhancement

#2026 refactor(compute-parameters): rewrite logic
  packages/backend/src/helpers/compute-parameters.js
Labels: enhancement

#2025 feat(compute-parameters): add valueType with parse option and string by default
  packages/backend/src/apps/code/actions/run-javascript/index.js
  packages/backend/src/helpers/compute-parameters.js
  packages/backend/src/helpers/compute-parameters.test.js
  packages/backend/src/models/step.js
  packages/backend/src/services/action.js
  packages/backend/test/factories/app.js
Labels: enhancement

#2041 fix: remove redundant asyncHandler wrapper
  packages/backend/src/routes/api/v1/admin/apps.ee.js
Labels: bug

#2047 fix(FlowAppIcons): fix crash when no steps exist
  packages/web/src/components/FlowAppIcons/index.jsx
Labels: bug

#2051 feat: incorporate NotAuthorized error in error handler
  packages/backend/src/errors/not-authorized.js
  packages/backend/src/helpers/authorization.js
  packages/backend/src/helpers/error-handler.js
  packages/backend/src/models/user.js
Labels: enhancement
