Repository automatisch/automatisch, pull requests merged in 2024-01, with the labels that each got.

#1498 feat(self-hosted-llm): add send prompt and send chat prompt actions
  packages/backend/src/apps/self-hosted-llm/actions/index.ts
  packages/backend/src/apps/self-hosted-llm/actions/send-chat-prompt/index.ts
  packages/backend/src/apps/self-hosted-llm/actions/send-prompt/index.ts
  packages/backend/src/apps/self-hosted-llm/assets/favicon.svg
  packages/backend/src/apps/self-hosted-llm/auth/index.ts
  packages/backend/src/apps/self-hosted-llm/auth/is-still-verified.ts
  packages/backend/src/apps/self-hosted-llm/auth/verify-credentials.ts
  packages/backend/src/apps/self-hosted-llm/common/add-auth-header.ts
  packages/backend/src/apps/self-hosted-llm/common/set-base-url.ts
  packages/backend/src/apps/self-hosted-llm/dynamic-data/index.ts
  packages/backend/src/apps/self-hosted-llm/dynamic-data/list-models/index.ts
  packages/backend/src/apps/self-hosted-llm/index.d.ts
  packages/backend/src/apps/self-hosted-llm/index.ts
Labels: integration request

#1557 feat(formatter): add string to base64 action
  packages/backend/src/apps/formatter/actions/text/index.js
  packages/backend/src/apps/formatter/actions/text/transformers/string-to-base64.js
  packages/backend/src/apps/formatter/dynamic-fields/list-transform-options/index.js
  packages/backend/src/apps/formatter/dynamic-fields/list-transform-options/text/string-to-base64.js
Labels: enhancement

#1559 feat(formatter): add base64 to string action
  packages/backend/src/apps/formatter/actions/text/index.js
  packages/backend/src/apps/formatter/actions/text/transformers/base64-to-string.js
  packages/backend/src/apps/formatter/dynamic-fields/list-transform-options/index.js
  packages/backend/src/apps/formatter/dynamic-fields/list-transform-options/text/base64-to-string.js
Labels: enhancement

#1570 fix: prevent registration on non-cloud
  packages/backend/src/graphql/mutations/register-user.ee.js
Labels: bug
