Repository automatisch/automatisch, pull requests merged in 2025-03, with the labels that each got.

#1820 feat(firebase): add find firebase realtime database record action
  packages/backend/src/apps/firebase/actions/find-firebase-realtime-database-record/index.js
  packages/backend/src/apps/firebase/actions/index.js
  packages/docs/pages/apps/firebase/actions.md
Labels: enhancement, documentation-change

#2389 fix(Footer): make footer optional
  packages/web/src/components/Layout/Footer/index.jsx
Labels: bug

#2383 fix: apps icons position
  packages/docs/pages/.vitepress/theme/custom.css
Labels: documentation-change

#2419 fix(flow-export): update all parameters
  packages/backend/src/helpers/export-flow.js
Labels: bug
