Repository automatisch/automatisch, pull requests merged in 2025-07, with the labels that each got.

#2555 feat(forms): add support for multiline and checkbox fields
  packages/web/src/pages/CreateForm/index.ee.jsx
  packages/web/src/pages/EditForm/index.ee.jsx
  packages/web/src/pages/FormFlow/index.ee.jsx
Labels: enhancement

#2533 feat: Frappe/ERPNext App
  packages/backend/src/apps/frappe/actions/create-doc/index.js
  packages/backend/src/apps/frappe/actions/delete-doc/index.js
  packages/backend/src/apps/frappe/actions/get-doc/index.js
  packages/backend/src/apps/frappe/actions/get-list/index.js
  packages/backend/src/apps/frappe/actions/index.js
  packages/backend/src/apps/frappe/actions/update-doc/index.js
  packages/backend/src/apps/frappe/assets/favicon.svg
  packages/backend/src/apps/frappe/auth/generate-auth-url.js
  packages/backend/src/apps/frappe/auth/index.js
  packages/backend/src/apps/frappe/auth/is-still-verified.js
  packages/backend/src/apps/frappe/auth/refresh-token.js
  packages/backend/src/apps/frappe/auth/verify-credentials.js
  packages/backend/src/apps/frappe/common/add-auth-header.js
  packages/backend/src/apps/frappe/common/constants.js
  packages/backend/src/apps/frappe/common/get-current-user.js
  packages/backend/src/apps/frappe/common/set-base-url.js
  packages/backend/src/apps/frappe/common/utils.js
  packages/backend/src/apps/frappe/dynamic-data/index.js
  packages/backend/src/apps/frappe/dynamic-data/list-doctypes/index.js
  packages/backend/src/apps/frappe/dynamic-fields/index.js
  packages/backend/src/apps/frappe/dynamic-fields/list-fields/index.js
  packages/backend/src/apps/frappe/index.js
  packages/backend/src/models/__snapshots__/app.test.js.snap
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/frappe/actions.md
  packages/docs/pages/apps/frappe/connection.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/frappe.svg
Labels: integration request, documentation-change

#2558 feat(forms): order form field types
  packages/web/src/pages/CreateForm/index.ee.jsx
  packages/web/src/pages/EditForm/index.ee.jsx
Labels: enhancement

#2565 feat(forms): support readonly and required fields
  packages/backend/src/controllers/internal/api/v1/flows/get-form.ee.test.js
  packages/backend/src/controllers/internal/api/v1/forms/create-form.ee.test.js
  packages/backend/src/controllers/internal/api/v1/forms/update-form.ee.test.js
  packages/backend/src/models/__snapshots__/form.ee.test.js.snap
  packages/backend/src/models/form.ee.js
  packages/backend/test/factories/form.js
  packages/web/src/components/FormEditor/FieldRow.jsx
  packages/web/src/components/FormEditor/index.ee.jsx
  packages/web/src/locales/en.json
  packages/web/src/pages/CreateForm/index.ee.jsx
  packages/web/src/pages/EditForm/index.ee.jsx
  packages/web/src/pages/FormFlow/index.ee.jsx
Labels: enhancement

#2566 feat(forms): support date, time and datetime fields
  packages/backend/src/controllers/internal/api/v1/forms/create-form.ee.test.js
  packages/backend/src/models/__snapshots__/form.ee.test.js.snap
  packages/backend/src/models/form.ee.js
  packages/web/src/components/FormEditor/FieldRow.jsx
  packages/web/src/locales/en.json
  packages/web/src/pages/FormFlow/index.ee.jsx
  packages/web/src/propTypes/propTypes.js
Labels: enhancement

#2567 feat(forms): introduce input validations
  packages/backend/src/controllers/internal/api/v1/forms/create-form.ee.test.js
  packages/backend/src/models/__snapshots__/form.ee.test.js.snap
  packages/backend/src/models/form.ee.js
  packages/web/src/components/FormEditor/FieldRow.jsx
  packages/web/src/locales/en.json
  packages/web/src/pages/EditForm/index.ee.jsx
  packages/web/src/pages/FormFlow/index.ee.jsx
  packages/web/src/propTypes/propTypes.js
Labels: enhancement

#2568 feat(forms/new-form-submission): support sync submissions
  packages/backend/src/apps/forms/triggers/new-form-submission/index.ee.js
Labels: enhancement

#2569 feat(forms): add respondWith action for custom form submission handling
  packages/backend/src/apps/forms/actions/index.ee.js
  packages/backend/src/apps/forms/actions/respond-with/index.ee.js
  packages/backend/src/apps/forms/index.ee.js
  packages/backend/src/apps/forms/triggers/new-form-submission/index.ee.js
  packages/backend/src/controllers/internal/api/v1/flows/get-form.ee.test.js
  packages/backend/src/helpers/webhook-handler-sync.js
  packages/backend/src/models/__snapshots__/form.ee.test.js.snap
  packages/backend/src/models/flow.js
  packages/backend/src/models/form.ee.js
  packages/backend/src/routes/webhooks.js
  packages/backend/src/serializers/public-form.ee.js
  packages/backend/src/serializers/public-form.ee.test.js
  packages/backend/test/mocks/rest/internal/api/v1/flows/get-form.js
  packages/web/src/components/FormEditor/FieldRow.jsx
  packages/web/src/hooks/useCreateFormSubmission.ee.js
  packages/web/src/pages/FormFlow/index.ee.jsx
Labels: enhancement

#2571 fix(admin-settings): correct enterprise permissions
  packages/backend/src/models/user.js
  packages/e2e-tests/fixtures/base-page.js
  packages/e2e-tests/tests/admin/manage-roles.spec.js
  packages/web/src/adminSettingsRoutes.jsx
  packages/web/src/components/AccountDropdownMenu/index.jsx
  packages/web/src/components/AdminGuard/index.jsx
  packages/web/src/components/AdminSettingsLayout/index.jsx
  packages/web/src/components/EnterpriseAdminGuard/index.ee.jsx
  packages/web/src/components/NotFound/index.jsx
  packages/web/src/helpers/api.js
  packages/web/src/hooks/useIsCurrentUserAdmin.js
  packages/web/src/hooks/useIsCurrentUserEnterpriseAdmin.js
  packages/web/src/pages/AdminApiTokens/index.ee.jsx
  packages/web/src/pages/AdminApplication/index.ee.jsx
  packages/web/src/pages/AdminApplications/index.ee.jsx
  packages/web/src/pages/AdminCreateTemplate/index.ee.jsx
  packages/web/src/pages/AdminTemplates/index.ee.jsx
  packages/web/src/pages/AdminUpdateTemplate/index.ee.jsx
  packages/web/src/pages/Authentication/RoleMappings.ee.jsx
  packages/web/src/pages/Authentication/RoleMappingsFieldsArray.ee.jsx
  packages/web/src/pages/Authentication/SamlConfiguration.ee.jsx
  packages/web/src/pages/Authentication/index.ee.jsx
  packages/web/src/pages/CreateUser/index.jsx
  packages/web/src/pages/EditUser/index.jsx
  packages/web/src/pages/UserInterface/index.ee.jsx
  packages/web/src/routes.jsx
Labels: bug

#2572 fix(web): redirect to login on 401
  packages/web/src/helpers/api.js
Labels: bug

#2573 feat(smtp/send-email): support html body
  packages/backend/src/apps/smtp/actions/send-email/index.js
Labels: enhancement

#2576 fix(smtp): remove unused SMTP from email in auth
  packages/backend/src/apps/smtp/auth/index.js
Labels: enhancement

#1629 feat(bigin-by-zoho-crm): add create event action
  packages/backend/src/apps/bigin-by-zoho-crm/actions/create-company/index.js
  packages/backend/src/apps/bigin-by-zoho-crm/actions/create-event/index.js
  packages/backend/src/apps/bigin-by-zoho-crm/actions/create-task/index.js
  packages/backend/src/apps/bigin-by-zoho-crm/actions/index.js
  packages/docs/pages/apps/bigin-by-zoho-crm/actions.md
Labels: enhancement

#1626 feat(bigin-by-zoho-crm): add new products trigger
  packages/backend/src/apps/bigin-by-zoho-crm/actions/create-company/index.js
  packages/backend/src/apps/bigin-by-zoho-crm/actions/create-contact/index.js
  packages/backend/src/apps/bigin-by-zoho-crm/actions/create-event/index.js
  packages/backend/src/apps/bigin-by-zoho-crm/actions/create-task/index.js
  packages/backend/src/apps/bigin-by-zoho-crm/actions/index.js
  packages/backend/src/apps/bigin-by-zoho-crm/dynamic-data/index.js
  packages/backend/src/apps/bigin-by-zoho-crm/dynamic-data/list-companies/index.js
  packages/backend/src/apps/bigin-by-zoho-crm/dynamic-data/list-contact-owners/index.js
  packages/backend/src/apps/bigin-by-zoho-crm/index.js
  packages/backend/src/apps/bigin-by-zoho-crm/triggers/index.js
  packages/backend/src/apps/bigin-by-zoho-crm/triggers/new-products/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/bigin-by-zoho-crm/actions.md
  packages/docs/pages/apps/bigin-by-zoho-crm/triggers.md
Labels: enhancement

#1623 feat(bigin-by-zoho-crm): add new companies trigger
  packages/backend/src/apps/bigin-by-zoho-crm/actions/create-company/index.js
  packages/backend/src/apps/bigin-by-zoho-crm/actions/create-contact/index.js
  packages/backend/src/apps/bigin-by-zoho-crm/actions/create-event/index.js
  packages/backend/src/apps/bigin-by-zoho-crm/actions/create-task/index.js
  packages/backend/src/apps/bigin-by-zoho-crm/actions/index.js
  packages/backend/src/apps/bigin-by-zoho-crm/dynamic-data/index.js
  packages/backend/src/apps/bigin-by-zoho-crm/dynamic-data/list-companies/index.js
  packages/backend/src/apps/bigin-by-zoho-crm/dynamic-data/list-contact-owners/index.js
  packages/backend/src/apps/bigin-by-zoho-crm/index.js
  packages/backend/src/apps/bigin-by-zoho-crm/triggers/index.js
  packages/backend/src/apps/bigin-by-zoho-crm/triggers/new-calls/index.js
  packages/backend/src/apps/bigin-by-zoho-crm/triggers/new-companies/index.js
  packages/backend/src/apps/bigin-by-zoho-crm/triggers/new-products/index.js
  packages/backend/src/apps/bigin-by-zoho-crm/triggers/new-tasks/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/bigin-by-zoho-crm/actions.md
  packages/docs/pages/apps/bigin-by-zoho-crm/triggers.md
Labels: enhancement

#2583 feat(github/triggers): add new pull request event trigger
  packages/backend/src/apps/github/triggers/index.js
  packages/backend/src/apps/github/triggers/new-pull-request-event/index.js
  packages/docs/pages/apps/github/triggers.md
Labels: integration request, documentation-change

#2584 feat(flow-editor): add continue without test option
  packages/web/src/components/TestSubstep/index.jsx
  packages/web/src/hooks/useContinueWithoutTest.js
  packages/web/src/hooks/useTestAndContinueStep.js
  packages/web/src/locales/en.json
Labels: enhancement

#2548 Fix #2071 notion database load
  packages/backend/src/apps/notion/dynamic-data/list-databases/index.js
  packages/backend/src/apps/notion/dynamic-data/list-parent-pages/index.js
Labels: bug

#1674 feat(pdf-monkey): add find document action
  packages/backend/src/apps/pdf-monkey/actions/find-document/index.js
  packages/backend/src/apps/pdf-monkey/actions/index.js
  packages/docs/pages/apps/pdf-monkey/actions.md
Labels: enhancement

#1673 feat(pdf-monkey): add delete document action
  packages/backend/src/apps/pdf-monkey/actions/delete-document/index.js
  packages/backend/src/apps/pdf-monkey/actions/find-document/index.js
  packages/backend/src/apps/pdf-monkey/actions/index.js
  packages/docs/pages/apps/pdf-monkey/actions.md
Labels: enhancement

#1459 feat(notion): add update database item action
  packages/backend/src/apps/notion/actions/index.js
  packages/backend/src/apps/notion/actions/update-database-item/index.js
  packages/backend/src/apps/notion/dynamic-data/index.js
  packages/backend/src/apps/notion/dynamic-data/list-database-items/index.js
  packages/backend/src/apps/notion/dynamic-data/list-databases/index.js
  packages/backend/src/apps/notion/dynamic-data/list-tags/index.js
  packages/backend/src/apps/notion/dynamic-fields/index.js
  packages/backend/src/apps/notion/dynamic-fields/list-database-properties/index.js
  packages/backend/src/apps/notion/index.js
  packages/docs/pages/apps/notion/actions.md
Labels: enhancement, documentation-change

#1633 feat(apps): add pdfmonkey integration
  packages/backend/src/apps/pdfmonkey/actions/delete-document/index.js
  packages/backend/src/apps/pdfmonkey/actions/find-document/index.js
  packages/backend/src/apps/pdfmonkey/actions/generate-document/index.js
  packages/backend/src/apps/pdfmonkey/actions/index.js
  packages/backend/src/apps/pdfmonkey/assets/favicon.svg
  packages/backend/src/apps/pdfmonkey/auth/index.js
  packages/backend/src/apps/pdfmonkey/auth/is-still-verified.js
  packages/backend/src/apps/pdfmonkey/auth/verify-credentials.js
  packages/backend/src/apps/pdfmonkey/common/add-auth-header.js
  packages/backend/src/apps/pdfmonkey/common/get-current-user.js
  packages/backend/src/apps/pdfmonkey/dynamic-data/index.js
  packages/backend/src/apps/pdfmonkey/dynamic-data/list-templates/index.js
  packages/backend/src/apps/pdfmonkey/dynamic-data/list-workspaces/index.js
  packages/backend/src/apps/pdfmonkey/dynamic-fields/index.js
  packages/backend/src/apps/pdfmonkey/dynamic-fields/list-document-data/index.js
  packages/backend/src/apps/pdfmonkey/index.js
  packages/backend/src/apps/pdfmonkey/triggers/documents-generated/index.js
  packages/backend/src/apps/pdfmonkey/triggers/index.js
  packages/backend/src/models/__snapshots__/app.test.js.snap
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/pdfmonkey/actions.md
  packages/docs/pages/apps/pdfmonkey/connection.md
  packages/docs/pages/apps/pdfmonkey/triggers.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/pdfmonkey.svg
Labels: integration request, documentation-change

#2587 feat(delete-connections): adapt endpoint to manage permissions
  packages/backend/src/controllers/internal/api/v1/connections/delete-connection.js
  packages/backend/src/controllers/internal/api/v1/connections/delete-connection.test.js
  packages/backend/src/models/user.js
Labels: enhancement

#2594 feat(forms): support array field type
  packages/backend/src/models/__snapshots__/form.ee.test.js.snap
  packages/backend/src/models/form.ee.js
  packages/backend/src/models/form.ee.test.js
  packages/web/src/components/DatePickerInput/index.jsx
  packages/web/src/components/FormEditor/FieldRow.jsx
  packages/web/src/components/FormEditor/index.ee.jsx
  packages/web/src/helpers/addKeyByNameInArrayOfObjects.js
  packages/web/src/index.jsx
  packages/web/src/locales/en.json
  packages/web/src/pages/FormFlow/components/ArrayField/ArrayFieldEntry.jsx
  packages/web/src/pages/FormFlow/components/ArrayField/index.jsx
  packages/web/src/pages/FormFlow/components/CheckboxField.jsx
  packages/web/src/pages/FormFlow/components/DateField.jsx
  packages/web/src/pages/FormFlow/components/DateTimeField.jsx
  packages/web/src/pages/FormFlow/components/DropdownField.jsx
  packages/web/src/pages/FormFlow/components/MultilineField.jsx
  packages/web/src/pages/FormFlow/components/StringField.jsx
  packages/web/src/pages/FormFlow/components/TimeField.jsx
  packages/web/src/pages/FormFlow/index.ee.jsx
Labels: enhancement

#1886 feat(changedetection): add changed watch trigger
  packages/backend/src/apps/changedetection/dynamic-data/index.js
  packages/backend/src/apps/changedetection/dynamic-data/list-watches/index.js
  packages/backend/src/apps/changedetection/index.js
  packages/backend/src/apps/changedetection/triggers/changed-watch/index.js
  packages/backend/src/apps/changedetection/triggers/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/changedetection/triggers.md
Labels: enhancement, documentation-change

#1881 feat(apps): add changedetection integration
  packages/backend/src/apps/changedetection/actions/create-watch/index.js
  packages/backend/src/apps/changedetection/actions/delete-watch/index.js
  packages/backend/src/apps/changedetection/actions/index.js
  packages/backend/src/apps/changedetection/assets/favicon.svg
  packages/backend/src/apps/changedetection/auth/index.js
  packages/backend/src/apps/changedetection/auth/is-still-verified.js
  packages/backend/src/apps/changedetection/auth/verify-credentials.js
  packages/backend/src/apps/changedetection/common/add-auth-header.js
  packages/backend/src/apps/changedetection/common/set-base-url.js
  packages/backend/src/apps/changedetection/dynamic-data/index.js
  packages/backend/src/apps/changedetection/dynamic-data/list-watches/index.js
  packages/backend/src/apps/changedetection/index.js
  packages/backend/src/apps/changedetection/triggers/changed-watch/index.js
  packages/backend/src/apps/changedetection/triggers/index.js
  packages/backend/src/models/__snapshots__/app.test.js.snap
  packages/docs/package.json
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/changedetection/actions.md
  packages/docs/pages/apps/changedetection/connection.md
  packages/docs/pages/apps/changedetection/triggers.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/changedetection.svg
Labels: integration request, documentation-change

#1894 feat(firefly-iii): add transaction deleted trigger
  packages/backend/src/apps/firefly-iii/triggers/index.js
  packages/backend/src/apps/firefly-iii/triggers/transaction-deleted/index.js
Labels: enhancement

#1906 feat(wordpress): add delete post action
  packages/backend/src/apps/wordpress/actions/delete-post/index.js
  packages/backend/src/apps/wordpress/actions/index.js
  packages/backend/src/apps/wordpress/dynamic-data/list-posts/index.js
  packages/docs/pages/apps/wordpress/actions.md
Labels: enhancement, documentation-change

#1914 feat(ntfy/send-message): add priority and tag fields
  packages/backend/src/apps/ntfy/actions/send-message/index.js
Labels: enhancement

#1908 feat(libretranslate): add libretranslate integration
  packages/backend/src/apps/libretranslate/actions/detect-language/index.js
  packages/backend/src/apps/libretranslate/actions/index.js
  packages/backend/src/apps/libretranslate/actions/translate-text/index.js
  packages/backend/src/apps/libretranslate/assets/favicon.svg
  packages/backend/src/apps/libretranslate/auth/index.js
  packages/backend/src/apps/libretranslate/auth/is-still-verified.js
  packages/backend/src/apps/libretranslate/auth/verify-credentials.js
  packages/backend/src/apps/libretranslate/common/add-api-key.js
  packages/backend/src/apps/libretranslate/common/set-base-url.js
  packages/backend/src/apps/libretranslate/dynamic-data/index.js
  packages/backend/src/apps/libretranslate/dynamic-data/list-languages/index.js
  packages/backend/src/apps/libretranslate/index.js
  packages/backend/src/models/__snapshots__/app.test.js.snap
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/libretranslate/actions.md
  packages/docs/pages/apps/libretranslate/connection.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/libretranslate.svg
Labels: integration request, documentation-change

#1921 feat(asana): add find task in project action
  packages/backend/src/apps/asana/actions/find-task-in-project/index.js
  packages/backend/src/apps/asana/actions/index.js
  packages/docs/pages/apps/asana/actions.md
Labels: enhancement, documentation-change

#1920 feat(asana): add find project action
  packages/backend/src/apps/asana/actions/find-project/index.js
  packages/backend/src/apps/asana/actions/find-task-in-project/index.js
  packages/backend/src/apps/asana/actions/index.js
  packages/docs/pages/apps/asana/actions.md
Labels: enhancement, documentation-change

#1918 feat(asana): add create task action
  packages/backend/src/apps/asana/actions/create-project/index.js
  packages/backend/src/apps/asana/actions/create-task/index.js
  packages/backend/src/apps/asana/actions/find-project/index.js
  packages/backend/src/apps/asana/actions/find-task-in-project/index.js
  packages/backend/src/apps/asana/actions/index.js
  packages/backend/src/apps/asana/dynamic-data/index.js
  packages/backend/src/apps/asana/dynamic-data/list-projects/index.js
  packages/backend/src/apps/asana/dynamic-data/list-sections/index.js
  packages/backend/src/apps/asana/dynamic-data/list-tags/index.js
  packages/backend/src/apps/asana/dynamic-data/list-teams/index.js
  packages/backend/src/apps/asana/dynamic-data/list-users/index.js
  packages/backend/src/apps/asana/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/asana/actions.md
Labels: enhancement, documentation-change

#1915 feat(asana): add asana integration
  packages/backend/src/apps/asana/actions/create-project/index.js
  packages/backend/src/apps/asana/actions/create-task/index.js
  packages/backend/src/apps/asana/actions/find-project/index.js
  packages/backend/src/apps/asana/actions/find-task-in-project/index.js
  packages/backend/src/apps/asana/actions/index.js
  packages/backend/src/apps/asana/assets/favicon.svg
  packages/backend/src/apps/asana/auth/generate-auth-url.js
  packages/backend/src/apps/asana/auth/index.js
  packages/backend/src/apps/asana/auth/is-still-verified.js
  packages/backend/src/apps/asana/auth/refresh-token.js
  packages/backend/src/apps/asana/auth/verify-credentials.js
  packages/backend/src/apps/asana/common/add-auth-header.js
  packages/backend/src/apps/asana/common/get-current-user.js
  packages/backend/src/apps/asana/dynamic-data/index.js
  packages/backend/src/apps/asana/dynamic-data/list-projects/index.js
  packages/backend/src/apps/asana/dynamic-data/list-sections/index.js
  packages/backend/src/apps/asana/dynamic-data/list-tags/index.js
  packages/backend/src/apps/asana/dynamic-data/list-teams/index.js
  packages/backend/src/apps/asana/dynamic-data/list-users/index.js
  packages/backend/src/apps/asana/dynamic-data/list-workspaces/index.js
  packages/backend/src/apps/asana/index.js
  packages/backend/src/models/__snapshots__/app.test.js.snap
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/asana/actions.md
  packages/docs/pages/apps/asana/connection.md
  packages/docs/pages/public/favicons/asana.svg
Labels: integration request, documentation-change

#1928 feat(eventbrite): add publish event action
  packages/backend/src/apps/eventbrite/actions/index.js
  packages/backend/src/apps/eventbrite/actions/publish-event/index.js
  packages/backend/src/apps/eventbrite/dynamic-data/list-events/index.js
  packages/docs/pages/apps/eventbrite/actions.md
Labels: enhancement, documentation-change

#1922 feat(eventbrite): add eventbrite integration
  packages/backend/src/apps/eventbrite/actions/create-event/index.js
  packages/backend/src/apps/eventbrite/actions/index.js
  packages/backend/src/apps/eventbrite/actions/publish-event/index.js
  packages/backend/src/apps/eventbrite/assets/favicon.svg
  packages/backend/src/apps/eventbrite/auth/generate-auth-url.js
  packages/backend/src/apps/eventbrite/auth/index.js
  packages/backend/src/apps/eventbrite/auth/is-still-verified.js
  packages/backend/src/apps/eventbrite/auth/verify-credentials.js
  packages/backend/src/apps/eventbrite/common/add-auth-header.js
  packages/backend/src/apps/eventbrite/common/get-current-user.js
  packages/backend/src/apps/eventbrite/dynamic-data/index.js
  packages/backend/src/apps/eventbrite/dynamic-data/list-currency/index.js
  packages/backend/src/apps/eventbrite/dynamic-data/list-events/index.js
  packages/backend/src/apps/eventbrite/dynamic-data/list-organizations/index.js
  packages/backend/src/apps/eventbrite/dynamic-data/list-venues/index.js
  packages/backend/src/apps/eventbrite/index.js
  packages/backend/src/apps/eventbrite/triggers/index.js
  packages/backend/src/apps/eventbrite/triggers/new-attendee-check-in/index.js
  packages/backend/src/apps/eventbrite/triggers/new-attendee-registered/index.js
  packages/backend/src/apps/eventbrite/triggers/new-events/index.js
  packages/backend/src/apps/eventbrite/triggers/updated-attendee/index.js
  packages/backend/src/models/__snapshots__/app.test.js.snap
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/eventbrite/actions.md
  packages/docs/pages/apps/eventbrite/connection.md
  packages/docs/pages/apps/eventbrite/triggers.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/eventbrite.svg
Labels: integration request, documentation-change

#1935 feat(surveymonkey): add create contact action
  packages/backend/src/apps/surveymonkey/actions/create-contact/index.js
  packages/backend/src/apps/surveymonkey/actions/index.js
  packages/backend/src/apps/surveymonkey/dynamic-data/index.js
  packages/backend/src/apps/surveymonkey/dynamic-data/list-contact-lists/index.js
  packages/backend/src/apps/surveymonkey/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/surveymonkey/actions.md
Labels: enhancement, documentation-change

#1930 feat(surveymonkey): add surveymonkey integration
  packages/backend/src/apps/surveymonkey/actions/create-contact/index.js
  packages/backend/src/apps/surveymonkey/actions/index.js
  packages/backend/src/apps/surveymonkey/assets/favicon.svg
  packages/backend/src/apps/surveymonkey/auth/generate-auth-url.js
  packages/backend/src/apps/surveymonkey/auth/index.js
  packages/backend/src/apps/surveymonkey/auth/is-still-verified.js
  packages/backend/src/apps/surveymonkey/auth/verify-credentials.js
  packages/backend/src/apps/surveymonkey/common/add-auth-header.js
  packages/backend/src/apps/surveymonkey/common/get-current-user.js
  packages/backend/src/apps/surveymonkey/common/set-base-url.js
  packages/backend/src/apps/surveymonkey/dynamic-data/index.js
  packages/backend/src/apps/surveymonkey/dynamic-data/list-contact-lists/index.js
  packages/backend/src/apps/surveymonkey/dynamic-data/list-surveys/index.js
  packages/backend/src/apps/surveymonkey/index.js
  packages/backend/src/apps/surveymonkey/triggers/index.js
  packages/backend/src/apps/surveymonkey/triggers/new-response-notification/index.js
  packages/backend/src/models/__snapshots__/app.test.js.snap
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/surveymonkey/actions.md
  packages/docs/pages/apps/surveymonkey/connection.md
  packages/docs/pages/apps/surveymonkey/triggers.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/surveymonkey.svg
Labels: integration request, documentation-change

#2597 feat(apps): add common API request action
  packages/backend/src/helpers/common-api-request-action.js
  packages/backend/src/helpers/get-app.js
Labels: enhancement, integration request

#2601 feat(apps): support private apps
  .gitignore
  packages/backend/src/helpers/app-assets-handler.js
  packages/backend/src/helpers/get-app.js
  packages/backend/src/models/app.js
  packages/backend/src/models/app.test.js
  packages/backend/vitest.config.js
Labels: enhancement

#2610 fix(docs): add missing VITE_ prefix to environment variable
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/.vitepress/theme/index.js
  packages/docs/pages/api-docs/[operationId].paths.js
Labels: bug

#2611 feat: Use swagger ui json file also from env variable
  packages/docs/pages/.vitepress/theme/components/SwaggerUI.vue
Labels: documentation-change
