Repository automatisch/automatisch, pull requests merged in 2025-02, with the labels that each got.

#2313 feat(brave-search): add app with web search action
  packages/backend/src/apps/brave-search/actions/index.js
  packages/backend/src/apps/brave-search/actions/web-search/index.js
  packages/backend/src/apps/brave-search/assets/favicon.svg
  packages/backend/src/apps/brave-search/auth/index.js
  packages/backend/src/apps/brave-search/auth/is-still-verified.js
  packages/backend/src/apps/brave-search/auth/verify-credentials.js
  packages/backend/src/apps/brave-search/common/add-accept-header.js
  packages/backend/src/apps/brave-search/common/add-auth-header.js
  packages/backend/src/apps/brave-search/dynamic-data/index.js
  packages/backend/src/apps/brave-search/dynamic-data/list-models/index.js
  packages/backend/src/apps/brave-search/index.js
  packages/backend/src/models/__snapshots__/app.test.js.snap
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/brave-search/actions.md
  packages/docs/pages/apps/brave-search/connection.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/brave-search.svg
Labels: integration request, documentation-change

#2328 test(user): fix user trial period
  packages/backend/src/models/user.test.js
Labels: bug

#2329 chore: add missing doc links
  packages/docs/pages/guide/available-apps.md
Labels: documentation-change

#1880 feat(monday): add new users trigger
  packages/backend/src/apps/monday/triggers/index.js
  packages/backend/src/apps/monday/triggers/new-boards/index.js
  packages/backend/src/apps/monday/triggers/new-users/index.js
  packages/backend/src/models/__snapshots__/app.test.js.snap
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/monday/triggers.md
Labels: enhancement, documentation-change

#1879 feat(monday): add create column action
  packages/backend/src/apps/monday/actions/create-column/index.js
  packages/backend/src/apps/monday/actions/index.js
  packages/backend/src/apps/monday/dynamic-data/list-boards/index.js
  packages/backend/src/apps/monday/triggers/index.js
  packages/backend/src/apps/monday/triggers/new-boards/index.js
  packages/backend/src/apps/monday/triggers/new-users/index.js
  packages/backend/src/models/__snapshots__/app.test.js.snap
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/monday/actions.md
  packages/docs/pages/apps/monday/triggers.md
Labels: enhancement, documentation-change

#1878 feat(monday): add create item action
  packages/backend/src/apps/monday/actions/create-column/index.js
  packages/backend/src/apps/monday/actions/create-item/index.js
  packages/backend/src/apps/monday/actions/index.js
  packages/backend/src/apps/monday/dynamic-data/index.js
  packages/backend/src/apps/monday/dynamic-data/list-boards/index.js
  packages/backend/src/apps/monday/dynamic-data/list-groups/index.js
  packages/backend/src/apps/monday/index.js
  packages/backend/src/apps/monday/triggers/index.js
  packages/backend/src/apps/monday/triggers/new-boards/index.js
  packages/backend/src/apps/monday/triggers/new-users/index.js
  packages/backend/src/models/__snapshots__/app.test.js.snap
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/monday/actions.md
  packages/docs/pages/apps/monday/triggers.md
Labels: enhancement, documentation-change

#1869 feat(monday): add create board action
  packages/backend/src/apps/monday/actions/create-board/index.js
  packages/backend/src/apps/monday/actions/create-column/index.js
  packages/backend/src/apps/monday/actions/create-item/index.js
  packages/backend/src/apps/monday/actions/index.js
  packages/backend/src/apps/monday/dynamic-data/index.js
  packages/backend/src/apps/monday/dynamic-data/list-boards/index.js
  packages/backend/src/apps/monday/dynamic-data/list-groups/index.js
  packages/backend/src/apps/monday/index.js
  packages/backend/src/apps/monday/triggers/index.js
  packages/backend/src/apps/monday/triggers/new-boards/index.js
  packages/backend/src/apps/monday/triggers/new-users/index.js
  packages/backend/src/models/__snapshots__/app.test.js.snap
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/monday/actions.md
  packages/docs/pages/apps/monday/triggers.md
Labels: enhancement, documentation-change

#1856 feat(monday): add new boards trigger
  packages/backend/src/apps/monday/actions/create-board/index.js
  packages/backend/src/apps/monday/actions/create-column/index.js
  packages/backend/src/apps/monday/actions/create-item/index.js
  packages/backend/src/apps/monday/actions/index.js
  packages/backend/src/apps/monday/dynamic-data/index.js
  packages/backend/src/apps/monday/dynamic-data/list-boards/index.js
  packages/backend/src/apps/monday/dynamic-data/list-groups/index.js
  packages/backend/src/apps/monday/index.js
  packages/backend/src/apps/monday/triggers/index.js
  packages/backend/src/apps/monday/triggers/new-boards/index.js
  packages/backend/src/apps/monday/triggers/new-users/index.js
  packages/backend/src/models/__snapshots__/app.test.js.snap
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/monday/actions.md
  packages/docs/pages/apps/monday/triggers.md
  packages/docs/pages/guide/available-apps.md
Labels: enhancement, documentation-change

#1855 feat(monday): add monday integration
  packages/backend/src/apps/monday/actions/create-board/index.js
  packages/backend/src/apps/monday/actions/create-column/index.js
  packages/backend/src/apps/monday/actions/create-item/index.js
  packages/backend/src/apps/monday/actions/index.js
  packages/backend/src/apps/monday/assets/favicon.svg
  packages/backend/src/apps/monday/auth/index.js
  packages/backend/src/apps/monday/auth/is-still-verified.js
  packages/backend/src/apps/monday/auth/verify-credentials.js
  packages/backend/src/apps/monday/common/add-auth-header.js
  packages/backend/src/apps/monday/dynamic-data/index.js
  packages/backend/src/apps/monday/dynamic-data/list-boards/index.js
  packages/backend/src/apps/monday/dynamic-data/list-groups/index.js
  packages/backend/src/apps/monday/index.js
  packages/backend/src/apps/monday/triggers/index.js
  packages/backend/src/apps/monday/triggers/new-boards/index.js
  packages/backend/src/apps/monday/triggers/new-users/index.js
  packages/backend/src/models/__snapshots__/app.test.js.snap
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/monday/actions.md
  packages/docs/pages/apps/monday/connection.md
  packages/docs/pages/apps/monday/triggers.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/monday.svg
Labels: integration request, documentation-change

#1899 feat(bluesky): add reply to post action
  packages/backend/src/apps/bluesky/actions/index.js
  packages/backend/src/apps/bluesky/actions/reply-to-post/index.js
  packages/backend/src/apps/bluesky/common/get-reply-refs.js
  packages/docs/pages/apps/bluesky/actions.md
Labels: enhancement, documentation-change

#1898 feat(bluesky): add search post by url action
  packages/backend/src/apps/bluesky/actions/index.js
  packages/backend/src/apps/bluesky/actions/reply-to-post/index.js
  packages/backend/src/apps/bluesky/actions/search-post-by-url/index.js
  packages/backend/src/apps/bluesky/common/get-reply-refs.js
  packages/docs/pages/apps/bluesky/actions.md
Labels: enhancement, documentation-change

#1897 feat(bluesky): add create post action
  packages/backend/package.json
  packages/backend/src/apps/bluesky/actions/create-post/index.js
  packages/backend/src/apps/bluesky/actions/index.js
  packages/backend/src/apps/bluesky/actions/reply-to-post/index.js
  packages/backend/src/apps/bluesky/actions/search-post-by-url/index.js
  packages/backend/src/apps/bluesky/common/get-reply-refs.js
  packages/backend/src/apps/bluesky/index.js
  packages/backend/yarn.lock
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/bluesky/actions.md
  packages/docs/pages/guide/available-apps.md
Labels: enhancement, documentation-change

#1831 feat(gmail): add send to trash action
  packages/backend/src/apps/gmail/actions/index.js
  packages/backend/src/apps/gmail/actions/send-to-trash/index.js
  packages/backend/src/apps/gmail/actions/star-email/index.js
  packages/backend/src/apps/gmail/auth/refresh-token.js
  packages/backend/src/apps/gmail/common/add-auth-header.js
  packages/backend/src/apps/gmail/dynamic-data/index.js
  packages/backend/src/apps/gmail/dynamic-data/list-messages/index.js
  packages/docs/pages/apps/gmail/actions.md
Labels: enhancement, documentation-change

#1830 feat(gmail): add create draft action
  packages/backend/src/apps/gmail/actions/create-draft/index.js
  packages/backend/src/apps/gmail/actions/index.js
  packages/backend/src/apps/gmail/actions/send-to-trash/index.js
  packages/backend/src/apps/gmail/actions/star-email/index.js
  packages/backend/src/apps/gmail/auth/refresh-token.js
  packages/backend/src/apps/gmail/common/add-auth-header.js
  packages/backend/src/apps/gmail/dynamic-data/index.js
  packages/backend/src/apps/gmail/dynamic-data/list-messages/index.js
  packages/docs/pages/apps/gmail/actions.md
Labels: enhancement, documentation-change

#1829 feat(gmail): add reply to email action
  packages/backend/src/apps/gmail/actions/create-draft/index.js
  packages/backend/src/apps/gmail/actions/index.js
  packages/backend/src/apps/gmail/actions/reply-to-email/index.js
  packages/backend/src/apps/gmail/actions/send-to-trash/index.js
  packages/backend/src/apps/gmail/actions/star-email/index.js
  packages/backend/src/apps/gmail/auth/refresh-token.js
  packages/backend/src/apps/gmail/common/add-auth-header.js
  packages/backend/src/apps/gmail/dynamic-data/index.js
  packages/backend/src/apps/gmail/dynamic-data/list-messages/index.js
  packages/backend/src/apps/gmail/dynamic-data/list-threads/index.js
  packages/docs/pages/apps/gmail/actions.md
Labels: enhancement, documentation-change

#1826 feat(gmail): add send email action
  packages/backend/src/apps/gmail/actions/create-draft/index.js
  packages/backend/src/apps/gmail/actions/index.js
  packages/backend/src/apps/gmail/actions/reply-to-email/index.js
  packages/backend/src/apps/gmail/actions/send-email/index.js
  packages/backend/src/apps/gmail/actions/send-to-trash/index.js
  packages/backend/src/apps/gmail/actions/star-email/index.js
  packages/backend/src/apps/gmail/auth/refresh-token.js
  packages/backend/src/apps/gmail/common/add-auth-header.js
  packages/backend/src/apps/gmail/dynamic-data/index.js
  packages/backend/src/apps/gmail/dynamic-data/list-emails/index.js
  packages/backend/src/apps/gmail/dynamic-data/list-messages/index.js
  packages/backend/src/apps/gmail/dynamic-data/list-signatures/index.js
  packages/backend/src/apps/gmail/dynamic-data/list-threads/index.js
  packages/backend/src/apps/gmail/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/gmail/actions.md
Labels: enhancement, documentation-change

#1824 feat(gmail): add new emails trigger
  packages/backend/src/apps/gmail/actions/create-draft/index.js
  packages/backend/src/apps/gmail/actions/index.js
  packages/backend/src/apps/gmail/actions/reply-to-email/index.js
  packages/backend/src/apps/gmail/actions/send-email/index.js
  packages/backend/src/apps/gmail/actions/send-to-trash/index.js
  packages/backend/src/apps/gmail/actions/star-email/index.js
  packages/backend/src/apps/gmail/auth/refresh-token.js
  packages/backend/src/apps/gmail/auth/verify-credentials.js
  packages/backend/src/apps/gmail/common/add-auth-header.js
  packages/backend/src/apps/gmail/dynamic-data/index.js
  packages/backend/src/apps/gmail/dynamic-data/list-emails/index.js
  packages/backend/src/apps/gmail/dynamic-data/list-labels/index.js
  packages/backend/src/apps/gmail/dynamic-data/list-messages/index.js
  packages/backend/src/apps/gmail/dynamic-data/list-signatures/index.js
  packages/backend/src/apps/gmail/dynamic-data/list-threads/index.js
  packages/backend/src/apps/gmail/index.js
  packages/backend/src/apps/gmail/triggers/index.js
  packages/backend/src/apps/gmail/triggers/new-emails/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/gmail/actions.md
  packages/docs/pages/apps/gmail/triggers.md
  packages/docs/pages/guide/available-apps.md
Labels: enhancement, documentation-change

#1854 feat(gitea): add new pull requests trigger
  packages/backend/src/apps/gitea/triggers/index.js
  packages/backend/src/apps/gitea/triggers/new-pull-requests/index.js
  packages/docs/pages/apps/gitea/triggers.md
Labels: enhancement, documentation-change

#1853 feat(gitea): add create issue action
  packages/backend/src/apps/gitea/actions/create-issue/index.js
  packages/backend/src/apps/gitea/actions/index.js
  packages/backend/src/apps/gitea/dynamic-data/list-labels/index.js
  packages/backend/src/apps/gitea/index.js
  packages/backend/src/apps/gitea/triggers/index.js
  packages/backend/src/apps/gitea/triggers/new-pull-requests/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/gitea/actions.md
  packages/docs/pages/apps/gitea/triggers.md
Labels: enhancement, documentation-change

#1852 feat(gitea): add new issues trigger
  packages/backend/src/apps/gitea/actions/create-issue/index.js
  packages/backend/src/apps/gitea/actions/index.js
  packages/backend/src/apps/gitea/dynamic-data/index.js
  packages/backend/src/apps/gitea/dynamic-data/list-labels/index.js
  packages/backend/src/apps/gitea/index.js
  packages/backend/src/apps/gitea/triggers/index.js
  packages/backend/src/apps/gitea/triggers/new-issues/index.js
  packages/backend/src/apps/gitea/triggers/new-pull-requests/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/gitea/actions.md
  packages/docs/pages/apps/gitea/triggers.md
Labels: enhancement, documentation-change

#1850 feat(gitea): add new watchers trigger
  packages/backend/src/apps/gitea/actions/create-issue/index.js
  packages/backend/src/apps/gitea/actions/index.js
  packages/backend/src/apps/gitea/dynamic-data/index.js
  packages/backend/src/apps/gitea/dynamic-data/list-labels/index.js
  packages/backend/src/apps/gitea/index.js
  packages/backend/src/apps/gitea/triggers/index.js
  packages/backend/src/apps/gitea/triggers/new-issues/index.js
  packages/backend/src/apps/gitea/triggers/new-pull-requests/index.js
  packages/backend/src/apps/gitea/triggers/new-watchers/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/gitea/actions.md
  packages/docs/pages/apps/gitea/triggers.md
Labels: enhancement, documentation-change

#1849 feat(gitea): add new stargazers trigger
  packages/backend/src/apps/gitea/actions/create-issue/index.js
  packages/backend/src/apps/gitea/actions/index.js
  packages/backend/src/apps/gitea/dynamic-data/index.js
  packages/backend/src/apps/gitea/dynamic-data/list-labels/index.js
  packages/backend/src/apps/gitea/dynamic-data/list-repos/index.js
  packages/backend/src/apps/gitea/index.js
  packages/backend/src/apps/gitea/triggers/index.js
  packages/backend/src/apps/gitea/triggers/new-issues/index.js
  packages/backend/src/apps/gitea/triggers/new-pull-requests/index.js
  packages/backend/src/apps/gitea/triggers/new-stargazers/index.js
  packages/backend/src/apps/gitea/triggers/new-watchers/index.js
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/gitea/actions.md
  packages/docs/pages/apps/gitea/triggers.md
  packages/docs/pages/guide/available-apps.md
Labels: enhancement, documentation-change

#1848 feat(gitea): add gitea integration
  packages/backend/src/apps/gitea/actions/create-issue/index.js
  packages/backend/src/apps/gitea/actions/index.js
  packages/backend/src/apps/gitea/assets/favicon.svg
  packages/backend/src/apps/gitea/auth/generate-auth-url.js
  packages/backend/src/apps/gitea/auth/index.js
  packages/backend/src/apps/gitea/auth/is-still-verified.js
  packages/backend/src/apps/gitea/auth/refresh-token.js
  packages/backend/src/apps/gitea/auth/verify-credentials.js
  packages/backend/src/apps/gitea/common/add-auth-header.js
  packages/backend/src/apps/gitea/common/get-current-user.js
  packages/backend/src/apps/gitea/common/set-base-url.js
  packages/backend/src/apps/gitea/dynamic-data/index.js
  packages/backend/src/apps/gitea/dynamic-data/list-labels/index.js
  packages/backend/src/apps/gitea/dynamic-data/list-repos/index.js
  packages/backend/src/apps/gitea/index.js
  packages/backend/src/apps/gitea/triggers/index.js
  packages/backend/src/apps/gitea/triggers/new-issues/index.js
  packages/backend/src/apps/gitea/triggers/new-pull-requests/index.js
  packages/backend/src/apps/gitea/triggers/new-stargazers/index.js
  packages/backend/src/apps/gitea/triggers/new-watchers/index.js
  packages/backend/src/models/__snapshots__/app.test.js.snap
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/gitea/actions.md
  packages/docs/pages/apps/gitea/connection.md
  packages/docs/pages/apps/gitea/triggers.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/gitea.svg
Labels: integration request, documentation-change

#2341 fix(flow): copy over step name while duplicating flow
  packages/backend/src/models/flow.js
Labels: bug

#2342 fix(import-flow): update all variables in step parameters
  packages/backend/src/controllers/api/v1/flows/import-flow.test.js
  packages/backend/src/helpers/import-flow.js
Labels: bug

#2343 fix(variables): use step names in variables
  packages/web/src/components/PowerInput/data.js
Labels: enhancement

#2345 feat(formatter/date-time): add get current timestamp in seconds
  packages/backend/src/apps/formatter/actions/date-time/index.js
  packages/backend/src/apps/formatter/actions/date-time/transformers/get-current-timestamp-in-seconds.js
Labels: enhancement

#2332 feat(web): introduce folders to organize flows
  packages/web/src/components/ConfirmationDialog/index.jsx
  packages/web/src/components/CreateFolderDialog/index.jsx
  packages/web/src/components/EditFolderDialog/index.jsx
  packages/web/src/components/EditorLayout/FlowFolder.jsx
  packages/web/src/components/EditorLayout/index.jsx
  packages/web/src/components/FlowContextMenu/index.jsx
  packages/web/src/components/FlowFolderChangeDialog/index.jsx
  packages/web/src/components/FlowFolderChangeDialog/style.js
  packages/web/src/components/FlowRow/index.jsx
  packages/web/src/components/Folders/index.jsx
  packages/web/src/components/Folders/style.js
  packages/web/src/config/urls.js
  packages/web/src/hooks/useCreateFolder.js
  packages/web/src/hooks/useDeleteFolder.js
  packages/web/src/hooks/useFlowFolder.js
  packages/web/src/hooks/useFlows.js
  packages/web/src/hooks/useFolders.js
  packages/web/src/hooks/useUpdateFlowFolder.js
  packages/web/src/hooks/useUpdateFolder.js
  packages/web/src/locales/en.json
  packages/web/src/pages/Flows/index.jsx
Labels: enhancement

#2346 fix(folders): reset state on delete folder confirmation dialog close
  packages/web/src/components/Folders/index.jsx
Labels: bug

#2352 fix(folders): reset state upon deleting folder and updating flow folder
  packages/web/src/components/Folders/index.jsx
  packages/web/src/hooks/useUpdateFlowFolder.js
Labels: bug
