Repository automatisch/automatisch, pull requests merged in 2025-01, with the labels that each got.

#2266 feat: add support to rename flow step
  packages/web/src/components/ChooseAppAndEventSubstep/index.jsx
  packages/web/src/components/EditableTypography/index.jsx
  packages/web/src/components/EditableTypography/style.js
  packages/web/src/components/Editor/index.jsx
  packages/web/src/components/EditorNew/EditorNew.jsx
  packages/web/src/components/ExecutionStep/index.jsx
  packages/web/src/components/FlowStep/index.jsx
  packages/web/src/components/FlowSubstepTitle/style.jsx
  packages/web/src/hooks/useUpdateStep.js
  packages/web/src/styles/theme.js
Labels: enhancement

#2274 feat(EditableTypography): make icon size and position consistent
  packages/web/src/components/EditableTypography/index.jsx
  packages/web/src/components/EditorLayout/index.jsx
Labels: enhancement

#2275 chore(test): add missing test files in coverage
  packages/backend/vitest.config.js
Labels: enhancement

#2280 docs: Add REDIS_DB env variable to configuration
  packages/docs/pages/advanced/configuration.md
Labels: documentation-change

#2286 fix(workers): correct worker for trigger queue
  packages/backend/src/workers/trigger.js
Labels: bug

#2287 feat: add freescout app with new event trigger
  packages/backend/src/apps/freescout/assets/favicon.svg
  packages/backend/src/apps/freescout/auth/index.js
  packages/backend/src/apps/freescout/auth/is-still-verified.js
  packages/backend/src/apps/freescout/auth/verify-credentials.js
  packages/backend/src/apps/freescout/common/add-auth-header.js
  packages/backend/src/apps/freescout/common/set-base-url.js
  packages/backend/src/apps/freescout/common/webhook-filters.js
  packages/backend/src/apps/freescout/index.js
  packages/backend/src/apps/freescout/triggers/index.js
  packages/backend/src/apps/freescout/triggers/new-event/index.js
  packages/backend/src/models/__snapshots__/app.test.js.snap
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/freescout/connection.md
  packages/docs/pages/apps/freescout/triggers.md
  packages/docs/pages/public/favicons/freescout.svg
Labels: integration request, documentation-change

#2293 feat(web): add import flow functionality
  packages/web/src/components/ConditionalIconButton/index.jsx
  packages/web/src/components/FileUploadInput/index.js
  packages/web/src/components/ImportFlowDialog/index.jsx
  packages/web/src/config/urls.js
  packages/web/src/hooks/useImportFlow.js
  packages/web/src/locales/en.json
  packages/web/src/pages/Flow/index.jsx
  packages/web/src/pages/Flows/index.jsx
  packages/web/src/routes.jsx
Labels: enhancement

#2294 feat(ImportFlowDialog): improve error management and user experience
  packages/web/src/components/ImportFlowDialog/index.jsx
  packages/web/src/helpers/errors.js
Labels: enhancement

#2298 fix(apps/get-flows): respond with distinct flows
  packages/backend/src/controllers/api/v1/apps/get-flows.js
  packages/backend/src/controllers/api/v1/connections/get-flows.js
Labels: bug

#2296 feat(scheduler): add every N minutes trigger
  packages/backend/src/apps/scheduler/common/cron-times.js
  packages/backend/src/apps/scheduler/triggers/every-n-minutes/index.js
  packages/backend/src/apps/scheduler/triggers/index.js
  packages/backend/src/helpers/define-trigger.js
  packages/docs/pages/apps/scheduler/triggers.md
Labels: integration request, documentation-change

#2295 feat(useImportFlow): invalidate flows on success
  packages/web/src/components/FlowContextMenu/index.jsx
  packages/web/src/components/FlowRow/index.jsx
  packages/web/src/hooks/useDeleteFlow.js
  packages/web/src/hooks/useDuplicateFlow.js
  packages/web/src/hooks/useFlows.js
  packages/web/src/hooks/useImportFlow.js
  packages/web/src/hooks/useLazyFlows.js
  packages/web/src/pages/Flows/index.jsx
Labels: enhancement

#2299 feat(anthropic): add anthropic app with send message action
  packages/backend/src/apps/anthropic/actions/index.js
  packages/backend/src/apps/anthropic/actions/send-message/index.js
  packages/backend/src/apps/anthropic/assets/favicon.svg
  packages/backend/src/apps/anthropic/auth/index.js
  packages/backend/src/apps/anthropic/auth/is-still-verified.js
  packages/backend/src/apps/anthropic/auth/verify-credentials.js
  packages/backend/src/apps/anthropic/common/add-anthropic-version-header.js
  packages/backend/src/apps/anthropic/common/add-auth-header.js
  packages/backend/src/apps/anthropic/dynamic-data/index.js
  packages/backend/src/apps/anthropic/dynamic-data/list-models/index.js
  packages/backend/src/apps/anthropic/index.js
  packages/backend/src/models/__snapshots__/app.test.js.snap
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/anthropic/actions.md
  packages/docs/pages/apps/anthropic/connection.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/anthropic.svg
Labels: integration request, documentation-change

#2301 feat(perplexity): add perplexity app with send chat prompt action
  packages/backend/src/apps/perplexity/actions/index.js
  packages/backend/src/apps/perplexity/actions/send-chat-prompt/index.js
  packages/backend/src/apps/perplexity/assets/favicon.svg
  packages/backend/src/apps/perplexity/auth/index.js
  packages/backend/src/apps/perplexity/auth/is-still-verified.js
  packages/backend/src/apps/perplexity/auth/verify-credentials.js
  packages/backend/src/apps/perplexity/common/add-auth-header.js
  packages/backend/src/apps/perplexity/index.js
  packages/backend/src/models/__snapshots__/app.test.js.snap
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/perplexity/actions.md
  packages/docs/pages/apps/perplexity/connection.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/perplexity.svg
Labels: integration request, documentation-change

#2302 feat(together-ai): add app with create completion and create chat completion actions
  packages/backend/src/apps/together-ai/actions/create-chat-completion/index.js
  packages/backend/src/apps/together-ai/actions/create-completion/index.js
  packages/backend/src/apps/together-ai/actions/index.js
  packages/backend/src/apps/together-ai/assets/favicon.svg
  packages/backend/src/apps/together-ai/auth/index.js
  packages/backend/src/apps/together-ai/auth/is-still-verified.js
  packages/backend/src/apps/together-ai/auth/verify-credentials.js
  packages/backend/src/apps/together-ai/common/add-auth-header.js
  packages/backend/src/apps/together-ai/dynamic-data/index.js
  packages/backend/src/apps/together-ai/dynamic-data/list-models/index.js
  packages/backend/src/apps/together-ai/index.js
  packages/backend/src/models/__snapshots__/app.test.js.snap
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/together-ai/actions.md
  packages/docs/pages/apps/together-ai/connection.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/together-ai.svg
Labels: integration request, documentation-change

#2303 feat(mistral-ai): add app with create chat completion action
  packages/backend/src/apps/mistral-ai/actions/create-chat-completion/index.js
  packages/backend/src/apps/mistral-ai/actions/index.js
  packages/backend/src/apps/mistral-ai/assets/favicon.svg
  packages/backend/src/apps/mistral-ai/auth/index.js
  packages/backend/src/apps/mistral-ai/auth/is-still-verified.js
  packages/backend/src/apps/mistral-ai/auth/verify-credentials.js
  packages/backend/src/apps/mistral-ai/common/add-auth-header.js
  packages/backend/src/apps/mistral-ai/dynamic-data/index.js
  packages/backend/src/apps/mistral-ai/dynamic-data/list-models/index.js
  packages/backend/src/apps/mistral-ai/index.js
  packages/backend/src/models/__snapshots__/app.test.js.snap
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/mistral-ai/actions.md
  packages/docs/pages/apps/mistral-ai/connection.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/mistral-ai.svg
Labels: integration request, documentation-change

#2304 feat(openrouter): add app with create chat completion action
  packages/backend/src/apps/openrouter/actions/create-chat-completion/index.js
  packages/backend/src/apps/openrouter/actions/index.js
  packages/backend/src/apps/openrouter/assets/favicon.svg
  packages/backend/src/apps/openrouter/auth/index.js
  packages/backend/src/apps/openrouter/auth/is-still-verified.js
  packages/backend/src/apps/openrouter/auth/verify-credentials.js
  packages/backend/src/apps/openrouter/common/add-auth-header.js
  packages/backend/src/apps/openrouter/dynamic-data/index.js
  packages/backend/src/apps/openrouter/dynamic-data/list-models/index.js
  packages/backend/src/apps/openrouter/index.js
  packages/backend/src/models/__snapshots__/app.test.js.snap
  packages/docs/pages/.vitepress/config.js
  packages/docs/pages/apps/openrouter/actions.md
  packages/docs/pages/apps/openrouter/connection.md
  packages/docs/pages/guide/available-apps.md
  packages/docs/pages/public/favicons/openrouter.svg
Labels: integration request, documentation-change

#2312 fix(anthorpic/send-message): fix action key
  packages/backend/src/apps/anthropic/actions/send-message/index.js
Labels: bug

#2315 feat(virtualq/actions): add properties JSON field
  packages/backend/src/apps/virtualq/actions/create-waiter/index.js
  packages/backend/src/apps/virtualq/actions/update-waiter/index.js
  packages/backend/src/apps/virtualq/index.js
  packages/backend/src/services/action.js
  packages/backend/src/services/flow.js
Labels: enhancement
